name: Release cleanroom workload infrastructure containers
description: Release cleanroom workload infrastructure containers
inputs:
  tag:
    description: The tag
    required: true
  environment:
    description: The environment being released to
    required: true
  registry-name:
    description: The registry to which the images need to be pushed
    required: true
  client-id:
    description: The client ID to connect to the registry
    required: true
  tenant-id:
    description: The tenant ID of the registry
    required: true
  subscription-id:
    description: The subscription ID of the registry
    required: true
  needs-attestation:
    description: Whether the container needs attestation
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/release-container
      with:
        name: workloads/cleanroom-spark-analytics-agent
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cleanroom-spark-analytics-agent
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-container
      with:
        name: workloads/cleanroom-spark-frontend
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cleanroom-spark-frontend
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-container
      with:
        name: workloads/cleanroom-spark-analytics-app
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cleanroom-spark-analytics-app
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-helm-chart
      with:
        name: workloads/helm/cleanroom-spark-analytics-agent
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cleanroom-spark-analytics-agent-helm
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-helm-chart
      with:
        name: workloads/helm/cleanroom-spark-frontend
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: cleanroom-spark-frontend-helm
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-helm-chart
      with:
        name: workloads/helm/frontend-service
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: frontend-service-helm
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-container
      with:
        name: workloads/kserve-inferencing-agent
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: kserve-inferencing-agent
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-container
      with:
        name: workloads/kserve-inferencing-frontend
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: kserve-inferencing-frontend
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-container
      with:
        name: workloads/ohttp-gateway
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: ohttp-gateway
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-helm-chart
      with:
        name: workloads/helm/kserve-inferencing-agent
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: kserve-inferencing-agent-helm
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}

    - uses: ./.github/actions/release-helm-chart
      with:
        name: workloads/helm/kserve-inferencing-frontend
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        artefact-name: kserve-inferencing-frontend-helm
        registry-name: ${{ inputs.registry-name }}
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        needs-attestation: ${{ inputs.needs-attestation }}