name: Release sidecar digests
description: Release sidecar digests
inputs:
  tag:
    description: The tag
    required: true
  environment:
    description: The environment being released to
    required: true
  registry-name:
    description: The registry to which the images need to be pushed
    required: true
  client-id:
    description: The client ID to connect to the registry
    required: true
  tenant-id:
    description: The tenant ID of the registry
    required: true
  subscription-id:
    description: The subscription ID of the registry
    required: true
  needs-attestation:
    description: Whether the container needs attestation
    required: true

runs:
  using: composite
  steps:
    - uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}

    # The azure/docker-login action currently does not support authentication using
    # federated credentials - https://github.com/Azure/docker-login/issues/56. Hence,
    # resorting to a manual login.
    - shell: bash
      run: az acr login --name ${{ inputs.registry-name }}

    - shell: pwsh
      run: Install-Module -Name powershell-yaml -Force

    - shell: pwsh
      run: |
        ./build/build-ccr-digests.ps1 -repo ${{ inputs.registry-name }}.azurecr.io/${{ inputs.environment }}/cleanroom -tag ${{ inputs.tag }} -push

    - uses: actions/upload-artifact@v4
      with:
        name: sidecar-digests-${{ inputs.environment }}.yaml
        path: ./sidecar-digests.yaml
        overwrite: true

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/blobfuse-launcher-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/ccr-attestation-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/ccr-governance-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/ccr-init-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/ccr-secrets-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/ccr-proxy-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/ccr-proxy-ext-processor-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/code-launcher-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/identity-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/otel-collector-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: policies/skr-policy
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}

    - uses: ./.github/actions/attest-artefact
      if: ${{ inputs.needs-attestation == 'true' }}
      with:
        name: sidecar-digests
        tag: ${{ inputs.tag }}
        environment: ${{ inputs.environment }}
        registry-name: ${{ inputs.registry-name }}