// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> A factory class for creating instances of the models for mocking. </summary>
    public static partial class AzureCleanroomGovernanceClientModelFactory
    {
        /// <summary> Generate CA signing key response. </summary>
        /// <param name="requestId"> Request ID. </param>
        /// <returns> A new <see cref="Client.GenerateCASigningKeyResponse"/> instance for mocking. </returns>
        public static GenerateCASigningKeyResponse GenerateCASigningKeyResponse(string requestId = default)
        {
            return new GenerateCASigningKeyResponse(requestId, additionalBinaryDataProperties: null);
        }

        /// <summary> Generate endorsed cert request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <param name="sign"> Signature. </param>
        /// <param name="data"> Encrypted request data. </param>
        /// <returns> A new <see cref="Client.GenerateEndorsedCertRequest"/> instance for mocking. </returns>
        public static GenerateEndorsedCertRequest GenerateEndorsedCertRequest(SnpEvidence attestation = default, Encrypt encrypt = default, Sign sign = default, string data = default)
        {
            return new GenerateEndorsedCertRequest(attestation, encrypt, sign, data, additionalBinaryDataProperties: null);
        }

        /// <summary> SNP attestation evidence. </summary>
        /// <param name="evidence"> Base64 encoded evidence. </param>
        /// <param name="endorsements"> Base64 encoded endorsements. </param>
        /// <param name="uvmEndorsements"> Base64 encoded UVM endorsements. </param>
        /// <param name="endorsedTcb"> Endorsed TCB version. </param>
        /// <returns> A new <see cref="Client.SnpEvidence"/> instance for mocking. </returns>
        public static SnpEvidence SnpEvidence(string evidence = default, string endorsements = default, string uvmEndorsements = default, string endorsedTcb = default)
        {
            return new SnpEvidence(evidence, endorsements, uvmEndorsements, endorsedTcb, additionalBinaryDataProperties: null);
        }

        /// <summary> Encryption information. </summary>
        /// <param name="publicKey"> PEM encoded public key. </param>
        /// <returns> A new <see cref="Client.Encrypt"/> instance for mocking. </returns>
        public static Encrypt Encrypt(string publicKey = default)
        {
            return new Encrypt(publicKey, additionalBinaryDataProperties: null);
        }

        /// <summary> Digital signature information. </summary>
        /// <param name="signature"> Signature value. </param>
        /// <param name="publicKey"> PEM encoded public key. </param>
        /// <returns> A new <see cref="Client.Sign"/> instance for mocking. </returns>
        public static Sign Sign(string signature = default, string publicKey = default)
        {
            return new Sign(signature, publicKey, additionalBinaryDataProperties: null);
        }

        /// <summary> Generate endorsed cert response. </summary>
        /// <param name="value"> base64 wrapped certificate. </param>
        /// <returns> A new <see cref="Client.GenerateEndorsedCertResponse"/> instance for mocking. </returns>
        public static GenerateEndorsedCertResponse GenerateEndorsedCertResponse(string value = default)
        {
            return new GenerateEndorsedCertResponse(value, additionalBinaryDataProperties: null);
        }

        /// <summary> CA info. </summary>
        /// <param name="enabled"> CA enabled. </param>
        /// <param name="caCert"> CA certificate. </param>
        /// <param name="publicKey"> Public key. </param>
        /// <param name="proposalIds"> Proposal IDs. </param>
        /// <returns> A new <see cref="Client.CAInfo"/> instance for mocking. </returns>
        public static CAInfo CAInfo(bool enabled = default, string caCert = default, string publicKey = default, IEnumerable<string> proposalIds = default)
        {
            proposalIds ??= new ChangeTrackingList<string>();

            return new CAInfo(enabled, caCert, publicKey, proposalIds.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Get clean room policy response. </summary>
        /// <param name="proposalIds"> Proposal IDs. </param>
        /// <param name="policy"> Policy data. </param>
        /// <returns> A new <see cref="Client.GetCleanRoomPolicyResponse"/> instance for mocking. </returns>
        public static GetCleanRoomPolicyResponse GetCleanRoomPolicyResponse(IEnumerable<string> proposalIds = default, BinaryData policy = default)
        {
            proposalIds ??= new ChangeTrackingList<string>();

            return new GetCleanRoomPolicyResponse(proposalIds.ToList(), policy, additionalBinaryDataProperties: null);
        }

        /// <summary> List delegate policies response. </summary>
        /// <param name="value"> Array of delegate policies. </param>
        /// <returns> A new <see cref="Client.ListDelegatePoliciesResponse"/> instance for mocking. </returns>
        public static ListDelegatePoliciesResponse ListDelegatePoliciesResponse(IEnumerable<ListDelegatePolicyResponse> value = default)
        {
            value ??= new ChangeTrackingList<ListDelegatePolicyResponse>();

            return new ListDelegatePoliciesResponse(value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> List delegate policy response. </summary>
        /// <param name="delegateType"> Delegate type. </param>
        /// <param name="delegateId"> Delegate ID. </param>
        /// <returns> A new <see cref="Client.ListDelegatePolicyResponse"/> instance for mocking. </returns>
        public static ListDelegatePolicyResponse ListDelegatePolicyResponse(string delegateType = default, string delegateId = default)
        {
            return new ListDelegatePolicyResponse(delegateType, delegateId, additionalBinaryDataProperties: null);
        }

        /// <summary> Get delegate policy response. </summary>
        /// <param name="claims"> Delegate policy properties. </param>
        /// <returns> A new <see cref="Client.GetDelegatePolicyResponse"/> instance for mocking. </returns>
        public static GetDelegatePolicyResponse GetDelegatePolicyResponse(CleanRoomPolicyProps claims = default)
        {
            return new GetDelegatePolicyResponse(claims, additionalBinaryDataProperties: null);
        }

        /// <summary> Clean room policy properties for SEV-SNP attestation. </summary>
        /// <param name="authorKeyDigest"> Author key digest values. </param>
        /// <param name="familyId"> Family ID values. </param>
        /// <param name="guestSvn"> Guest SVN values. </param>
        /// <param name="hostData"> Host data values. </param>
        /// <param name="idKeyDigest"> ID key digest values. </param>
        /// <param name="imageId"> Image ID values. </param>
        /// <param name="isDebuggable"> Indicates if debugging is allowed. </param>
        /// <param name="launchMeasurement"> Launch measurement values. </param>
        /// <param name="reportData"> Report data values. </param>
        /// <param name="reportId"> Report ID values. </param>
        /// <param name="smtAllowed"> Indicates if SMT is allowed. </param>
        /// <param name="vmpl"> VMPL values. </param>
        /// <param name="version"> Version values. </param>
        /// <returns> A new <see cref="Client.CleanRoomPolicyProps"/> instance for mocking. </returns>
        public static CleanRoomPolicyProps CleanRoomPolicyProps(IEnumerable<string> authorKeyDigest = default, IEnumerable<string> familyId = default, IEnumerable<int> guestSvn = default, IEnumerable<string> hostData = default, IEnumerable<string> idKeyDigest = default, IEnumerable<string> imageId = default, bool? isDebuggable = default, IEnumerable<string> launchMeasurement = default, IEnumerable<string> reportData = default, IEnumerable<string> reportId = default, bool? smtAllowed = default, IEnumerable<int> vmpl = default, IEnumerable<string> version = default)
        {
            authorKeyDigest ??= new ChangeTrackingList<string>();
            familyId ??= new ChangeTrackingList<string>();
            guestSvn ??= new ChangeTrackingList<int>();
            hostData ??= new ChangeTrackingList<string>();
            idKeyDigest ??= new ChangeTrackingList<string>();
            imageId ??= new ChangeTrackingList<string>();
            launchMeasurement ??= new ChangeTrackingList<string>();
            reportData ??= new ChangeTrackingList<string>();
            reportId ??= new ChangeTrackingList<string>();
            vmpl ??= new ChangeTrackingList<int>();
            version ??= new ChangeTrackingList<string>();

            return new CleanRoomPolicyProps(
                authorKeyDigest.ToList(),
                familyId.ToList(),
                guestSvn.ToList(),
                hostData.ToList(),
                idKeyDigest.ToList(),
                imageId.ToList(),
                isDebuggable,
                launchMeasurement.ToList(),
                reportData.ToList(),
                reportId.ToList(),
                smtAllowed,
                vmpl.ToList(),
                version.ToList(),
                additionalBinaryDataProperties: null);
        }

        /// <summary> Set delegate clean room policy request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <param name="sign"> Signature. </param>
        /// <param name="data"> Encrypted request data. </param>
        /// <returns> A new <see cref="Client.SetDelegateCleanRoomPolicyRequest"/> instance for mocking. </returns>
        public static SetDelegateCleanRoomPolicyRequest SetDelegateCleanRoomPolicyRequest(SnpEvidence attestation = default, Encrypt encrypt = default, Sign sign = default, string data = default)
        {
            return new SetDelegateCleanRoomPolicyRequest(attestation, encrypt, sign, data, additionalBinaryDataProperties: null);
        }

        /// <summary> Get runtime option response. </summary>
        /// <param name="status"> Runtime option status. </param>
        /// <param name="reason"> Error reason. </param>
        /// <param name="proposalIds"> Proposal IDs. </param>
        /// <returns> A new <see cref="Client.GetRuntimeOptionResponse"/> instance for mocking. </returns>
        public static GetRuntimeOptionResponse GetRuntimeOptionResponse(string status = default, ErrorReason reason = default, IEnumerable<string> proposalIds = default)
        {
            proposalIds ??= new ChangeTrackingList<string>();

            return new GetRuntimeOptionResponse(status, reason, proposalIds.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Error reason. </summary>
        /// <param name="code"> Error code. </param>
        /// <param name="message"> Error message. </param>
        /// <returns> A new <see cref="Client.ErrorReason"/> instance for mocking. </returns>
        public static ErrorReason ErrorReason(string code = default, string message = default)
        {
            return new ErrorReason(code, message, additionalBinaryDataProperties: null);
        }

        /// <summary> List contracts response. </summary>
        /// <param name="value"> Array of contracts. </param>
        /// <returns> A new <see cref="Client.ListContractsResponse"/> instance for mocking. </returns>
        public static ListContractsResponse ListContractsResponse(IEnumerable<ListContractResponse> value = default)
        {
            value ??= new ChangeTrackingList<ListContractResponse>();

            return new ListContractsResponse(value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> List contract response. </summary>
        /// <param name="id"> Contract ID. </param>
        /// <returns> A new <see cref="Client.ListContractResponse"/> instance for mocking. </returns>
        public static ListContractResponse ListContractResponse(string id = default)
        {
            return new ListContractResponse(id, additionalBinaryDataProperties: null);
        }

        /// <summary> Put contract request. </summary>
        /// <param name="version"> Contract version. </param>
        /// <param name="data"> Contract data. </param>
        /// <returns> A new <see cref="Client.PutContractRequest"/> instance for mocking. </returns>
        public static PutContractRequest PutContractRequest(string version = default, BinaryData data = default)
        {
            return new PutContractRequest(version, data, additionalBinaryDataProperties: null);
        }

        /// <summary> Get contract response. </summary>
        /// <param name="id"> Contract ID. </param>
        /// <param name="version"> Contract version. </param>
        /// <param name="data"> Contract data. </param>
        /// <param name="state"> Contract state. </param>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <param name="finalVotes"> Final votes. </param>
        /// <returns> A new <see cref="Client.GetContractResponse"/> instance for mocking. </returns>
        public static GetContractResponse GetContractResponse(string id = default, string version = default, BinaryData data = default, string state = default, string proposalId = default, IEnumerable<MemberVote> finalVotes = default)
        {
            finalVotes ??= new ChangeTrackingList<MemberVote>();

            return new GetContractResponse(
                id,
                version,
                data,
                state,
                proposalId,
                finalVotes.ToList(),
                additionalBinaryDataProperties: null);
        }

        /// <summary> Member vote. </summary>
        /// <param name="memberId"> Member ID. </param>
        /// <param name="vote"> Vote value. </param>
        /// <returns> A new <see cref="Client.MemberVote"/> instance for mocking. </returns>
        public static MemberVote MemberVote(string memberId = default, bool vote = default)
        {
            return new MemberVote(memberId, vote, additionalBinaryDataProperties: null);
        }

        /// <summary> Get deployment info response. </summary>
        /// <param name="proposalIds"> Proposal IDs. </param>
        /// <param name="data"> Deployment info data. </param>
        /// <returns> A new <see cref="Client.GetDeploymentInfoResponse"/> instance for mocking. </returns>
        public static GetDeploymentInfoResponse GetDeploymentInfoResponse(IEnumerable<string> proposalIds = default, BinaryData data = default)
        {
            proposalIds ??= new ChangeTrackingList<string>();

            return new GetDeploymentInfoResponse(proposalIds.ToList(), data, additionalBinaryDataProperties: null);
        }

        /// <summary> Get deployment spec response. </summary>
        /// <param name="proposalIds"> Proposal IDs. </param>
        /// <param name="data"> Deployment spec data. </param>
        /// <returns> A new <see cref="Client.GetDeploymentSpecResponse"/> instance for mocking. </returns>
        public static GetDeploymentSpecResponse GetDeploymentSpecResponse(IEnumerable<string> proposalIds = default, BinaryData data = default)
        {
            proposalIds ??= new ChangeTrackingList<string>();

            return new GetDeploymentSpecResponse(proposalIds.ToList(), data, additionalBinaryDataProperties: null);
        }

        /// <summary> Get events response. </summary>
        /// <param name="nextLink"> Next link for pagination. </param>
        /// <param name="value"> Array of events. </param>
        /// <returns> A new <see cref="Client.GetEventsResponse"/> instance for mocking. </returns>
        public static GetEventsResponse GetEventsResponse(string nextLink = default, IEnumerable<Event> value = default)
        {
            value ??= new ChangeTrackingList<Event>();

            return new GetEventsResponse(nextLink, value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Event. </summary>
        /// <param name="timestamp"> Event timestamp. </param>
        /// <param name="timestampIso"> Event timestamp ISO format. </param>
        /// <param name="scope"> Event scope. </param>
        /// <param name="id"> Event ID. </param>
        /// <param name="seqno"> Sequence number. </param>
        /// <param name="data"> Event data. </param>
        /// <returns> A new <see cref="Client.Event"/> instance for mocking. </returns>
        public static Event Event(string timestamp = default, string timestampIso = default, string scope = default, string id = default, int seqno = default, BinaryData data = default)
        {
            return new Event(
                timestamp,
                timestampIso,
                scope,
                id,
                seqno,
                data,
                additionalBinaryDataProperties: null);
        }

        /// <summary> Put event request. </summary>
        /// <param name="timestamp"> Event timestamp. </param>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="sign"> Signature. </param>
        /// <param name="data"> Event data. </param>
        /// <returns> A new <see cref="Client.PutEventRequest"/> instance for mocking. </returns>
        public static PutEventRequest PutEventRequest(string timestamp = default, SnpEvidence attestation = default, Sign sign = default, BinaryData data = default)
        {
            return new PutEventRequest(timestamp, attestation, sign, data, additionalBinaryDataProperties: null);
        }

        /// <summary> List member document response. </summary>
        /// <param name="id"> Document ID. </param>
        /// <returns> A new <see cref="Client.ListMemberDocumentResponse"/> instance for mocking. </returns>
        public static ListMemberDocumentResponse ListMemberDocumentResponse(string id = default)
        {
            return new ListMemberDocumentResponse(id, additionalBinaryDataProperties: null);
        }

        /// <summary> Put member document request. </summary>
        /// <param name="version"> Document version. </param>
        /// <param name="contractId"> Contract ID. </param>
        /// <param name="data"> Document data. </param>
        /// <returns> A new <see cref="Client.PutMemberDocumentRequest"/> instance for mocking. </returns>
        public static PutMemberDocumentRequest PutMemberDocumentRequest(string version = default, string contractId = default, BinaryData data = default)
        {
            return new PutMemberDocumentRequest(version, contractId, data, additionalBinaryDataProperties: null);
        }

        /// <summary> Get member document response. </summary>
        /// <param name="id"> Document ID. </param>
        /// <param name="contractId"> Contract ID. </param>
        /// <param name="version"> Document version. </param>
        /// <param name="data"> Document data. </param>
        /// <param name="state"> Document state. </param>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <param name="finalVotes"> Final votes. </param>
        /// <returns> A new <see cref="Client.GetMemberDocumentResponse"/> instance for mocking. </returns>
        public static GetMemberDocumentResponse GetMemberDocumentResponse(string id = default, string contractId = default, string version = default, BinaryData data = default, string state = default, string proposalId = default, IEnumerable<MemberVote> finalVotes = default)
        {
            finalVotes ??= new ChangeTrackingList<MemberVote>();

            return new GetMemberDocumentResponse(
                id,
                contractId,
                version,
                data,
                state,
                proposalId,
                finalVotes.ToList(),
                additionalBinaryDataProperties: null);
        }

        /// <summary> Get accepted member document request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <returns> A new <see cref="Client.GetAcceptedMemberDocumentRequest"/> instance for mocking. </returns>
        public static GetAcceptedMemberDocumentRequest GetAcceptedMemberDocumentRequest(SnpEvidence attestation = default, Encrypt encrypt = default)
        {
            return new GetAcceptedMemberDocumentRequest(attestation, encrypt, additionalBinaryDataProperties: null);
        }

        /// <summary> Get accepted member document response. </summary>
        /// <param name="value"> Encrypted GetDocumentResponse content. </param>
        /// <returns> A new <see cref="Client.GetAcceptedMemberDocumentResponse"/> instance for mocking. </returns>
        public static GetAcceptedMemberDocumentResponse GetAcceptedMemberDocumentResponse(string value = default)
        {
            return new GetAcceptedMemberDocumentResponse(value, additionalBinaryDataProperties: null);
        }

        /// <summary> Discovery response. </summary>
        /// <param name="responseTypesSupported"> Supported response types. </param>
        /// <param name="idTokenSigningAlgValuesSupported"> Supported ID token signing algorithms. </param>
        /// <param name="issuer"> Issuer URL. </param>
        /// <param name="jwksUri"> JWKS URI. </param>
        /// <param name="claimsSupported"> Supported claims. </param>
        /// <returns> A new <see cref="Client.DiscoveryResponse"/> instance for mocking. </returns>
        public static DiscoveryResponse DiscoveryResponse(IEnumerable<string> responseTypesSupported = default, IEnumerable<string> idTokenSigningAlgValuesSupported = default, string issuer = default, string jwksUri = default, IEnumerable<string> claimsSupported = default)
        {
            responseTypesSupported ??= new ChangeTrackingList<string>();
            idTokenSigningAlgValuesSupported ??= new ChangeTrackingList<string>();
            claimsSupported ??= new ChangeTrackingList<string>();

            return new DiscoveryResponse(
                responseTypesSupported.ToList(),
                idTokenSigningAlgValuesSupported.ToList(),
                issuer,
                jwksUri,
                claimsSupported.ToList(),
                additionalBinaryDataProperties: null);
        }

        /// <summary> JWKS response. </summary>
        /// <param name="keys"> Array of JWK keys. </param>
        /// <returns> A new <see cref="Client.JwksResponse"/> instance for mocking. </returns>
        public static JwksResponse JwksResponse(IEnumerable<Jwk> keys = default)
        {
            keys ??= new ChangeTrackingList<Jwk>();

            return new JwksResponse(keys.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> JSON Web Key. </summary>
        /// <param name="alg"> Algorithm. </param>
        /// <param name="use"> Usage. </param>
        /// <param name="e"> Exponent. </param>
        /// <param name="n"> Modulus. </param>
        /// <param name="kid"> Key ID. </param>
        /// <param name="kty"> Key type. </param>
        /// <param name="x5c"> X.509 certificate chain. </param>
        /// <param name="x5t"> X.509 certificate SHA-1 thumbprint. </param>
        /// <returns> A new <see cref="Client.Jwk"/> instance for mocking. </returns>
        public static Jwk Jwk(string alg = default, string use = default, string e = default, string n = default, string kid = default, string kty = default, IEnumerable<string> x5c = default, string x5t = default)
        {
            x5c ??= new ChangeTrackingList<string>();

            return new Jwk(
                alg,
                use,
                e,
                n,
                kid,
                kty,
                x5c.ToList(),
                x5t,
                additionalBinaryDataProperties: null);
        }

        /// <summary> Set issuer URL request. </summary>
        /// <param name="url"> Issuer URL. </param>
        /// <returns> A new <see cref="Client.SetIssuerUrlRequest"/> instance for mocking. </returns>
        public static SetIssuerUrlRequest SetIssuerUrlRequest(string url = default)
        {
            return new SetIssuerUrlRequest(url, additionalBinaryDataProperties: null);
        }

        /// <summary> OIDC issuer info. </summary>
        /// <param name="enabled"> Issuer enabled. </param>
        /// <param name="issuerUrl"> Issuer URL. </param>
        /// <param name="tenantData"> Tenant data. </param>
        /// <returns> A new <see cref="Client.OidcIssuerInfo"/> instance for mocking. </returns>
        public static OidcIssuerInfo OidcIssuerInfo(bool enabled = default, string issuerUrl = default, TenantData tenantData = default)
        {
            return new OidcIssuerInfo(enabled, issuerUrl, tenantData, additionalBinaryDataProperties: null);
        }

        /// <summary> Tenant data. </summary>
        /// <param name="tenantId"> Tenant ID. </param>
        /// <param name="issuerUrl"> Issuer URL. </param>
        /// <returns> A new <see cref="Client.TenantData"/> instance for mocking. </returns>
        public static TenantData TenantData(string tenantId = default, string issuerUrl = default)
        {
            return new TenantData(tenantId, issuerUrl, additionalBinaryDataProperties: null);
        }

        /// <summary> Get proposal response. </summary>
        /// <param name="nextLink"> Next link for pagination. </param>
        /// <param name="value"> Array of proposals. </param>
        /// <returns> A new <see cref="Client.GetProposalResponse"/> instance for mocking. </returns>
        public static GetProposalResponse GetProposalResponse(string nextLink = default, IEnumerable<Proposal> value = default)
        {
            value ??= new ChangeTrackingList<Proposal>();

            return new GetProposalResponse(nextLink, value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Proposal. </summary>
        /// <param name="seqno"> Sequence number. </param>
        /// <param name="proposalState"> Proposal state. </param>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <returns> A new <see cref="Client.Proposal"/> instance for mocking. </returns>
        public static Proposal Proposal(int seqno = default, string proposalState = default, string proposalId = default)
        {
            return new Proposal(seqno, proposalState, proposalId, additionalBinaryDataProperties: null);
        }

        /// <summary> List secrets response. </summary>
        /// <param name="value"> Array of secrets. </param>
        /// <returns> A new <see cref="Client.ListSecretsResponse"/> instance for mocking. </returns>
        public static ListSecretsResponse ListSecretsResponse(IEnumerable<ListSecretResponse> value = default)
        {
            value ??= new ChangeTrackingList<ListSecretResponse>();

            return new ListSecretsResponse(value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> List secret response. </summary>
        /// <param name="secretId"> Secret ID. </param>
        /// <returns> A new <see cref="Client.ListSecretResponse"/> instance for mocking. </returns>
        public static ListSecretResponse ListSecretResponse(string secretId = default)
        {
            return new ListSecretResponse(secretId, additionalBinaryDataProperties: null);
        }

        /// <summary> Put secret by member/user request. </summary>
        /// <param name="value"> Secret value. </param>
        /// <returns> A new <see cref="Client.PutSecretByMemberUserRequest"/> instance for mocking. </returns>
        public static PutSecretByMemberUserRequest PutSecretByMemberUserRequest(string value = default)
        {
            return new PutSecretByMemberUserRequest(value, additionalBinaryDataProperties: null);
        }

        /// <summary> Put secret by clean room request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <param name="sign"> Signature. </param>
        /// <param name="data"> Encrypted data. </param>
        /// <returns> A new <see cref="Client.PutSecretByCleanRoomRequest"/> instance for mocking. </returns>
        public static PutSecretByCleanRoomRequest PutSecretByCleanRoomRequest(SnpEvidence attestation = default, Encrypt encrypt = default, Sign sign = default, string data = default)
        {
            return new PutSecretByCleanRoomRequest(attestation, encrypt, sign, data, additionalBinaryDataProperties: null);
        }

        /// <summary> Put secret response. </summary>
        /// <param name="secretId"> Secret ID. </param>
        /// <returns> A new <see cref="Client.PutSecretResponse"/> instance for mocking. </returns>
        public static PutSecretResponse PutSecretResponse(string secretId = default)
        {
            return new PutSecretResponse(secretId, additionalBinaryDataProperties: null);
        }

        /// <summary> Get secret request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <returns> A new <see cref="Client.GetSecretRequest"/> instance for mocking. </returns>
        public static GetSecretRequest GetSecretRequest(SnpEvidence attestation = default, Encrypt encrypt = default)
        {
            return new GetSecretRequest(attestation, encrypt, additionalBinaryDataProperties: null);
        }

        /// <summary> Get secret response. </summary>
        /// <param name="value"> Secret value. </param>
        /// <returns> A new <see cref="Client.GetSecretResponse"/> instance for mocking. </returns>
        public static GetSecretResponse GetSecretResponse(string value = default)
        {
            return new GetSecretResponse(value, additionalBinaryDataProperties: null);
        }

        /// <summary> Sign payload response. </summary>
        /// <param name="value"> Base64 wrapped signed value. </param>
        /// <returns> A new <see cref="Client.SignPayloadResponse"/> instance for mocking. </returns>
        public static SignPayloadResponse SignPayloadResponse(string value = default)
        {
            return new SignPayloadResponse(value, additionalBinaryDataProperties: null);
        }

        /// <summary> Generate signing key response. </summary>
        /// <param name="reqId"> Request ID. </param>
        /// <param name="kid"> Key ID. </param>
        /// <returns> A new <see cref="Client.GenerateSigningKeyResponse"/> instance for mocking. </returns>
        public static GenerateSigningKeyResponse GenerateSigningKeyResponse(string reqId = default, string kid = default)
        {
            return new GenerateSigningKeyResponse(reqId, kid, additionalBinaryDataProperties: null);
        }

        /// <summary> Signing info. </summary>
        /// <param name="enabled"> Signing enabled. </param>
        /// <param name="publicKeyPem"> PEM encoded public key. </param>
        /// <returns> A new <see cref="Client.SigningInfo"/> instance for mocking. </returns>
        public static SigningInfo SigningInfo(bool enabled = default, string publicKeyPem = default)
        {
            return new SigningInfo(enabled, publicKeyPem, additionalBinaryDataProperties: null);
        }

        /// <summary> Get token request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <returns> A new <see cref="Client.GetTokenRequest"/> instance for mocking. </returns>
        public static GetTokenRequest GetTokenRequest(SnpEvidence attestation = default, Encrypt encrypt = default)
        {
            return new GetTokenRequest(attestation, encrypt, additionalBinaryDataProperties: null);
        }

        /// <summary> Get token response. </summary>
        /// <param name="value"> Token value. </param>
        /// <returns> A new <see cref="Client.GetTokenResponse"/> instance for mocking. </returns>
        public static GetTokenResponse GetTokenResponse(string value = default)
        {
            return new GetTokenResponse(value, additionalBinaryDataProperties: null);
        }

        /// <summary> List user documents response. </summary>
        /// <param name="value"> Array of user documents. </param>
        /// <returns> A new <see cref="Client.ListUserDocumentsResponse"/> instance for mocking. </returns>
        public static ListUserDocumentsResponse ListUserDocumentsResponse(IEnumerable<ListUserDocumentResponse> value = default)
        {
            value ??= new ChangeTrackingList<ListUserDocumentResponse>();

            return new ListUserDocumentsResponse(value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> List user document response. </summary>
        /// <param name="id"> Document ID. </param>
        /// <param name="labels"> Labels. </param>
        /// <returns> A new <see cref="Client.ListUserDocumentResponse"/> instance for mocking. </returns>
        public static ListUserDocumentResponse ListUserDocumentResponse(string id = default, IDictionary<string, string> labels = default)
        {
            labels ??= new ChangeTrackingDictionary<string, string>();

            return new ListUserDocumentResponse(id, labels, additionalBinaryDataProperties: null);
        }

        /// <summary> Put user document request. </summary>
        /// <param name="version"> Document version. </param>
        /// <param name="contractId"> Contract ID. </param>
        /// <param name="approvers"> Approvers. </param>
        /// <param name="data"> Document data. </param>
        /// <param name="labels"> Labels. </param>
        /// <returns> A new <see cref="Client.PutUserDocumentRequest"/> instance for mocking. </returns>
        public static PutUserDocumentRequest PutUserDocumentRequest(string version = default, string contractId = default, IEnumerable<UserProposalApprover> approvers = default, BinaryData data = default, IDictionary<string, string> labels = default)
        {
            approvers ??= new ChangeTrackingList<UserProposalApprover>();
            labels ??= new ChangeTrackingDictionary<string, string>();

            return new PutUserDocumentRequest(
                version,
                contractId,
                approvers.ToList(),
                data,
                labels,
                additionalBinaryDataProperties: null);
        }

        /// <summary> User proposal approver. </summary>
        /// <param name="approverId"> Approver ID. </param>
        /// <param name="approverIdType"> Approver ID type. </param>
        /// <returns> A new <see cref="Client.UserProposalApprover"/> instance for mocking. </returns>
        public static UserProposalApprover UserProposalApprover(string approverId = default, string approverIdType = default)
        {
            return new UserProposalApprover(approverId, approverIdType, additionalBinaryDataProperties: null);
        }

        /// <summary> Get user document response. </summary>
        /// <param name="id"> Document ID. </param>
        /// <param name="contractId"> Contract ID. </param>
        /// <param name="version"> Document version. </param>
        /// <param name="approvers"> Approvers. </param>
        /// <param name="data"> Document data. </param>
        /// <param name="labels"> Labels. </param>
        /// <param name="state"> Document state. </param>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <param name="proposerId"> Proposer ID. </param>
        /// <param name="finalVotes"> Final votes. </param>
        /// <returns> A new <see cref="Client.GetUserDocumentResponse"/> instance for mocking. </returns>
        public static GetUserDocumentResponse GetUserDocumentResponse(string id = default, string contractId = default, string version = default, IEnumerable<UserProposalApprover> approvers = default, BinaryData data = default, IDictionary<string, string> labels = default, string state = default, string proposalId = default, string proposerId = default, IEnumerable<UserVote> finalVotes = default)
        {
            approvers ??= new ChangeTrackingList<UserProposalApprover>();
            labels ??= new ChangeTrackingDictionary<string, string>();
            finalVotes ??= new ChangeTrackingList<UserVote>();

            return new GetUserDocumentResponse(
                id,
                contractId,
                version,
                approvers.ToList(),
                data,
                labels,
                state,
                proposalId,
                proposerId,
                finalVotes.ToList(),
                additionalBinaryDataProperties: null);
        }

        /// <summary> User vote. </summary>
        /// <param name="approverId"> Approver ID. </param>
        /// <param name="ballot"> Ballot value. </param>
        /// <returns> A new <see cref="Client.UserVote"/> instance for mocking. </returns>
        public static UserVote UserVote(string approverId = default, string ballot = default)
        {
            return new UserVote(approverId, ballot, additionalBinaryDataProperties: null);
        }

        /// <summary> Get accepted user document request. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <returns> A new <see cref="Client.GetAcceptedUserDocumentRequest"/> instance for mocking. </returns>
        public static GetAcceptedUserDocumentRequest GetAcceptedUserDocumentRequest(SnpEvidence attestation = default, Encrypt encrypt = default)
        {
            return new GetAcceptedUserDocumentRequest(attestation, encrypt, additionalBinaryDataProperties: null);
        }

        /// <summary> Get accepted user document response. </summary>
        /// <param name="value"> Encrypted GetUserDocumentResponse content. </param>
        /// <returns> A new <see cref="Client.GetAcceptedUserDocumentResponse"/> instance for mocking. </returns>
        public static GetAcceptedUserDocumentResponse GetAcceptedUserDocumentResponse(string value = default)
        {
            return new GetAcceptedUserDocumentResponse(value, additionalBinaryDataProperties: null);
        }

        /// <summary> List user identities response. </summary>
        /// <param name="value"> Array of user identities. </param>
        /// <returns> A new <see cref="Client.ListUserIdentitiesResponse"/> instance for mocking. </returns>
        public static ListUserIdentitiesResponse ListUserIdentitiesResponse(IEnumerable<GetUserIdentityResponse> value = default)
        {
            value ??= new ChangeTrackingList<GetUserIdentityResponse>();

            return new ListUserIdentitiesResponse(value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Get user identity response. </summary>
        /// <param name="id"> User ID. </param>
        /// <param name="accountType"> Account type. </param>
        /// <param name="invitationId"> Invitation ID. </param>
        /// <param name="data"> User data. </param>
        /// <returns> A new <see cref="Client.GetUserIdentityResponse"/> instance for mocking. </returns>
        public static GetUserIdentityResponse GetUserIdentityResponse(string id = default, string accountType = default, string invitationId = default, BinaryData data = default)
        {
            return new GetUserIdentityResponse(id, accountType, invitationId, data, additionalBinaryDataProperties: null);
        }

        /// <summary> Get user identity response. </summary>
        /// <param name="active"> User status. </param>
        /// <returns> A new <see cref="Client.CheckUserIdentityResponse"/> instance for mocking. </returns>
        public static CheckUserIdentityResponse CheckUserIdentityResponse(bool active = default)
        {
            return new CheckUserIdentityResponse(active, additionalBinaryDataProperties: null);
        }

        /// <summary> List user invitations response. </summary>
        /// <param name="value"> Array of user invitations. </param>
        /// <returns> A new <see cref="Client.ListUserInvitationsResponse"/> instance for mocking. </returns>
        public static ListUserInvitationsResponse ListUserInvitationsResponse(IEnumerable<GetUserInvitationResponse> value = default)
        {
            value ??= new ChangeTrackingList<GetUserInvitationResponse>();

            return new ListUserInvitationsResponse(value.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Get user invitation response. </summary>
        /// <param name="invitationId"> Invitation ID. </param>
        /// <param name="accountType"> Account type. </param>
        /// <param name="tenantId"> Tenant ID. </param>
        /// <param name="claims"> Claims. </param>
        /// <param name="status"> Invitation status. </param>
        /// <param name="userInfo"> User information. </param>
        /// <returns> A new <see cref="Client.GetUserInvitationResponse"/> instance for mocking. </returns>
        public static GetUserInvitationResponse GetUserInvitationResponse(string invitationId = default, string accountType = default, string tenantId = default, BinaryData claims = default, string status = default, UserInfo userInfo = default)
        {
            return new GetUserInvitationResponse(
                invitationId,
                accountType,
                tenantId,
                claims,
                status,
                userInfo,
                additionalBinaryDataProperties: null);
        }

        /// <summary> User information. </summary>
        /// <param name="userId"> User ID. </param>
        /// <param name="data"> User data. </param>
        /// <returns> A new <see cref="Client.UserInfo"/> instance for mocking. </returns>
        public static UserInfo UserInfo(string userId = default, UserData data = default)
        {
            return new UserInfo(userId, data, additionalBinaryDataProperties: null);
        }

        /// <summary> User data. </summary>
        /// <param name="tenantId"> Tenant ID. </param>
        /// <returns> A new <see cref="Client.UserData"/> instance for mocking. </returns>
        public static UserData UserData(string tenantId = default)
        {
            return new UserData(tenantId, additionalBinaryDataProperties: null);
        }

        /// <summary> Get user proposal response. </summary>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <param name="name"> Proposal name. </param>
        /// <param name="approvers"> Approvers. </param>
        /// <param name="args"> Proposal arguments. </param>
        /// <returns> A new <see cref="Client.GetUserProposalResponse"/> instance for mocking. </returns>
        public static GetUserProposalResponse GetUserProposalResponse(string proposalId = default, string name = default, IEnumerable<UserProposalApprover> approvers = default, BinaryData args = default)
        {
            approvers ??= new ChangeTrackingList<UserProposalApprover>();

            return new GetUserProposalResponse(proposalId, name, approvers.ToList(), args, additionalBinaryDataProperties: null);
        }

        /// <summary> Create user proposal request. </summary>
        /// <param name="name"> Proposal name. </param>
        /// <param name="approvers"> Approvers. </param>
        /// <param name="args"> Proposal arguments. </param>
        /// <returns> A new <see cref="Client.CreateUserProposalRequest"/> instance for mocking. </returns>
        public static CreateUserProposalRequest CreateUserProposalRequest(string name = default, IEnumerable<UserProposalApprover> approvers = default, BinaryData args = default)
        {
            approvers ??= new ChangeTrackingList<UserProposalApprover>();

            return new CreateUserProposalRequest(name, approvers.ToList(), args, additionalBinaryDataProperties: null);
        }

        /// <summary> Create user proposal response. </summary>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <returns> A new <see cref="Client.CreateUserProposalResponse"/> instance for mocking. </returns>
        public static CreateUserProposalResponse CreateUserProposalResponse(string proposalId = default)
        {
            return new CreateUserProposalResponse(proposalId, additionalBinaryDataProperties: null);
        }

        /// <summary> User proposal info item. </summary>
        /// <param name="proposerId"> Proposer ID. </param>
        /// <param name="state"> Proposal state. </param>
        /// <param name="ballots"> Ballots. </param>
        /// <returns> A new <see cref="Client.UserProposalInfoItem"/> instance for mocking. </returns>
        public static UserProposalInfoItem UserProposalInfoItem(string proposerId = default, string state = default, IEnumerable<UserVote> ballots = default)
        {
            ballots ??= new ChangeTrackingList<UserVote>();

            return new UserProposalInfoItem(proposerId, state, ballots.ToList(), additionalBinaryDataProperties: null);
        }

        /// <summary> Submit user proposal ballot request. </summary>
        /// <param name="ballot"> Ballot value. </param>
        /// <returns> A new <see cref="Client.SubmitUserProposalBallotRequest"/> instance for mocking. </returns>
        public static SubmitUserProposalBallotRequest SubmitUserProposalBallotRequest(string ballot = default)
        {
            return new SubmitUserProposalBallotRequest(ballot, additionalBinaryDataProperties: null);
        }
    }
}
