// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary></summary>
    public partial class CleanRoomPolicy
    {
        private static PipelineMessageClassifier _pipelineMessageClassifier200;

        private static PipelineMessageClassifier PipelineMessageClassifier200 => _pipelineMessageClassifier200 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 200 });

        internal PipelineMessage CreateGetCleanRoomPolicyRequest(string contractId, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/cleanroompolicy", false);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "POST", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateGetDelegatePoliciesRequest(string contractId, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/cleanroompolicy/delegates", false);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateGetDelegatePolicyRequest(string contractId, string delegateType, string delegateId, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/cleanroompolicy/delegates/", false);
            uri.AppendPath(delegateType, true);
            uri.AppendPath("/", false);
            uri.AppendPath(delegateId, true);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "POST", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreateSetDelegatePolicyRequest(string contractId, string delegateType, string delegateId, BinaryContent content, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/cleanroompolicy/delegates/", false);
            uri.AppendPath(delegateType, true);
            uri.AppendPath("/", false);
            uri.AppendPath(delegateId, true);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "PUT", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Content-Type", "application/json");
            request.Content = content;
            message.Apply(options);
            return message;
        }
    }
}
