// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Threading;
using System.Threading.Tasks;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> The DeploymentSpec sub-client. </summary>
    public partial class DeploymentSpec
    {
        private readonly Uri _endpoint;

        /// <summary> Initializes a new instance of DeploymentSpec for mocking. </summary>
        protected DeploymentSpec()
        {
        }

        /// <summary> Initializes a new instance of DeploymentSpec. </summary>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        internal DeploymentSpec(ClientPipeline pipeline, Uri endpoint)
        {
            _endpoint = endpoint;
            Pipeline = pipeline;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary>
        /// [Protocol Method] getDeploymentSpec
        ///     endpoints/deployment-spec.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult GetDeploymentSpec(string contractId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            using PipelineMessage message = CreateGetDeploymentSpecRequest(contractId, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] getDeploymentSpec
        ///     endpoints/deployment-spec.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> GetDeploymentSpecAsync(string contractId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            using PipelineMessage message = CreateGetDeploymentSpecRequest(contractId, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// getDeploymentSpec
        ///     endpoints/deployment-spec.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<GetDeploymentSpecResponse> GetDeploymentSpec(string contractId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            ClientResult result = GetDeploymentSpec(contractId, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((GetDeploymentSpecResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// getDeploymentSpec
        ///     endpoints/deployment-spec.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<GetDeploymentSpecResponse>> GetDeploymentSpecAsync(string contractId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            ClientResult result = await GetDeploymentSpecAsync(contractId, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((GetDeploymentSpecResponse)result, result.GetRawResponse());
        }
    }
}
