// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary></summary>
    public partial class DeploymentSpec
    {
        private static PipelineMessageClassifier _pipelineMessageClassifier200;

        private static PipelineMessageClassifier PipelineMessageClassifier200 => _pipelineMessageClassifier200 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 200 });

        internal PipelineMessage CreateGetDeploymentSpecRequest(string contractId, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/deploymentspec", false);
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "POST", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }
    }
}
