// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary></summary>
    public partial class Events
    {
        private static PipelineMessageClassifier _pipelineMessageClassifier200;
        private static PipelineMessageClassifier _pipelineMessageClassifier204;

        private static PipelineMessageClassifier PipelineMessageClassifier200 => _pipelineMessageClassifier200 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 200 });

        private static PipelineMessageClassifier PipelineMessageClassifier204 => _pipelineMessageClassifier204 ??= PipelineMessageClassifier.Create(stackalloc ushort[] { 204 });

        internal PipelineMessage CreateGetEventsRequest(string contractId, string id, string scope, string fromSeqno, string toSeqno, string maxSeqnoPerPage, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/events", false);
            if (id != null)
            {
                uri.AppendQuery("id", id, true);
            }
            if (scope != null)
            {
                uri.AppendQuery("scope", scope, true);
            }
            if (fromSeqno != null)
            {
                uri.AppendQuery("from_seqno", fromSeqno, true);
            }
            if (toSeqno != null)
            {
                uri.AppendQuery("to_seqno", toSeqno, true);
            }
            if (maxSeqnoPerPage != null)
            {
                uri.AppendQuery("max_seqno_per_page", maxSeqnoPerPage, true);
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "GET", PipelineMessageClassifier200);
            PipelineRequest request = message.Request;
            request.Headers.Set("Accept", "application/json");
            message.Apply(options);
            return message;
        }

        internal PipelineMessage CreatePutEventRequest(string contractId, BinaryContent content, string id, string scope, RequestOptions options)
        {
            ClientUriBuilder uri = new ClientUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/contracts/", false);
            uri.AppendPath(contractId, true);
            uri.AppendPath("/events", false);
            if (id != null)
            {
                uri.AppendQuery("id", id, true);
            }
            if (scope != null)
            {
                uri.AppendQuery("scope", scope, true);
            }
            PipelineMessage message = Pipeline.CreateMessage(uri.ToUri(), "PUT", PipelineMessageClassifier204);
            PipelineRequest request = message.Request;
            request.Headers.Set("Content-Type", "application/json");
            request.Content = content;
            message.Apply(options);
            return message;
        }
    }
}
