// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Threading;
using System.Threading.Tasks;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> The UserProposals sub-client. </summary>
    public partial class UserProposals
    {
        private readonly Uri _endpoint;

        /// <summary> Initializes a new instance of UserProposals for mocking. </summary>
        protected UserProposals()
        {
        }

        /// <summary> Initializes a new instance of UserProposals. </summary>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        internal UserProposals(ClientPipeline pipeline, Uri endpoint)
        {
            _endpoint = endpoint;
            Pipeline = pipeline;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary>
        /// [Protocol Method] getUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult GetUserProposal(string proposalId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            using PipelineMessage message = CreateGetUserProposalRequest(proposalId, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] getUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> GetUserProposalAsync(string proposalId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            using PipelineMessage message = CreateGetUserProposalRequest(proposalId, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// getUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<GetUserProposalResponse> GetUserProposal(string proposalId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            ClientResult result = GetUserProposal(proposalId, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((GetUserProposalResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// getUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<GetUserProposalResponse>> GetUserProposalAsync(string proposalId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            ClientResult result = await GetUserProposalAsync(proposalId, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((GetUserProposalResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// [Protocol Method] putUserProposal
        ///     endpoints/user-proposals.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult PutUserProposal(string proposalId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreatePutUserProposalRequest(proposalId, content, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] putUserProposal
        ///     endpoints/user-proposals.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> PutUserProposalAsync(string proposalId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreatePutUserProposalRequest(proposalId, content, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// putUserProposal
        ///     endpoints/user-proposals.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<CreateUserProposalResponse> PutUserProposal(string proposalId, CreateUserProposalRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(request, nameof(request));

            ClientResult result = PutUserProposal(proposalId, request, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((CreateUserProposalResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// putUserProposal
        ///     endpoints/user-proposals.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<CreateUserProposalResponse>> PutUserProposalAsync(string proposalId, CreateUserProposalRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(request, nameof(request));

            ClientResult result = await PutUserProposalAsync(proposalId, request, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((CreateUserProposalResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// [Protocol Method] checkUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult CheckUserProposal(string proposalId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            using PipelineMessage message = CreateCheckUserProposalRequest(proposalId, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] checkUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> CheckUserProposalAsync(string proposalId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            using PipelineMessage message = CreateCheckUserProposalRequest(proposalId, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// checkUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<UserProposalInfoItem> CheckUserProposal(string proposalId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            ClientResult result = CheckUserProposal(proposalId, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((UserProposalInfoItem)result, result.GetRawResponse());
        }

        /// <summary>
        /// checkUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<UserProposalInfoItem>> CheckUserProposalAsync(string proposalId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            ClientResult result = await CheckUserProposalAsync(proposalId, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((UserProposalInfoItem)result, result.GetRawResponse());
        }

        /// <summary>
        /// [Protocol Method] withdrawUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult WithdrawUserProposal(string proposalId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            using PipelineMessage message = CreateWithdrawUserProposalRequest(proposalId, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] withdrawUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> WithdrawUserProposalAsync(string proposalId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            using PipelineMessage message = CreateWithdrawUserProposalRequest(proposalId, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// withdrawUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult WithdrawUserProposal(string proposalId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            return WithdrawUserProposal(proposalId, cancellationToken.ToRequestOptions());
        }

        /// <summary>
        /// withdrawUserProposal
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult> WithdrawUserProposalAsync(string proposalId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));

            return await WithdrawUserProposalAsync(proposalId, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }

        /// <summary>
        /// [Protocol Method] submitUserProposalBallot
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult SubmitUserProposalBallot(string proposalId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreateSubmitUserProposalBallotRequest(proposalId, content, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] submitUserProposalBallot
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> SubmitUserProposalBallotAsync(string proposalId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreateSubmitUserProposalBallotRequest(proposalId, content, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// submitUserProposalBallot
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult SubmitUserProposalBallot(string proposalId, SubmitUserProposalBallotRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(request, nameof(request));

            return SubmitUserProposalBallot(proposalId, request, cancellationToken.ToRequestOptions());
        }

        /// <summary>
        /// submitUserProposalBallot
        ///     endpoints/user-proposals.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="proposalId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="proposalId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="proposalId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult> SubmitUserProposalBallotAsync(string proposalId, SubmitUserProposalBallotRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(proposalId, nameof(proposalId));
            Argument.AssertNotNull(request, nameof(request));

            return await SubmitUserProposalBallotAsync(proposalId, request, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }
    }
}
