// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Threading;
using System.Threading.Tasks;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> The UserDocuments sub-client. </summary>
    public partial class UserDocuments
    {
        private readonly Uri _endpoint;

        /// <summary> Initializes a new instance of UserDocuments for mocking. </summary>
        protected UserDocuments()
        {
        }

        /// <summary> Initializes a new instance of UserDocuments. </summary>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        internal UserDocuments(ClientPipeline pipeline, Uri endpoint)
        {
            _endpoint = endpoint;
            Pipeline = pipeline;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary>
        /// [Protocol Method] listUserDocuments
        ///     endpoints/user-documents.js
        ///     GET
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult GetUserDocuments(string contractId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            using PipelineMessage message = CreateGetUserDocumentsRequest(contractId, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] listUserDocuments
        ///     endpoints/user-documents.js
        ///     GET
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> GetUserDocumentsAsync(string contractId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            using PipelineMessage message = CreateGetUserDocumentsRequest(contractId, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// listUserDocuments
        ///     endpoints/user-documents.js
        ///     GET
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<ListUserDocumentsResponse> GetUserDocuments(string contractId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            ClientResult result = GetUserDocuments(contractId, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((ListUserDocumentsResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// listUserDocuments
        ///     endpoints/user-documents.js
        ///     GET
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<ListUserDocumentsResponse>> GetUserDocumentsAsync(string contractId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));

            ClientResult result = await GetUserDocumentsAsync(contractId, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((ListUserDocumentsResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// [Protocol Method] putUserDocument
        ///     endpoints/user-documents.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult PutUserDocument(string contractId, string documentId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreatePutUserDocumentRequest(contractId, documentId, content, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] putUserDocument
        ///     endpoints/user-documents.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> PutUserDocumentAsync(string contractId, string documentId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreatePutUserDocumentRequest(contractId, documentId, content, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// putUserDocument
        ///     endpoints/user-documents.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult PutUserDocument(string contractId, string documentId, PutUserDocumentRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(request, nameof(request));

            return PutUserDocument(contractId, documentId, request, cancellationToken.ToRequestOptions());
        }

        /// <summary>
        /// putUserDocument
        ///     endpoints/user-documents.js
        ///     PUT
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult> PutUserDocumentAsync(string contractId, string documentId, PutUserDocumentRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(request, nameof(request));

            return await PutUserDocumentAsync(contractId, documentId, request, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
        }

        /// <summary>
        /// [Protocol Method] getUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> or <paramref name="documentId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult GetUserDocument(string contractId, string documentId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));

            using PipelineMessage message = CreateGetUserDocumentRequest(contractId, documentId, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] getUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> or <paramref name="documentId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> GetUserDocumentAsync(string contractId, string documentId, RequestOptions options)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));

            using PipelineMessage message = CreateGetUserDocumentRequest(contractId, documentId, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// getUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> or <paramref name="documentId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<GetUserDocumentResponse> GetUserDocument(string contractId, string documentId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));

            ClientResult result = GetUserDocument(contractId, documentId, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((GetUserDocumentResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// getUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [member_cert, user_cert, jwt]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/> or <paramref name="documentId"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<GetUserDocumentResponse>> GetUserDocumentAsync(string contractId, string documentId, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));

            ClientResult result = await GetUserDocumentAsync(contractId, documentId, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((GetUserDocumentResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// [Protocol Method] getAcceptedUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual ClientResult GetAcceptedUserDocument(string contractId, string documentId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreateGetAcceptedUserDocumentRequest(contractId, documentId, content, options);
            return ClientResult.FromResponse(Pipeline.ProcessMessage(message, options));
        }

        /// <summary>
        /// [Protocol Method] getAcceptedUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// <list type="bullet">
        /// <item>
        /// <description> This <see href="https://aka.ms/azsdk/net/protocol-methods">protocol method</see> allows explicit creation of the request and processing of the response for advanced scenarios. </description>
        /// </item>
        /// </list>
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="content"> The content to send as the body of the request. </param>
        /// <param name="options"> The request options, which can override default behaviors of the client pipeline on a per-call basis. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="content"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        /// <returns> The response returned from the service. </returns>
        public virtual async Task<ClientResult> GetAcceptedUserDocumentAsync(string contractId, string documentId, BinaryContent content, RequestOptions options = null)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(content, nameof(content));

            using PipelineMessage message = CreateGetAcceptedUserDocumentRequest(contractId, documentId, content, options);
            return ClientResult.FromResponse(await Pipeline.ProcessMessageAsync(message, options).ConfigureAwait(false));
        }

        /// <summary>
        /// getAcceptedUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual ClientResult<GetAcceptedUserDocumentResponse> GetAcceptedUserDocument(string contractId, string documentId, GetAcceptedUserDocumentRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(request, nameof(request));

            ClientResult result = GetAcceptedUserDocument(contractId, documentId, request, cancellationToken.ToRequestOptions());
            return ClientResult.FromValue((GetAcceptedUserDocumentResponse)result, result.GetRawResponse());
        }

        /// <summary>
        /// getAcceptedUserDocument
        ///     endpoints/user-documents.js
        ///     POST
        ///     AuthPolicies: [attestation]
        /// </summary>
        /// <param name="contractId"></param>
        /// <param name="documentId"></param>
        /// <param name="request"></param>
        /// <param name="cancellationToken"> The cancellation token that can be used to cancel the operation. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="contractId"/>, <paramref name="documentId"/> or <paramref name="request"/> is null. </exception>
        /// <exception cref="ArgumentException"> <paramref name="contractId"/> or <paramref name="documentId"/> is an empty string, and was expected to be non-empty. </exception>
        /// <exception cref="ClientResultException"> Service returned a non-success status code. </exception>
        public virtual async Task<ClientResult<GetAcceptedUserDocumentResponse>> GetAcceptedUserDocumentAsync(string contractId, string documentId, GetAcceptedUserDocumentRequest request, CancellationToken cancellationToken = default)
        {
            Argument.AssertNotNullOrEmpty(contractId, nameof(contractId));
            Argument.AssertNotNullOrEmpty(documentId, nameof(documentId));
            Argument.AssertNotNull(request, nameof(request));

            ClientResult result = await GetAcceptedUserDocumentAsync(contractId, documentId, request, cancellationToken.ToRequestOptions()).ConfigureAwait(false);
            return ClientResult.FromValue((GetAcceptedUserDocumentResponse)result, result.GetRawResponse());
        }
    }
}
