// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.Ccf.Client._Recovery
{
    /// <summary> A share of a recovery key, granted for a specific recovery member, and encrypted with that member's share-encryption key. This is safe to share in the ledger or amongst untrusted callers, as only the intended member will be able to decrypt and access the secret content. </summary>
    public partial class EncryptedRecoveryShare
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="EncryptedRecoveryShare"/>. </summary>
        /// <param name="memberId"> ID of CCF member who this recovery share belongs to. </param>
        /// <param name="encryptedShare"> Base-64 encoding of a member's encrypted share. </param>
        internal EncryptedRecoveryShare(string memberId, BinaryData encryptedShare)
        {
            MemberId = memberId;
            EncryptedShare = encryptedShare;
        }

        /// <summary> Initializes a new instance of <see cref="EncryptedRecoveryShare"/>. </summary>
        /// <param name="memberId"> ID of CCF member who this recovery share belongs to. </param>
        /// <param name="encryptedShare"> Base-64 encoding of a member's encrypted share. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal EncryptedRecoveryShare(string memberId, BinaryData encryptedShare, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            MemberId = memberId;
            EncryptedShare = encryptedShare;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> ID of CCF member who this recovery share belongs to. </summary>
        public string MemberId { get; }

        /// <summary>
        /// Base-64 encoding of a member's encrypted share.
        /// <para>
        /// To assign a byte[] to this property use <see cref="BinaryData.FromBytes(byte[])"/>.
        /// The byte[] will be serialized to a Base64 encoded string.
        /// </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term> BinaryData.FromBytes(new byte[] { 1, 2, 3 }). </term>
        /// <description> Creates a payload of "AQID". </description>
        /// </item>
        /// </list>
        /// </para>
        /// </summary>
        public BinaryData EncryptedShare { get; }
    }
}
