// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.Ccf.Client._Proposals
{
    /// <summary> Description of why governance execution failed. </summary>
    public partial class FailureInfo
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="FailureInfo"/>. </summary>
        /// <param name="reason"> Error message describing reason for failure. </param>
        internal FailureInfo(string reason)
        {
            Reason = reason;
        }

        /// <summary> Initializes a new instance of <see cref="FailureInfo"/>. </summary>
        /// <param name="reason"> Error message describing reason for failure. </param>
        /// <param name="trace"> Call stack showing where failure occurred, if available. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal FailureInfo(string reason, string trace, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Reason = reason;
            Trace = trace;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Error message describing reason for failure. </summary>
        public string Reason { get; }

        /// <summary> Call stack showing where failure occurred, if available. </summary>
        public string Trace { get; }
    }
}
