// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;
using Microsoft.Ccf.Client;

namespace Microsoft.Ccf.Client._ServiceState
{
    /// <summary> Possible states for a CCF governing member. </summary>
    public readonly partial struct MemberStatus : IEquatable<MemberStatus>
    {
        private readonly string _value;
        /// <summary> Member has been approved to join the service, but have not yet submitted an ACK to indicate their participation. These members should not be considered by constitutions in quorum calculations, and their signed requests will be rejected until they become Active. </summary>
        private const string AcceptedValue = "Accepted";
        /// <summary> Member has submitted a valid ACK and is a full voting participant. </summary>
        private const string ActiveValue = "Active";

        /// <summary> Initializes a new instance of <see cref="MemberStatus"/>. </summary>
        /// <param name="value"> The value. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public MemberStatus(string value)
        {
            Argument.AssertNotNull(value, nameof(value));

            _value = value;
        }

        /// <summary> Member has been approved to join the service, but have not yet submitted an ACK to indicate their participation. These members should not be considered by constitutions in quorum calculations, and their signed requests will be rejected until they become Active. </summary>
        public static MemberStatus Accepted { get; } = new MemberStatus(AcceptedValue);

        /// <summary> Member has submitted a valid ACK and is a full voting participant. </summary>
        public static MemberStatus Active { get; } = new MemberStatus(ActiveValue);

        /// <summary> Determines if two <see cref="MemberStatus"/> values are the same. </summary>
        /// <param name="left"> The left value to compare. </param>
        /// <param name="right"> The right value to compare. </param>
        public static bool operator ==(MemberStatus left, MemberStatus right) => left.Equals(right);

        /// <summary> Determines if two <see cref="MemberStatus"/> values are not the same. </summary>
        /// <param name="left"> The left value to compare. </param>
        /// <param name="right"> The right value to compare. </param>
        public static bool operator !=(MemberStatus left, MemberStatus right) => !left.Equals(right);

        /// <summary> Converts a string to a <see cref="MemberStatus"/>. </summary>
        /// <param name="value"> The value. </param>
        public static implicit operator MemberStatus(string value) => new MemberStatus(value);

        /// <summary> Converts a string to a <see cref="MemberStatus"/>. </summary>
        /// <param name="value"> The value. </param>
        public static implicit operator MemberStatus?(string value) => value == null ? null : new MemberStatus(value);

        /// <inheritdoc/>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is MemberStatus other && Equals(other);

        /// <inheritdoc/>
        public bool Equals(MemberStatus other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc/>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value != null ? StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value) : 0;

        /// <inheritdoc/>
        public override string ToString() => _value;
    }
}
