// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Ccf.Client._ServiceState;

namespace Azure.Core.Foundations
{
    /// <summary> Paged collection of Member items. </summary>
    internal partial class PagedMember
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="PagedMember"/>. </summary>
        /// <param name="value"> The Member items on this page. </param>
        /// <param name="transactionId"> Identifier for transaction this response was read from. The service state may be altered by other write requests. Reads at the same transactionId describe a consistent single point in the service history. </param>
        internal PagedMember(IEnumerable<Member> value, string transactionId)
        {
            Value = value.ToList();
            TransactionId = transactionId;
        }

        /// <summary> Initializes a new instance of <see cref="PagedMember"/>. </summary>
        /// <param name="value"> The Member items on this page. </param>
        /// <param name="nextLink"> The link to the next page of items. </param>
        /// <param name="transactionId"> Identifier for transaction this response was read from. The service state may be altered by other write requests. Reads at the same transactionId describe a consistent single point in the service history. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal PagedMember(IList<Member> value, Uri nextLink, string transactionId, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Value = value;
            NextLink = nextLink;
            TransactionId = transactionId;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> The Member items on this page. </summary>
        public IList<Member> Value { get; }

        /// <summary> The link to the next page of items. </summary>
        public Uri NextLink { get; }

        /// <summary> Identifier for transaction this response was read from. The service state may be altered by other write requests. Reads at the same transactionId describe a consistent single point in the service history. </summary>
        public string TransactionId { get; }
    }
}
