// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.Ccf.Client;

namespace Microsoft.Ccf.Client._Proposals
{
    /// <summary> Description of a proposed change to the service. </summary>
    public partial class Proposal : IJsonModel<Proposal>
    {
        /// <summary> Initializes a new instance of <see cref="Proposal"/> for deserialization. </summary>
        internal Proposal()
        {
        }

        /// <param name="data"> The data to parse. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual Proposal PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<Proposal>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions))
                    {
                        return DeserializeProposal(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(Proposal)} does not support reading '{options.Format}' format.");
            }
        }

        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<Proposal>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, MicrosoftCcfClientContext.Default);
                default:
                    throw new FormatException($"The model {nameof(Proposal)} does not support writing '{options.Format}' format.");
            }
        }

        /// <param name="options"> The client options for reading and writing models. </param>
        BinaryData IPersistableModel<Proposal>.Write(ModelReaderWriterOptions options) => PersistableModelWriteCore(options);

        /// <param name="data"> The data to parse. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        Proposal IPersistableModel<Proposal>.Create(BinaryData data, ModelReaderWriterOptions options) => PersistableModelCreateCore(data, options);

        /// <param name="options"> The client options for reading and writing models. </param>
        string IPersistableModel<Proposal>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        /// <param name="result"> The <see cref="ClientResult"/> to deserialize the <see cref="Proposal"/> from. </param>
        public static explicit operator Proposal(ClientResult result)
        {
            PipelineResponse response = result.GetRawResponse();
            using JsonDocument document = JsonDocument.Parse(response.Content, ModelSerializationExtensions.JsonDocumentOptions);
            return DeserializeProposal(document.RootElement, ModelSerializationExtensions.WireOptions);
        }

        /// <param name="writer"> The JSON writer. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        void IJsonModel<Proposal>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        /// <param name="writer"> The JSON writer. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<Proposal>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(Proposal)} does not support writing '{format}' format.");
            }
            writer.WritePropertyName("proposalId"u8);
            writer.WriteStringValue(ProposalId);
            writer.WritePropertyName("proposerId"u8);
            writer.WriteStringValue(ProposerId);
            writer.WritePropertyName("proposalState"u8);
            writer.WriteStringValue(ProposalState.ToString());
            writer.WritePropertyName("ballotCount"u8);
            writer.WriteNumberValue(BallotCount);
            if (Optional.IsDefined(FinalVotes))
            {
                writer.WritePropertyName("finalVotes"u8);
                writer.WriteObjectValue(FinalVotes, options);
            }
            if (Optional.IsDefined(VoteFailures))
            {
                writer.WritePropertyName("voteFailures"u8);
                writer.WriteObjectValue(VoteFailures, options);
            }
            if (Optional.IsDefined(Failure))
            {
                writer.WritePropertyName("failure"u8);
                writer.WriteObjectValue(Failure, options);
            }
            if (options.Format != "W" && _additionalBinaryDataProperties != null)
            {
                foreach (var item in _additionalBinaryDataProperties)
                {
                    writer.WritePropertyName(item.Key);
#if NET6_0_OR_GREATER
                    writer.WriteRawValue(item.Value);
#else
                    using (JsonDocument document = JsonDocument.Parse(item.Value))
                    {
                        JsonSerializer.Serialize(writer, document.RootElement);
                    }
#endif
                }
            }
        }

        /// <param name="reader"> The JSON reader. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        Proposal IJsonModel<Proposal>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => JsonModelCreateCore(ref reader, options);

        /// <param name="reader"> The JSON reader. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual Proposal JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<Proposal>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(Proposal)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return DeserializeProposal(document.RootElement, options);
        }

        /// <param name="element"> The JSON element to deserialize. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        internal static Proposal DeserializeProposal(JsonElement element, ModelReaderWriterOptions options)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            string proposalId = default;
            string proposerId = default;
            ProposalState proposalState = default;
            long ballotCount = default;
            MemberVotes finalVotes = default;
            VoteFailures voteFailures = default;
            FailureInfo failure = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("proposalId"u8))
                {
                    proposalId = prop.Value.GetString();
                    continue;
                }
                if (prop.NameEquals("proposerId"u8))
                {
                    proposerId = prop.Value.GetString();
                    continue;
                }
                if (prop.NameEquals("proposalState"u8))
                {
                    proposalState = new ProposalState(prop.Value.GetString());
                    continue;
                }
                if (prop.NameEquals("ballotCount"u8))
                {
                    ballotCount = prop.Value.GetInt64();
                    continue;
                }
                if (prop.NameEquals("finalVotes"u8))
                {
                    if (prop.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    finalVotes = MemberVotes.DeserializeMemberVotes(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("voteFailures"u8))
                {
                    if (prop.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    voteFailures = VoteFailures.DeserializeVoteFailures(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("failure"u8))
                {
                    if (prop.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    failure = FailureInfo.DeserializeFailureInfo(prop.Value, options);
                    continue;
                }
                if (options.Format != "W")
                {
                    additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
                }
            }
            return new Proposal(
                proposalId,
                proposerId,
                proposalState,
                ballotCount,
                finalVotes,
                voteFailures,
                failure,
                additionalBinaryDataProperties);
        }
    }
}
