// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;
using Microsoft.Ccf.Client;

namespace Microsoft.Ccf.Client._Proposals
{
    /// <summary> Possible states for a proposal. </summary>
    public readonly partial struct ProposalState : IEquatable<ProposalState>
    {
        private readonly string _value;
        /// <summary> Proposal is active and can be voted on. </summary>
        private const string OpenValue = "Open";
        /// <summary> Proposal passed a successful vote and was enacted. </summary>
        private const string AcceptedValue = "Accepted";
        /// <summary> Proposal was removed by proposing member. Will never be enacted. </summary>
        private const string WithdrawnValue = "Withdrawn";
        /// <summary> Proposal was rejected by vote. Will never be enacted. </summary>
        private const string RejectedValue = "Rejected";
        /// <summary> Proposal passed a successful vote, but its proposed actions failed. Will never be enacted. </summary>
        private const string FailedValue = "Failed";
        /// <summary> Proposal was open when its semantics were potentially changed (code or constitution were modified), so it was automatically invalidated. </summary>
        private const string DroppedValue = "Dropped";

        /// <summary> Initializes a new instance of <see cref="ProposalState"/>. </summary>
        /// <param name="value"> The value. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public ProposalState(string value)
        {
            Argument.AssertNotNull(value, nameof(value));

            _value = value;
        }

        /// <summary> Proposal is active and can be voted on. </summary>
        public static ProposalState Open { get; } = new ProposalState(OpenValue);

        /// <summary> Proposal passed a successful vote and was enacted. </summary>
        public static ProposalState Accepted { get; } = new ProposalState(AcceptedValue);

        /// <summary> Proposal was removed by proposing member. Will never be enacted. </summary>
        public static ProposalState Withdrawn { get; } = new ProposalState(WithdrawnValue);

        /// <summary> Proposal was rejected by vote. Will never be enacted. </summary>
        public static ProposalState Rejected { get; } = new ProposalState(RejectedValue);

        /// <summary> Proposal passed a successful vote, but its proposed actions failed. Will never be enacted. </summary>
        public static ProposalState Failed { get; } = new ProposalState(FailedValue);

        /// <summary> Proposal was open when its semantics were potentially changed (code or constitution were modified), so it was automatically invalidated. </summary>
        public static ProposalState Dropped { get; } = new ProposalState(DroppedValue);

        /// <summary> Determines if two <see cref="ProposalState"/> values are the same. </summary>
        /// <param name="left"> The left value to compare. </param>
        /// <param name="right"> The right value to compare. </param>
        public static bool operator ==(ProposalState left, ProposalState right) => left.Equals(right);

        /// <summary> Determines if two <see cref="ProposalState"/> values are not the same. </summary>
        /// <param name="left"> The left value to compare. </param>
        /// <param name="right"> The right value to compare. </param>
        public static bool operator !=(ProposalState left, ProposalState right) => !left.Equals(right);

        /// <summary> Converts a string to a <see cref="ProposalState"/>. </summary>
        /// <param name="value"> The value. </param>
        public static implicit operator ProposalState(string value) => new ProposalState(value);

        /// <summary> Converts a string to a <see cref="ProposalState"/>. </summary>
        /// <param name="value"> The value. </param>
        public static implicit operator ProposalState?(string value) => value == null ? null : new ProposalState(value);

        /// <inheritdoc/>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is ProposalState other && Equals(other);

        /// <inheritdoc/>
        public bool Equals(ProposalState other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc/>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value != null ? StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value) : 0;

        /// <inheritdoc/>
        public override string ToString() => _value;
    }
}
