// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Microsoft.Ccf.Client._Proposals
{
    /// <summary> The actions contained in a proposal, describing the proposal's changes. </summary>
    public partial class ProposalActions
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="ProposalActions"/>. </summary>
        /// <param name="actions"> A list of actions to apply. Each action is considered, in order, for both proposal and execution of the proposal. All actions are validated and, if the proposal is accepted, applied atomically. </param>
        internal ProposalActions(IEnumerable<Action> actions)
        {
            Actions = actions.ToList();
        }

        /// <summary> Initializes a new instance of <see cref="ProposalActions"/>. </summary>
        /// <param name="actions"> A list of actions to apply. Each action is considered, in order, for both proposal and execution of the proposal. All actions are validated and, if the proposal is accepted, applied atomically. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal ProposalActions(IList<Action> actions, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Actions = actions;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> A list of actions to apply. Each action is considered, in order, for both proposal and execution of the proposal. All actions are validated and, if the proposal is accepted, applied atomically. </summary>
        public IList<Action> Actions { get; }
    }
}
