// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.Ccf.Client._Proposals
{
    /// <summary> Description of a proposed change to the service. </summary>
    public partial class Proposal
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="Proposal"/>. </summary>
        /// <param name="proposalId"> Unique ID assigned to this proposal at its submission, by the service. </param>
        /// <param name="proposerId"> ID of CCF member who signed and created this proposal. </param>
        /// <param name="proposalState"> Current state of this proposal. </param>
        /// <param name="ballotCount"> Count of how many ballots have been submitted for this proposal. </param>
        internal Proposal(string proposalId, string proposerId, ProposalState proposalState, long ballotCount)
        {
            ProposalId = proposalId;
            ProposerId = proposerId;
            ProposalState = proposalState;
            BallotCount = ballotCount;
        }

        /// <summary> Initializes a new instance of <see cref="Proposal"/>. </summary>
        /// <param name="proposalId"> Unique ID assigned to this proposal at its submission, by the service. </param>
        /// <param name="proposerId"> ID of CCF member who signed and created this proposal. </param>
        /// <param name="proposalState"> Current state of this proposal. </param>
        /// <param name="ballotCount"> Count of how many ballots have been submitted for this proposal. </param>
        /// <param name="finalVotes"> If a proposal is not open, then this contains the result of each ballot when the proposal transitioned from open. </param>
        /// <param name="voteFailures"> This will be populated with a description of any ballots which failed to execute. </param>
        /// <param name="failure"> If proposalState is Failure, then this will describe why the proposal failed. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal Proposal(string proposalId, string proposerId, ProposalState proposalState, long ballotCount, MemberVotes finalVotes, VoteFailures voteFailures, FailureInfo failure, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            ProposalId = proposalId;
            ProposerId = proposerId;
            ProposalState = proposalState;
            BallotCount = ballotCount;
            FinalVotes = finalVotes;
            VoteFailures = voteFailures;
            Failure = failure;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Unique ID assigned to this proposal at its submission, by the service. </summary>
        public string ProposalId { get; }

        /// <summary> ID of CCF member who signed and created this proposal. </summary>
        public string ProposerId { get; }

        /// <summary> Current state of this proposal. </summary>
        public ProposalState ProposalState { get; }

        /// <summary> Count of how many ballots have been submitted for this proposal. </summary>
        public long BallotCount { get; }

        /// <summary> If a proposal is not open, then this contains the result of each ballot when the proposal transitioned from open. </summary>
        public MemberVotes FinalVotes { get; }

        /// <summary> This will be populated with a description of any ballots which failed to execute. </summary>
        public VoteFailures VoteFailures { get; }

        /// <summary> If proposalState is Failure, then this will describe why the proposal failed. </summary>
        public FailureInfo Failure { get; }
    }
}
