// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Microsoft.Ccf.Client._ServiceState
{
    /// <summary> Join policy fields specific to nodes running on AMD SEV-SNP hardware. </summary>
    public partial class SnpJoinPolicy
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="SnpJoinPolicy"/>. </summary>
        /// <param name="measurements"> Code measurements of acceptable enclaves. </param>
        /// <param name="hostData"> Collection of acceptable host data values. </param>
        /// <param name="uvmEndorsements"> Collection of acceptable UVM endorsements. Keyed by endorser's did. </param>
        internal SnpJoinPolicy(IEnumerable<BinaryData> measurements, IDictionary<string, BinaryData> hostData, IDictionary<string, UvmEndorsementFeeds> uvmEndorsements)
        {
            Measurements = measurements.ToList();
            HostData = hostData;
            UvmEndorsements = uvmEndorsements;
        }

        /// <summary> Initializes a new instance of <see cref="SnpJoinPolicy"/>. </summary>
        /// <param name="measurements"> Code measurements of acceptable enclaves. </param>
        /// <param name="hostData"> Collection of acceptable host data values. </param>
        /// <param name="uvmEndorsements"> Collection of acceptable UVM endorsements. Keyed by endorser's did. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal SnpJoinPolicy(IList<BinaryData> measurements, IDictionary<string, BinaryData> hostData, IDictionary<string, UvmEndorsementFeeds> uvmEndorsements, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Measurements = measurements;
            HostData = hostData;
            UvmEndorsements = uvmEndorsements;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary>
        /// Code measurements of acceptable enclaves.
        /// <para>
        /// To assign a byte[] to the element of this property use <see cref="BinaryData.FromBytes(byte[])"/>.
        /// The byte[] will be serialized to a Base64 encoded string.
        /// </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term> BinaryData.FromBytes(new byte[] { 1, 2, 3 }). </term>
        /// <description> Creates a payload of "AQID". </description>
        /// </item>
        /// </list>
        /// </para>
        /// </summary>
        public IList<BinaryData> Measurements { get; }

        /// <summary>
        /// Collection of acceptable host data values.
        /// <para>
        /// To assign a byte[] to the value of this property use <see cref="BinaryData.FromBytes(byte[])"/>.
        /// The byte[] will be serialized to a Base64 encoded string.
        /// </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term> BinaryData.FromBytes(new byte[] { 1, 2, 3 }). </term>
        /// <description> Creates a payload of "AQID". </description>
        /// </item>
        /// </list>
        /// </para>
        /// </summary>
        public IDictionary<string, BinaryData> HostData { get; }

        /// <summary> Collection of acceptable UVM endorsements. Keyed by endorser's did. </summary>
        public IDictionary<string, UvmEndorsementFeeds> UvmEndorsements { get; }
    }
}
