// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Microsoft.Ccf.Client._ServiceState
{
    internal partial class UnknownQuoteInfo : QuoteInfo
    {
        /// <summary> Initializes a new instance of <see cref="UnknownQuoteInfo"/>. </summary>
        /// <param name="format"> Discriminator property for QuoteInfo. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal UnknownQuoteInfo(string format, IDictionary<string, BinaryData> additionalBinaryDataProperties) : base(format ?? "unknown", additionalBinaryDataProperties)
        {
        }
    }
}
