images:
  frontendUrl: <INFERENCING_FRONTEND_IMAGE_URL>
  ccrproxyUrl: <CCR_PROXY_IMAGE_URL>
  ccrskrUrl: <CCR_SKR_IMAGE_URL>
  ccrgovernanceUrl: <CCR_GOVERNANCE_IMAGE_URL>
  otelCollectorUrl: <OTEL_COLLECTOR_IMAGE_URL>

ccrgovernance:
  ccrgovEndpoint: <CCR_GOV_ENDPOINT>
  ccrgovApiPathPrefix: <CCR_GOV_API_PATH_PREFIX>
  ccrgovServiceCert: <CCR_GOV_SERVICE_CERT>
  ccrgovServiceCertDiscovery:
    endpoint: <CCR_GOV_SERVICE_CERT_DISCOVERY_ENDPOINT>
    snpHostData: <CCR_GOV_SERVICE_CERT_DISCOVERY_SNP_HOST_DATA>
    skipDigestCheck: <CCR_GOV_SERVICE_CERT_DISCOVERY_SKIP_DIGEST_CHECK>
    constitutionDigest: <CCR_GOV_SERVICE_CERT_DISCOVERY_CONSTITUTION_DIGEST>
    jsappBundleDigest: <CCR_GOV_SERVICE_CERT_DISCOVERY_JSAPP_BUNDLE_DIGEST>

telemetry:
  telemetryCollectionEnabled: <TELEMETRY_COLLECTION_ENABLED>
  prometheusEndpoint: <PROMETHEUS_ENDPOINT>
  lokiEndpoint: <LOKI_ENDPOINT>
  tempoEndpoint: <TEMPO_ENDPOINT>

settings:
  cleanroom:
    registryUrl: <CLEANROOM_REGISTRY_URL>
    versionsDocument: <CLEANROOM_VERSIONS_DOCUMENT>
    cvmMeasurementsDocument: <CLEANROOM_CVM_MEASUREMENTS_DOCUMENT>
    sidecarsPolicyDocumentRegistryUrl: <CLEANROOM_SIDECARS_POLICY_DOCUMENT_REGISTRY_URL>
    inferencingDigestsDocument: <INFERENCING_DIGESTS_DOCUMENT>
  applications:
    inferencing:
      namespace: <INFERENCING_NAMESPACE>
      debugMode: <DEBUG_MODE>
      allowAll: <ALLOW_ALL>
      enableTestEndpoints: <ENABLE_TEST_ENDPOINTS>
      kserve:
        predictor:
          cores: 1
          memory: "512m"
          serviceAccount: "kserve-operator-kserve"
