"""
Code generator for events.
Generates type-safe factory methods for each event defined in JSON files.

Usage:
    python generator.py --type operational --input operational_events.json --output operational_events_codegen.py
    python generator.py --type audit --input audit_events.json --output audit_records_codegen.py
    python generator.py --type statistics --input statistics_events.json --output statistics_events_codegen.py
"""

import argparse
import json
import re
from pathlib import Path
from typing import Dict, Set


def load_json(file_path: Path) -> Dict:
    """Load event definitions from JSON file."""
    with open(file_path, "r") as f:
        return json.load(f)


def snake_to_pascal(snake_str: str) -> str:
    """Convert SNAKE_CASE to PascalCase."""
    return "".join(word.capitalize() for word in snake_str.lower().split("_"))


def extract_parameters(message: str) -> Set[str]:
    """Extract parameter names from message template."""
    # Find all {parameter_name} patterns
    return set(re.findall(r"\{(\w+)\}", message))


def generate_method(
    event_name: str, event_def: Dict, event_class: str, is_audit: bool, enum_type: str
) -> str:
    """Generate a factory method for a single event."""
    method_name = snake_to_pascal(event_name)
    parameters = extract_parameters(event_def["message"])

    # Sort parameters for consistent ordering
    sorted_params = sorted(parameters)

    # Generate parameter list
    if sorted_params:
        param_list = ", ".join(f"{param}: str" for param in sorted_params)
        param_dict = ", ".join(f'"{param}": {param}' for param in sorted_params)
    else:
        param_list = ""
        param_dict = ""

    # Special handling for AuditEvent/AuditRecord (includes source parameter)
    if is_audit:
        if param_list:
            param_list = f"source: str, {param_list}"
        else:
            param_list = "source: str"
        source_line = "source=source,"
    else:
        source_line = ""

    # Build parameters dictionary
    if param_dict:
        params_dict_str = f"{{{param_dict}}}"
    else:
        params_dict_str = "{}"

    # Build the return statement with conditional source line
    if source_line:
        return_block = f"""        return {event_class}(
            id={event_def["id"]},
            name={enum_type}.{event_name}.value,
            message="{event_def["message"]}",
            {source_line}
            parameters={params_dict_str},
        )"""
    else:
        return_block = f"""        return {event_class}(
            id={event_def["id"]},
            name={enum_type}.{event_name}.value,
            message="{event_def["message"]}",
            parameters={params_dict_str},
        )"""

    method_code = f'''    @staticmethod
    def {method_name}({param_list}) -> {event_class}:
        """
        Create {event_name} event.
        
        Message: {event_def["message"]}
        """
{return_block}
'''
    return method_code


def generate_operational_events(events_path: Path, output_path: Path):
    """Generate operational events file."""
    events = load_json(events_path)

    header = '''"""
Auto-generated operational events file.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generator.py
"""

import enum
from .operational_event import OperationalEvent


'''

    # Generate enum
    enum_members = []
    for event_name in sorted(events.keys()):
        enum_members.append(f'    {event_name} = "{event_name}"')

    enum_code = f'''class OperationalEventType(enum.Enum):
    """Enum for operational event types."""
{chr(10).join(enum_members)}


'''

    methods = []
    for event_name, event_def in sorted(events.items()):
        methods.append(
            generate_method(
                event_name, event_def, "OperationalEvent", False, "OperationalEventType"
            )
        )

    class_code = f'''class OperationalEventFactory:
    """Factory class for OperationalEvent instances."""

{"".join(methods)}
'''

    full_code = header + enum_code + class_code

    with open(output_path, "w") as f:
        f.write(full_code)

    print(f"Generated {output_path} with {len(events)} operational events")


def generate_audit_records(events_path: Path, output_path: Path):
    """Generate audit records factory file."""
    events = load_json(events_path)

    header = '''"""
Auto-generated audit records file.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generator.py
"""

import enum
from .audit_record import AuditRecord


'''

    # Generate enum
    enum_members = []
    for event_name in sorted(events.keys()):
        enum_members.append(f'    {event_name} = "{event_name}"')

    enum_code = f'''class AuditRecordType(enum.Enum):
    """Enum for audit record types."""
{chr(10).join(enum_members)}


'''

    methods = []
    for event_name, event_def in sorted(events.items()):
        methods.append(
            generate_method(
                event_name, event_def, "AuditRecord", True, "AuditRecordType"
            )
        )

    class_code = f'''class AuditRecordFactory:
    """Factory class for AuditRecord instances."""

{"".join(methods)}
'''

    full_code = header + enum_code + class_code

    with open(output_path, "w") as f:
        f.write(full_code)

    print(f"Generated {output_path} with {len(events)} audit records")


def generate_statistics_event_method(
    event_name: str, event_def: Dict
) -> tuple[str, str]:
    """Generate a factory method and data class for a statistics event."""
    method_name = snake_to_pascal(event_name)
    data_class_name = f"{method_name}Data"

    properties = event_def.get("properties", {})

    # Map JSON types to Python types
    type_mapping = {
        "integer": "int",
        "float": "float",
        "string": "str",
        "boolean": "bool",
    }

    # Generate data class fields
    data_class_fields = []
    for prop_name, prop_type in sorted(properties.items()):
        python_type = type_mapping.get(prop_type, "str")
        default_value = (
            "0"
            if python_type == "int"
            else (
                "0.0"
                if python_type == "float"
                else '""'
                if python_type == "str"
                else "False"
            )
        )
        data_class_fields.append(
            f"    {prop_name}: {python_type} = Field(\n"
            f'        description="{prop_name.replace("_", " ").title()}", default={default_value}\n'
            f"    )"
        )

    data_class = f"""class {data_class_name}(BaseModel):
{chr(10).join(data_class_fields) if data_class_fields else "    pass"}


"""

    # Generate parameter list for method
    param_list = ", ".join(
        f"{prop}: {type_mapping.get(prop_type, 'str')}"
        for prop, prop_type in sorted(properties.items())
    )

    # Generate data instantiation
    data_params = ", ".join(f"{prop}={prop}" for prop in sorted(properties.keys()))

    method_code = f'''    @staticmethod
    def {method_name}({param_list}) -> StatisticsEvent:
        """
        Create {event_name} statistics event.
        """
        import base64
        import json

        data = {data_class_name}({data_params}).dict()
        data_json = json.dumps(data)
        data_base64 = base64.b64encode(data_json.encode("utf-8")).decode("utf-8")

        return StatisticsEvent(
            type=StatisticsEventType.{event_name}.value,
            data_base64=data_base64,
        )

'''
    return data_class, method_code


def generate_statistics_events(events_path: Path, output_path: Path):
    """Generate statistics events file."""
    events = load_json(events_path)

    header = '''"""
Auto-generated statistics events file.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generator.py
"""

import enum
from pydantic import BaseModel, Field
from .statistics_event import StatisticsEvent


'''

    # Generate enum
    enum_members = []
    for event_name in sorted(events.keys()):
        enum_members.append(f'    {event_name} = "{event_name}"')

    enum_code = f'''class StatisticsEventType(enum.Enum):
    """Enum for statistics event types."""
{chr(10).join(enum_members)}


'''

    data_classes = []
    methods = []
    for event_name, event_def in sorted(events.items()):
        data_class, method = generate_statistics_event_method(event_name, event_def)
        data_classes.append(data_class)
        methods.append(method)

    class_code = f'''class StatisticsEventFactory:
    """Factory class for StatisticsEvent instances."""

{"".join(methods)}
'''

    full_code = header + enum_code + "".join(data_classes) + class_code

    with open(output_path, "w") as f:
        f.write(full_code)

    print(f"Generated {output_path} with {len(events)} statistics events")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate event factory from JSON definitions"
    )
    parser.add_argument(
        "--type",
        choices=["operational_events", "audit_records", "statistics_events"],
        required=True,
        help="Type of events to generate (operational_events, audit_records, or statistics_events)",
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to input JSON file with event definitions",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output path for generated code file",
    )

    args = parser.parse_args()

    if args.type == "operational_events":
        generate_operational_events(args.input, args.output)
    elif args.type == "audit_records":
        generate_audit_records(args.input, args.output)
    elif args.type == "statistics_events":
        generate_statistics_events(args.input, args.output)
