images:
  frontendUrl: <SPARK_FRONTEND_IMAGE_URL>
  ccrproxyUrl: <CCR_PROXY_IMAGE_URL>
  ccrskrUrl: <CCR_SKR_IMAGE_URL>
  otelCollectorUrl: <OTEL_COLLECTOR_IMAGE_URL>

telemetry:
  telemetryCollectionEnabled: <TELEMETRY_COLLECTION_ENABLED>
  prometheusEndpoint: <PROMETHEUS_ENDPOINT>
  lokiEndpoint: <LOKI_ENDPOINT>
  tempoEndpoint: <TEMPO_ENDPOINT>

optimizer:
  enabled: true
  endpoint: "http://workspace-llama-3point1-8b-instruct.kaito-workspace.svc"
  timeout: 90

settings:
  cleanroom:
    registryUrl: <CLEANROOM_REGISTRY_URL>
    versionsDocument: <CLEANROOM_VERSIONS_DOCUMENT>
    sidecarsPolicyDocumentRegistryUrl: <CLEANROOM_SIDECARS_POLICY_DOCUMENT_REGISTRY_URL>
  applications:
    analytics:
      namespace: <ANALYTICS_NAMESPACE>
      timeToLiveSeconds: 259200
      image: <CLEANROOM_ANALYTICS_IMAGE_URL>
      policyFile: <CLEANROOM_ANALYTICS_IMAGE_POLICY_DOCUMENT_URL>
      debugMode: <DEBUG_MODE>
      allowAll: <ALLOW_ALL>
      applicationFile: "local:///app/src/analytics_workload/run_query.py"
      sql:
        driver:
          cores: 2
          memory: "8g"
          serviceAccount: "spark-operator-spark"
        executor:
          cores: 4
          memory: "16g"
          deleteOnTermination: "true"
          instances:
            min: 1
            max: 10