name: Build cleanroom az cli
description: Build cleanroom az cli

inputs:
  tag:
    required: true
    description: The tag

runs:
  using: composite
  steps:
    - name: Build cleanroom az cli extension
      shell: pwsh
      run: ./build/build-azcliext-cleanroom.ps1 -tag ${{ inputs.tag }} -skipInstall

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: cleanroom-cli.whl
        path: ./build/bin/azext_cleanroom/dist
        overwrite: true