// <auto-generated/>

// This file was originally auto-generated by a TypeSpec tool, but has been modified
// by hand for now. We will go back to auto-generation, so not fixing SA issues.

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Azure.Cleanroom.Sdk;

/// <summary>
/// Capabilities supported by a governance client instance.
/// Use flags to check which operations are available at runtime.
/// </summary>
[Flags]
public enum CleanroomClientCapabilities
{
    None = 0,
    AppOperations = 1,
    MemberOperations = 2,
    AttestationOperations = 4,
    All = 7
}