// <auto-generated/>

#nullable enable

// This file was originally auto-generated by a TypeSpec tool, but has been modified
// by hand for now. We will go back to auto-generation, so not fixing SA issues.

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.Json.Nodes;
using Azure.Cleanroom.Governance.Client;
using Microsoft.Ccf.Client._Acks;
using Microsoft.Ccf.Client._Proposals;
using Microsoft.Ccf.Client._Recovery;
using Microsoft.Ccf.Client._ServiceState;

using Proposal = Microsoft.Ccf.Client._Proposals.Proposal;

namespace Azure.Cleanroom.Sdk;

/// <summary>
/// Caller-facing governance client interface. Attestation, encryption,
/// and COSE signing are handled internally by the implementation.
/// </summary>
/// <remarks>
/// This interface hides wire-level attestation types (<c>SnpEvidence</c>,
/// <c>Encrypt</c>, <c>Sign</c>) from callers. For endpoints that require
/// attestation, the SDK auto-injects credentials configured at build time
/// and auto-decrypts encrypted responses.
///
/// Use <see cref="CleanroomClientBuilder"/> to create an
/// implementation. Register as <c>ICleanroomClient</c> in DI.
///
/// For advanced scenarios requiring explicit attestation control, cast to
/// the generated GovernanceClient which exposes the wire-level request
/// types.
/// </remarks>
public interface ICleanroomClient : IDisposable
{
    /// <summary>
    /// Gets the member identifier (SHA-256 hash of member certificate).
    /// Null when no member credentials were provided.
    /// </summary>
    string? MemberId { get; }

    // ================================================================
    // Certificate Authority
    // ================================================================

    /// <summary>
    /// Generates a CA signing key. Auth: member_cert.
    /// </summary>
    Task GenerateCaSigningKeyAsync(string contractId);

    /// <summary>
    /// Generates an endorsed certificate. Auth: attestation.
    /// The SDK auto-injects attestation evidence, signs the data,
    /// and encrypts the request.
    /// </summary>
    /// <param name="contractId">The contract identifier.</param>
    /// <param name="certData">The certificate data to endorse.</param>
    Task<GenerateEndorsedCertResponse> GenerateEndorsedCertAsync(
        string contractId,
        string certData);

    /// <summary>
    /// Gets CA info. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<CAInfo> GetCaInfoAsync(string contractId);

    // ================================================================
    // Clean Room Policy
    // ================================================================

    /// <summary>
    /// Gets the clean room policy. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetCleanRoomPolicyResponse> GetCleanRoomPolicyAsync(
        string contractId);

    /// <summary>
    /// Lists delegate policies. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListDelegatePoliciesResponse> ListDelegatePoliciesAsync(
        string contractId);

    /// <summary>
    /// Gets a delegate policy. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetDelegatePolicyResponse> GetDelegatePolicyAsync(
        string contractId,
        string delegateType,
        string delegateId);

    /// <summary>
    /// Sets a delegate policy. Auth: attestation.
    /// The SDK auto-injects attestation evidence and signs the data.
    /// </summary>
    /// <param name="contractId">The contract identifier.</param>
    /// <param name="delegateType">The delegate type.</param>
    /// <param name="delegateId">The delegate identifier.</param>
    /// <param name="policyData">The policy data to set.</param>
    Task SetDelegatePolicyAsync(
        string contractId,
        string delegateType,
        string delegateId,
        string policyData);

    // ================================================================
    // Contract Runtime Options
    // ================================================================

    /// <summary>
    /// Checks a contract runtime option.
    /// Auth: member_cert, user_cert, jwt, attestation.
    /// </summary>
    Task<GetRuntimeOptionResponse> CheckContractRuntimeOptionAsync(
        string contractId,
        string option);

    /// <summary>
    /// Enables a contract runtime option. Auth: member_cert.
    /// </summary>
    Task EnableContractRuntimeOptionAsync(
        string contractId,
        string option);

    /// <summary>
    /// Disables a contract runtime option. Auth: member_cert.
    /// </summary>
    Task DisableContractRuntimeOptionAsync(
        string contractId,
        string option);

    // ================================================================
    // Contracts
    // ================================================================

    /// <summary>
    /// Lists all contracts. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListContractsResponse> ListContractsAsync();

    /// <summary>
    /// Creates or updates a contract. Auth: member_cert.
    /// </summary>
    Task PutContractAsync(
        string contractId,
        PutContractRequest request);

    /// <summary>
    /// Gets a contract by ID. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetContractResponse> GetContractAsync(string contractId);

    // ================================================================
    // Deployment
    // ================================================================

    /// <summary>
    /// Gets deployment info. Auth: attestation (infrastructure-level).
    /// </summary>
    Task<GetDeploymentInfoResponse> GetDeploymentInfoAsync(
        string contractId);

    /// <summary>
    /// Gets the deployment spec. Auth: attestation (infrastructure-level).
    /// </summary>
    Task<GetDeploymentSpecResponse> GetDeploymentSpecAsync(
        string contractId);

    // ================================================================
    // Events
    // ================================================================

    /// <summary>
    /// Lists audit events. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetEventsResponse> ListEventsAsync(string contractId);

    /// <summary>
    /// Puts an audit event. Auth: jwt or attestation (dual-auth).
    /// In attestation mode, the SDK auto-signs the data and injects
    /// attestation evidence. In JWT mode, sends a simpler request.
    /// </summary>
    /// <param name="contractId">The contract identifier.</param>
    /// <param name="timestamp">Event timestamp (Unix milliseconds).</param>
    /// <param name="data">Event data as a JSON string.</param>
    /// <param name="id">Optional event ID (defaults to contractId on the server).</param>
    /// <param name="scope">Optional event scope.</param>
    Task PutEventAsync(
        string contractId,
        string timestamp,
        string data,
        string? id = null,
        string? scope = null);

    // ================================================================
    // Member Documents
    // ================================================================

    /// <summary>
    /// Lists member documents. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListMemberDocumentResponse[]> ListMemberDocumentsAsync(
        string contractId);

    /// <summary>
    /// Creates or updates a member document. Auth: member_cert.
    /// </summary>
    Task PutMemberDocumentAsync(
        string contractId,
        string documentId,
        PutMemberDocumentRequest request);

    /// <summary>
    /// Gets a member document. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetMemberDocumentResponse> GetMemberDocumentAsync(
        string contractId,
        string documentId);

    /// <summary>
    /// Gets an accepted member document. Auth: attestation.
    /// The SDK auto-injects attestation evidence and auto-decrypts
    /// the response.
    /// </summary>
    Task<GetAcceptedMemberDocumentResponse>
        GetAcceptedMemberDocumentAsync(
            string contractId,
            string documentId);

    // ================================================================
    // OIDC
    // ================================================================

    /// <summary>
    /// Gets the OIDC discovery configuration.
    /// Auth: attestation (infrastructure-level).
    /// </summary>
    Task<DiscoveryResponse> GetConfigurationAsync();

    /// <summary>
    /// Gets the JWKS. Auth: attestation (infrastructure-level).
    /// </summary>
    Task<JwksResponse> GetJwksAsync();

    /// <summary>
    /// Generates an OIDC issuer signing key. Auth: member_cert.
    /// </summary>
    Task GenerateIssuerSigningKeyAsync();

    /// <summary>
    /// Sets the OIDC issuer URL. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task SetIssuerUrlAsync(SetIssuerUrlRequest request);

    /// <summary>
    /// Gets OIDC issuer info. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<OidcIssuerInfo> GetOidcIssuerInfoAsync();

    // ================================================================
    // Proposals
    // ================================================================

    /// <summary>
    /// Gets a proposal (historical). Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetProposalResponse> GetProposalHistoricalAsync(
        string proposalId);

    // ================================================================
    // Runtime Options
    // ================================================================

    /// <summary>
    /// Checks a runtime option. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetRuntimeOptionResponse> CheckRuntimeOptionAsync(
        string option);

    // ================================================================
    // Secrets
    // ================================================================

    /// <summary>
    /// Lists secrets. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListSecretsResponse> ListSecretsAsync(string contractId);

    /// <summary>
    /// Creates or updates a secret.
    /// Auth: member_cert, user_cert, jwt, attestation.
    /// </summary>
    Task<PutSecretResponse> PutSecretAsync(
        string contractId,
        string secretName,
        object request);

    /// <summary>
    /// Gets a secret. Auth: attestation.
    /// The SDK auto-injects attestation evidence and auto-decrypts
    /// the encrypted response.
    /// </summary>
    Task<GetSecretResponse> GetSecretAsync(
        string contractId,
        string secretName);

    // ================================================================
    // Signing
    // ================================================================

    /// <summary>
    /// Signs a payload. Auth: attestation (infrastructure-level).
    /// </summary>
    Task SignPayloadAsync(string contractId);

    /// <summary>
    /// Generates a signing key. Auth: member_cert.
    /// </summary>
    Task GenerateSigningKeyAsync();

    /// <summary>
    /// Gets signing info. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task GetSigningInfoAsync();

    // ================================================================
    // Token
    // ================================================================

    /// <summary>
    /// Gets an OIDC token. Auth: attestation.
    /// The SDK auto-injects attestation evidence and auto-decrypts
    /// the encrypted response.
    /// </summary>
    Task<GetTokenResponse> GetTokenAsync(string contractId);

    // ================================================================
    // User Document Runtime Options
    // ================================================================

    /// <summary>
    /// Checks a user document runtime option.
    /// Auth: member_cert, user_cert, jwt, attestation.
    /// </summary>
    Task<GetRuntimeOptionResponse> CheckUserDocumentRuntimeOptionAsync(
        string contractId,
        string documentId,
        string option);

    /// <summary>
    /// Enables a user document runtime option.
    /// Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task EnableUserDocumentRuntimeOptionAsync(
        string contractId,
        string documentId,
        string option);

    /// <summary>
    /// Disables a user document runtime option.
    /// Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task DisableUserDocumentRuntimeOptionAsync(
        string contractId,
        string documentId,
        string option);

    // ================================================================
    // User Documents
    // ================================================================

    /// <summary>
    /// Lists user documents. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListUserDocumentsResponse> ListUserDocumentsAsync(
        string contractId);

    /// <summary>
    /// Creates or updates a user document.
    /// Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task PutUserDocumentAsync(
        string contractId,
        string documentId,
        PutUserDocumentRequest request);

    /// <summary>
    /// Gets a user document. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetUserDocumentResponse> GetUserDocumentAsync(
        string contractId,
        string documentId);

    /// <summary>
    /// Gets an accepted user document. Auth: attestation.
    /// The SDK auto-injects attestation evidence and auto-decrypts
    /// the response.
    /// </summary>
    Task<GetAcceptedUserDocumentResponse>
        GetAcceptedUserDocumentAsync(
            string contractId,
            string documentId);

    // ================================================================
    // User Identities
    // ================================================================

    /// <summary>
    /// Lists user identities. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListUserIdentitiesResponse> ListUserIdentitiesAsync();

    /// <summary>
    /// Checks the current user's identity. Auth: jwt.
    /// </summary>
    Task<CheckUserIdentityResponse> CheckUserIdentityAsync();

    /// <summary>
    /// Gets a user identity. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetUserIdentityResponse> GetUserIdentityAsync(
        string identityId);

    // ================================================================
    // User Invitations
    // ================================================================

    /// <summary>
    /// Lists invitations. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<ListUserInvitationsResponse> ListInvitationsAsync();

    /// <summary>
    /// Gets an invitation. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetUserInvitationResponse> GetInvitationAsync(
        string invitationId);

    /// <summary>
    /// Accepts an invitation. Auth: jwt.
    /// </summary>
    Task AcceptInvitationAsync(string invitationId);

    // ================================================================
    // User Proposals
    // ================================================================

    /// <summary>
    /// Gets a user proposal. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<GetUserProposalResponse> GetUserProposalAsync(
        string proposalId);

    /// <summary>
    /// Creates or updates a user proposal.
    /// Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<CreateUserProposalResponse> PutUserProposalAsync(
        string proposalId,
        CreateUserProposalRequest request);

    /// <summary>
    /// Checks a user proposal. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task<UserProposalInfoItem> CheckUserProposalAsync(
        string proposalId);

    /// <summary>
    /// Withdraws a user proposal. Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task WithdrawUserProposalAsync(string proposalId);

    /// <summary>
    /// Submits a ballot for a user proposal.
    /// Auth: member_cert, user_cert, jwt.
    /// </summary>
    Task SubmitUserProposalBallotAsync(
        string proposalId,
        SubmitUserProposalBallotRequest request);

    // ================================================================
    // Capabilities (SDK-defined)
    // ================================================================

    /// <summary>
    /// Gets the capabilities available on this client instance.
    /// </summary>
    Task<CleanroomClientCapabilities> GetCapabilitiesAsync();

    // ================================================================
    // gov/* operations (member governance)
    // Writes use explicit COSE Sign1 envelopes; reads use plain
    // mTLS GET. Return types are generated CCF client models from
    // the Microsoft.Ccf.* namespaces.
    // ================================================================

    // --- State digest ---

    /// <summary>
    /// Updates the state digest for this member.
    /// Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<StateDigest> UpdateStateDigestAsync();

    /// <summary>
    /// Acknowledges the state digest for this member.
    /// Auth: member_cert + COSE Sign1.
    /// </summary>
    Task AcknowledgeStateDigestAsync();

    // --- Proposals (write) ---

    /// <summary>
    /// Creates a governance proposal. Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<Proposal> CreateProposalAsync(JsonObject proposal);

    /// <summary>
    /// Withdraws a governance proposal.
    /// Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<Proposal> WithdrawProposalAsync(string proposalId);

    // --- Voting ---

    /// <summary>
    /// Votes to accept a proposal. Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<Proposal> VoteAcceptProposalAsync(string proposalId);

    /// <summary>
    /// Votes to reject a proposal. Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<Proposal> VoteRejectProposalAsync(string proposalId);

    /// <summary>
    /// Votes on a proposal with a custom ballot.
    /// Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<Proposal> VoteOnProposalAsync(
        string proposalId,
        JsonObject ballot);

    // --- Proposals (read) ---

    /// <summary>
    /// Gets the details of a governance proposal.
    /// Auth: member_cert (mTLS).
    /// </summary>
    Task<Proposal> GetGovProposalAsync(
        string proposalId);

    /// <summary>
    /// Gets the actions for a governance proposal.
    /// Auth: member_cert (mTLS).
    /// </summary>
    Task<ProposalActions> GetProposalActionsAsync(
        string proposalId);

    /// <summary>
    /// Gets the votes for a governance proposal.
    /// Auth: member_cert (mTLS).
    /// </summary>
    Task<VotesListResponse> GetProposalVotesAsync(
        string proposalId);

    /// <summary>
    /// Lists all governance proposals. Auth: member_cert (mTLS).
    /// </summary>
    Task<IReadOnlyList<Proposal>> ListGovProposalsAsync();

    // --- Network / Members (read) ---

    /// <summary>
    /// Lists all CCF consortium members. Auth: member_cert (mTLS).
    /// </summary>
    Task<IReadOnlyList<Member>> ListMembersAsync();

    /// <summary>
    /// Shows CCF network information. Auth: member_cert (mTLS).
    /// </summary>
    Task<ServiceInfo> ShowNetworkAsync();

    // --- Recovery ---

    /// <summary>
    /// Gets the encrypted recovery share for this member.
    /// Auth: member_cert (mTLS).
    /// </summary>
    Task<EncryptedRecoveryShare> GetMemberEncryptedShareAsync();

    /// <summary>
    /// Submits a decrypted recovery share to initiate or continue
    /// CCF network recovery. Auth: member_cert + COSE Sign1.
    /// </summary>
    Task<RecoveryResponse> SubmitRecoveryShareAsync(
        string decryptedShare);
}
