// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using Microsoft.Ccf.Client._Acks;
using Microsoft.Ccf.Client._Proposals;
using Microsoft.Ccf.Client._Recovery;
using Microsoft.Ccf.Client._ServiceState;
using Microsoft.Ccf.Client._Transactions;

namespace Microsoft.Ccf.Client
{
    /// <summary> The CcfClient. </summary>
    public partial class CcfClient
    {
        private readonly Uri _endpoint;
        private readonly string _apiVersion;
        private Acks _cachedAcks;
        private Proposals _cachedProposals;
        private Recovery _cachedRecovery;
        private ServiceState _cachedServiceState;
        private Transactions _cachedTransactions;

        /// <summary> Initializes a new instance of CcfClient for mocking. </summary>
        protected CcfClient()
        {
        }

        /// <summary> Initializes a new instance of CcfClient. </summary>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="endpoint"/> is null. </exception>
        public CcfClient(Uri endpoint) : this(endpoint, new CcfClientOptions())
        {
        }

        /// <summary> Initializes a new instance of CcfClient. </summary>
        /// <param name="authenticationPolicy"> The authentication policy to use for pipeline creation. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <param name="options"> The options for configuring the client. </param>
        internal CcfClient(AuthenticationPolicy authenticationPolicy, Uri endpoint, CcfClientOptions options)
        {
            Argument.AssertNotNull(endpoint, nameof(endpoint));

            options ??= new CcfClientOptions();

            _endpoint = endpoint;
            if (authenticationPolicy != null)
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(CcfClient).Assembly), authenticationPolicy }, Array.Empty<PipelinePolicy>());
            }
            else
            {
                Pipeline = ClientPipeline.Create(options, Array.Empty<PipelinePolicy>(), new PipelinePolicy[] { new UserAgentPolicy(typeof(CcfClient).Assembly) }, Array.Empty<PipelinePolicy>());
            }
            _apiVersion = options.Version;
        }

        /// <summary> Initializes a new instance of CcfClient. </summary>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <param name="options"> The options for configuring the client. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="endpoint"/> is null. </exception>
        public CcfClient(Uri endpoint, CcfClientOptions options) : this(null, endpoint, options)
        {
        }

        /// <summary> Initializes a new instance of CcfClient from a <see cref="CcfClientSettings"/>. </summary>
        /// <param name="settings"> The settings for CcfClient. </param>
        [Experimental("SCME0002")]
        public CcfClient(CcfClientSettings settings) : this(AuthenticationPolicy.Create(settings), settings?.Endpoint, settings?.Options)
        {
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary> Initializes a new instance of Acks. </summary>
        public virtual Acks GetAcksClient()
        {
            return Volatile.Read(ref _cachedAcks) ?? Interlocked.CompareExchange(ref _cachedAcks, new Acks(Pipeline, _endpoint, _apiVersion), null) ?? _cachedAcks;
        }

        /// <summary> Initializes a new instance of Proposals. </summary>
        public virtual Proposals GetProposalsClient()
        {
            return Volatile.Read(ref _cachedProposals) ?? Interlocked.CompareExchange(ref _cachedProposals, new Proposals(Pipeline, _endpoint, _apiVersion), null) ?? _cachedProposals;
        }

        /// <summary> Initializes a new instance of Recovery. </summary>
        public virtual Recovery GetRecoveryClient()
        {
            return Volatile.Read(ref _cachedRecovery) ?? Interlocked.CompareExchange(ref _cachedRecovery, new Recovery(Pipeline, _endpoint, _apiVersion), null) ?? _cachedRecovery;
        }

        /// <summary> Initializes a new instance of ServiceState. </summary>
        public virtual ServiceState GetServiceStateClient()
        {
            return Volatile.Read(ref _cachedServiceState) ?? Interlocked.CompareExchange(ref _cachedServiceState, new ServiceState(Pipeline, _endpoint, _apiVersion), null) ?? _cachedServiceState;
        }

        /// <summary> Initializes a new instance of Transactions. </summary>
        public virtual Transactions GetTransactionsClient()
        {
            return Volatile.Read(ref _cachedTransactions) ?? Interlocked.CompareExchange(ref _cachedTransactions, new Transactions(Pipeline, _endpoint, _apiVersion), null) ?? _cachedTransactions;
        }
    }
}
