// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Threading;

namespace Microsoft.Ccf.Client._Recovery
{
    /// <summary> The Recovery sub-client. </summary>
    public partial class Recovery
    {
        private readonly Uri _endpoint;
        private readonly string _apiVersion;
        private RecoveryEncryptedShares _cachedRecoveryEncryptedShares;
        private RecoveryShares _cachedRecoveryShares;

        /// <summary> Initializes a new instance of Recovery for mocking. </summary>
        protected Recovery()
        {
        }

        /// <summary> Initializes a new instance of Recovery. </summary>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <param name="apiVersion"></param>
        internal Recovery(ClientPipeline pipeline, Uri endpoint, string apiVersion)
        {
            _endpoint = endpoint;
            Pipeline = pipeline;
            _apiVersion = apiVersion;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary> Initializes a new instance of RecoveryEncryptedShares. </summary>
        public virtual RecoveryEncryptedShares GetRecoveryEncryptedSharesClient()
        {
            return Volatile.Read(ref _cachedRecoveryEncryptedShares) ?? Interlocked.CompareExchange(ref _cachedRecoveryEncryptedShares, new RecoveryEncryptedShares(Pipeline, _endpoint, _apiVersion), null) ?? _cachedRecoveryEncryptedShares;
        }

        /// <summary> Initializes a new instance of RecoveryShares. </summary>
        public virtual RecoveryShares GetRecoverySharesClient()
        {
            return Volatile.Read(ref _cachedRecoveryShares) ?? Interlocked.CompareExchange(ref _cachedRecoveryShares, new RecoveryShares(Pipeline, _endpoint, _apiVersion), null) ?? _cachedRecoveryShares;
        }
    }
}
