// <auto-generated/>

#nullable disable

using System;
using System.ClientModel.Primitives;
using System.Threading;

namespace Microsoft.Ccf.Client._ServiceState
{
    /// <summary> The ServiceState sub-client. </summary>
    public partial class ServiceState
    {
        private readonly Uri _endpoint;
        private readonly string _apiVersion;
        private ServiceStateServiceState _cachedServiceStateServiceState;

        /// <summary> Initializes a new instance of ServiceState for mocking. </summary>
        protected ServiceState()
        {
        }

        /// <summary> Initializes a new instance of ServiceState. </summary>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> Service endpoint. </param>
        /// <param name="apiVersion"></param>
        internal ServiceState(ClientPipeline pipeline, Uri endpoint, string apiVersion)
        {
            _endpoint = endpoint;
            Pipeline = pipeline;
            _apiVersion = apiVersion;
        }

        /// <summary> The HTTP pipeline for sending and receiving REST requests and responses. </summary>
        public ClientPipeline Pipeline { get; }

        /// <summary> Initializes a new instance of ServiceStateServiceState. </summary>
        public virtual ServiceStateServiceState GetServiceStateServiceStateClient()
        {
            return Volatile.Read(ref _cachedServiceStateServiceState) ?? Interlocked.CompareExchange(ref _cachedServiceStateServiceState, new ServiceStateServiceState(Pipeline, _endpoint, _apiVersion), null) ?? _cachedServiceStateServiceState;
        }
    }
}
