// Generated by Microsoft TypeSpec

import * as http from "node:http";

import * as serverRaw from "./operations/server-raw.js";

import { parseHeaderValueParameters } from "../helpers/header.js";

import {
  CertificateAuthority,
  CleanRoomPolicy,
  ContractRuntimeOptions,
  Contracts,
  DeploymentInfo,
  DeploymentSpec,
  Events,
  MemberDocuments,
  Oidc,
  Proposals,
  RuntimeOptions,
  Secrets,
  Signing,
  Token,
  UserDocumentRuntimeOptions,
  UserDocuments,
  UserIdentities,
  UserInvitations,
  UserProposals,
} from "../models/all/azure/cleanroom/governance.js";

import {
  RouterOptions,
  createPolicyChain,
  createPolicyChainForRoute,
  HttpContext,
} from "../helpers/router.js";

export interface GovernanceRouter {
  /**
   * Dispatches the request to the appropriate service based on the request path.
   *
   * This member function may be used directly as a handler for a Node HTTP server.
   *
   * @param request - The incoming HTTP request.
   * @param response - The outgoing HTTP response.
   */
  dispatch(request: http.IncomingMessage, response: http.ServerResponse): void;
}

export function createGovernanceRouter(
  certificateAuthority: CertificateAuthority,
  cleanRoomPolicy: CleanRoomPolicy,
  contractRuntimeOptions: ContractRuntimeOptions,
  contracts: Contracts,
  deploymentInfo: DeploymentInfo,
  deploymentSpec: DeploymentSpec,
  events: Events,
  memberDocuments: MemberDocuments,
  oidc: Oidc,
  proposals: Proposals,
  runtimeOptions: RuntimeOptions,
  secrets: Secrets,
  signing: Signing,
  token: Token,
  userDocumentRuntimeOptions: UserDocumentRuntimeOptions,
  userDocuments: UserDocuments,
  userIdentities: UserIdentities,
  userInvitations: UserInvitations,
  userProposals: UserProposals,
  options: RouterOptions<{
    certificateAuthority: CertificateAuthority<HttpContext>;
    cleanRoomPolicy: CleanRoomPolicy<HttpContext>;
    contractRuntimeOptions: ContractRuntimeOptions<HttpContext>;
    contracts: Contracts<HttpContext>;
    deploymentInfo: DeploymentInfo<HttpContext>;
    deploymentSpec: DeploymentSpec<HttpContext>;
    events: Events<HttpContext>;
    memberDocuments: MemberDocuments<HttpContext>;
    oidc: Oidc<HttpContext>;
    proposals: Proposals<HttpContext>;
    runtimeOptions: RuntimeOptions<HttpContext>;
    secrets: Secrets<HttpContext>;
    signing: Signing<HttpContext>;
    token: Token<HttpContext>;
    userDocumentRuntimeOptions: UserDocumentRuntimeOptions<HttpContext>;
    userDocuments: UserDocuments<HttpContext>;
    userIdentities: UserIdentities<HttpContext>;
    userInvitations: UserInvitations<HttpContext>;
    userProposals: UserProposals<HttpContext>;
  }> = {},
): GovernanceRouter {
  const __onRequestNotFound_242 =
    options.onRequestNotFound ??
    ((ctx) => {
      ctx.response.statusCode = 404;
      ctx.response.setHeader("Content-Type", "text/plain");
      ctx.response.end("Not Found");
    });

  const __onInvalidRequest_243 =
    options.onInvalidRequest ??
    ((ctx, route, error) => {
      ctx.response.statusCode = 400;
      ctx.response.setHeader("Content-Type", "application/json");
      ctx.response.end(JSON.stringify({ error }));
    });

  const __onInternalError_244 =
    options.onInternalError ??
    ((ctx, error) => {
      ctx.response.statusCode = 500;
      ctx.response.setHeader("Content-Type", "text/plain");
      ctx.response.end("Internal server error.");
    });

  const __routePolicies_245 = options.routePolicies ?? {};

  const __routeHandlers_246 = {
    certificate_authority_generate_ca_signing_key: createPolicyChainForRoute(
      "certificateAuthorityGenerateCaSigningKeyDispatch",
      __routePolicies_245,
      "certificateAuthority",
      "generateCaSigningKey",
      serverRaw.certificate_authority_generate_ca_signing_key,
    ),
    certificate_authority_generate_endorsed_cert: createPolicyChainForRoute(
      "certificateAuthorityGenerateEndorsedCertDispatch",
      __routePolicies_245,
      "certificateAuthority",
      "generateEndorsedCert",
      serverRaw.certificate_authority_generate_endorsed_cert,
    ),
    certificate_authority_get_ca_info: createPolicyChainForRoute(
      "certificateAuthorityGetCaInfoDispatch",
      __routePolicies_245,
      "certificateAuthority",
      "getCaInfo",
      serverRaw.certificate_authority_get_ca_info,
    ),
    clean_room_policy_get_clean_room_policy: createPolicyChainForRoute(
      "cleanRoomPolicyGetCleanRoomPolicyDispatch",
      __routePolicies_245,
      "cleanRoomPolicy",
      "getCleanRoomPolicy",
      serverRaw.clean_room_policy_get_clean_room_policy,
    ),
    clean_room_policy_list_delegate_policies: createPolicyChainForRoute(
      "cleanRoomPolicyListDelegatePoliciesDispatch",
      __routePolicies_245,
      "cleanRoomPolicy",
      "listDelegatePolicies",
      serverRaw.clean_room_policy_list_delegate_policies,
    ),
    clean_room_policy_get_delegate_policy: createPolicyChainForRoute(
      "cleanRoomPolicyGetDelegatePolicyDispatch",
      __routePolicies_245,
      "cleanRoomPolicy",
      "getDelegatePolicy",
      serverRaw.clean_room_policy_get_delegate_policy,
    ),
    clean_room_policy_set_delegate_policy: createPolicyChainForRoute(
      "cleanRoomPolicySetDelegatePolicyDispatch",
      __routePolicies_245,
      "cleanRoomPolicy",
      "setDelegatePolicy",
      serverRaw.clean_room_policy_set_delegate_policy,
    ),
    contract_runtime_options_check_contract_runtime_option:
      createPolicyChainForRoute(
        "contractRuntimeOptionsCheckContractRuntimeOptionDispatch",
        __routePolicies_245,
        "contractRuntimeOptions",
        "checkContractRuntimeOption",
        serverRaw.contract_runtime_options_check_contract_runtime_option,
      ),
    contract_runtime_options_enable_contract_runtime_option:
      createPolicyChainForRoute(
        "contractRuntimeOptionsEnableContractRuntimeOptionDispatch",
        __routePolicies_245,
        "contractRuntimeOptions",
        "enableContractRuntimeOption",
        serverRaw.contract_runtime_options_enable_contract_runtime_option,
      ),
    contract_runtime_options_disable_contract_runtime_option:
      createPolicyChainForRoute(
        "contractRuntimeOptionsDisableContractRuntimeOptionDispatch",
        __routePolicies_245,
        "contractRuntimeOptions",
        "disableContractRuntimeOption",
        serverRaw.contract_runtime_options_disable_contract_runtime_option,
      ),
    contracts_list_contracts: createPolicyChainForRoute(
      "contractsListContractsDispatch",
      __routePolicies_245,
      "contracts",
      "listContracts",
      serverRaw.contracts_list_contracts,
    ),
    contracts_put_contract: createPolicyChainForRoute(
      "contractsPutContractDispatch",
      __routePolicies_245,
      "contracts",
      "putContract",
      serverRaw.contracts_put_contract,
    ),
    contracts_get_contract: createPolicyChainForRoute(
      "contractsGetContractDispatch",
      __routePolicies_245,
      "contracts",
      "getContract",
      serverRaw.contracts_get_contract,
    ),
    deployment_info_get_deployment_info: createPolicyChainForRoute(
      "deploymentInfoGetDeploymentInfoDispatch",
      __routePolicies_245,
      "deploymentInfo",
      "getDeploymentInfo",
      serverRaw.deployment_info_get_deployment_info,
    ),
    deployment_spec_get_deployment_spec: createPolicyChainForRoute(
      "deploymentSpecGetDeploymentSpecDispatch",
      __routePolicies_245,
      "deploymentSpec",
      "getDeploymentSpec",
      serverRaw.deployment_spec_get_deployment_spec,
    ),
    events_list_events: createPolicyChainForRoute(
      "eventsListEventsDispatch",
      __routePolicies_245,
      "events",
      "listEvents",
      serverRaw.events_list_events,
    ),
    events_put_event: createPolicyChainForRoute(
      "eventsPutEventDispatch",
      __routePolicies_245,
      "events",
      "putEvent",
      serverRaw.events_put_event,
    ),
    member_documents_list_member_documents: createPolicyChainForRoute(
      "memberDocumentsListMemberDocumentsDispatch",
      __routePolicies_245,
      "memberDocuments",
      "listMemberDocuments",
      serverRaw.member_documents_list_member_documents,
    ),
    member_documents_put_member_document: createPolicyChainForRoute(
      "memberDocumentsPutMemberDocumentDispatch",
      __routePolicies_245,
      "memberDocuments",
      "putMemberDocument",
      serverRaw.member_documents_put_member_document,
    ),
    member_documents_get_member_document: createPolicyChainForRoute(
      "memberDocumentsGetMemberDocumentDispatch",
      __routePolicies_245,
      "memberDocuments",
      "getMemberDocument",
      serverRaw.member_documents_get_member_document,
    ),
    member_documents_get_accepted_member_document: createPolicyChainForRoute(
      "memberDocumentsGetAcceptedMemberDocumentDispatch",
      __routePolicies_245,
      "memberDocuments",
      "getAcceptedMemberDocument",
      serverRaw.member_documents_get_accepted_member_document,
    ),
    oidc_get_configuration: createPolicyChainForRoute(
      "oidcGetConfigurationDispatch",
      __routePolicies_245,
      "oidc",
      "getConfiguration",
      serverRaw.oidc_get_configuration,
    ),
    oidc_get_jwks: createPolicyChainForRoute(
      "oidcGetJwksDispatch",
      __routePolicies_245,
      "oidc",
      "getJwks",
      serverRaw.oidc_get_jwks,
    ),
    oidc_generate_issuer_signing_key: createPolicyChainForRoute(
      "oidcGenerateIssuerSigningKeyDispatch",
      __routePolicies_245,
      "oidc",
      "generateIssuerSigningKey",
      serverRaw.oidc_generate_issuer_signing_key,
    ),
    oidc_set_issuer_url: createPolicyChainForRoute(
      "oidcSetIssuerUrlDispatch",
      __routePolicies_245,
      "oidc",
      "setIssuerUrl",
      serverRaw.oidc_set_issuer_url,
    ),
    oidc_get_oidc_issuer_info: createPolicyChainForRoute(
      "oidcGetOidcIssuerInfoDispatch",
      __routePolicies_245,
      "oidc",
      "getOidcIssuerInfo",
      serverRaw.oidc_get_oidc_issuer_info,
    ),
    proposals_get_proposal_historical: createPolicyChainForRoute(
      "proposalsGetProposalHistoricalDispatch",
      __routePolicies_245,
      "proposals",
      "getProposalHistorical",
      serverRaw.proposals_get_proposal_historical,
    ),
    runtime_options_check_runtime_option: createPolicyChainForRoute(
      "runtimeOptionsCheckRuntimeOptionDispatch",
      __routePolicies_245,
      "runtimeOptions",
      "checkRuntimeOption",
      serverRaw.runtime_options_check_runtime_option,
    ),
    secrets_list_secrets: createPolicyChainForRoute(
      "secretsListSecretsDispatch",
      __routePolicies_245,
      "secrets",
      "listSecrets",
      serverRaw.secrets_list_secrets,
    ),
    secrets_put_secret: createPolicyChainForRoute(
      "secretsPutSecretDispatch",
      __routePolicies_245,
      "secrets",
      "putSecret",
      serverRaw.secrets_put_secret,
    ),
    secrets_get_secret: createPolicyChainForRoute(
      "secretsGetSecretDispatch",
      __routePolicies_245,
      "secrets",
      "getSecret",
      serverRaw.secrets_get_secret,
    ),
    signing_sign_payload: createPolicyChainForRoute(
      "signingSignPayloadDispatch",
      __routePolicies_245,
      "signing",
      "signPayload",
      serverRaw.signing_sign_payload,
    ),
    signing_generate_signing_key: createPolicyChainForRoute(
      "signingGenerateSigningKeyDispatch",
      __routePolicies_245,
      "signing",
      "generateSigningKey",
      serverRaw.signing_generate_signing_key,
    ),
    signing_get_signing_info: createPolicyChainForRoute(
      "signingGetSigningInfoDispatch",
      __routePolicies_245,
      "signing",
      "getSigningInfo",
      serverRaw.signing_get_signing_info,
    ),
    token_get_token: createPolicyChainForRoute(
      "tokenGetTokenDispatch",
      __routePolicies_245,
      "token",
      "getToken",
      serverRaw.token_get_token,
    ),
    user_document_runtime_options_check_user_document_runtime_option:
      createPolicyChainForRoute(
        "userDocumentRuntimeOptionsCheckUserDocumentRuntimeOptionDispatch",
        __routePolicies_245,
        "userDocumentRuntimeOptions",
        "checkUserDocumentRuntimeOption",
        serverRaw.user_document_runtime_options_check_user_document_runtime_option,
      ),
    user_document_runtime_options_enable_user_document_runtime_option:
      createPolicyChainForRoute(
        "userDocumentRuntimeOptionsEnableUserDocumentRuntimeOptionDispatch",
        __routePolicies_245,
        "userDocumentRuntimeOptions",
        "enableUserDocumentRuntimeOption",
        serverRaw.user_document_runtime_options_enable_user_document_runtime_option,
      ),
    user_document_runtime_options_disable_user_document_runtime_option:
      createPolicyChainForRoute(
        "userDocumentRuntimeOptionsDisableUserDocumentRuntimeOptionDispatch",
        __routePolicies_245,
        "userDocumentRuntimeOptions",
        "disableUserDocumentRuntimeOption",
        serverRaw.user_document_runtime_options_disable_user_document_runtime_option,
      ),
    user_documents_list_user_documents: createPolicyChainForRoute(
      "userDocumentsListUserDocumentsDispatch",
      __routePolicies_245,
      "userDocuments",
      "listUserDocuments",
      serverRaw.user_documents_list_user_documents,
    ),
    user_documents_put_user_document: createPolicyChainForRoute(
      "userDocumentsPutUserDocumentDispatch",
      __routePolicies_245,
      "userDocuments",
      "putUserDocument",
      serverRaw.user_documents_put_user_document,
    ),
    user_documents_get_user_document: createPolicyChainForRoute(
      "userDocumentsGetUserDocumentDispatch",
      __routePolicies_245,
      "userDocuments",
      "getUserDocument",
      serverRaw.user_documents_get_user_document,
    ),
    user_documents_get_accepted_user_document: createPolicyChainForRoute(
      "userDocumentsGetAcceptedUserDocumentDispatch",
      __routePolicies_245,
      "userDocuments",
      "getAcceptedUserDocument",
      serverRaw.user_documents_get_accepted_user_document,
    ),
    user_identities_list_user_identities: createPolicyChainForRoute(
      "userIdentitiesListUserIdentitiesDispatch",
      __routePolicies_245,
      "userIdentities",
      "listUserIdentities",
      serverRaw.user_identities_list_user_identities,
    ),
    user_identities_check_user_identity: createPolicyChainForRoute(
      "userIdentitiesCheckUserIdentityDispatch",
      __routePolicies_245,
      "userIdentities",
      "checkUserIdentity",
      serverRaw.user_identities_check_user_identity,
    ),
    user_identities_get_user_identity: createPolicyChainForRoute(
      "userIdentitiesGetUserIdentityDispatch",
      __routePolicies_245,
      "userIdentities",
      "getUserIdentity",
      serverRaw.user_identities_get_user_identity,
    ),
    user_invitations_list_invitations: createPolicyChainForRoute(
      "userInvitationsListInvitationsDispatch",
      __routePolicies_245,
      "userInvitations",
      "listInvitations",
      serverRaw.user_invitations_list_invitations,
    ),
    user_invitations_get_invitation: createPolicyChainForRoute(
      "userInvitationsGetInvitationDispatch",
      __routePolicies_245,
      "userInvitations",
      "getInvitation",
      serverRaw.user_invitations_get_invitation,
    ),
    user_invitations_accept_invitation: createPolicyChainForRoute(
      "userInvitationsAcceptInvitationDispatch",
      __routePolicies_245,
      "userInvitations",
      "acceptInvitation",
      serverRaw.user_invitations_accept_invitation,
    ),
    user_proposals_get_user_proposal: createPolicyChainForRoute(
      "userProposalsGetUserProposalDispatch",
      __routePolicies_245,
      "userProposals",
      "getUserProposal",
      serverRaw.user_proposals_get_user_proposal,
    ),
    user_proposals_put_user_proposal: createPolicyChainForRoute(
      "userProposalsPutUserProposalDispatch",
      __routePolicies_245,
      "userProposals",
      "putUserProposal",
      serverRaw.user_proposals_put_user_proposal,
    ),
    user_proposals_check_user_proposal: createPolicyChainForRoute(
      "userProposalsCheckUserProposalDispatch",
      __routePolicies_245,
      "userProposals",
      "checkUserProposal",
      serverRaw.user_proposals_check_user_proposal,
    ),
    user_proposals_withdraw_user_proposal: createPolicyChainForRoute(
      "userProposalsWithdrawUserProposalDispatch",
      __routePolicies_245,
      "userProposals",
      "withdrawUserProposal",
      serverRaw.user_proposals_withdraw_user_proposal,
    ),
    user_proposals_submit_user_proposal_ballot: createPolicyChainForRoute(
      "userProposalsSubmitUserProposalBallotDispatch",
      __routePolicies_245,
      "userProposals",
      "submitUserProposalBallot",
      serverRaw.user_proposals_submit_user_proposal_ballot,
    ),
  } as const;

  const dispatch = createPolicyChain(
    "GovernanceRouterDispatch",
    options.policies ?? [],
    async function (ctx, request, response) {
      const url = new URL(request.url!, `http://${request.headers.host}`);
      let path = url.pathname;

      if (path.length === 0) {
        return ctx.errorHandlers.onRequestNotFound(ctx);
      } else if (path.startsWith("/")) {
        path = path.slice(1);
        if (path.length === 0) {
          return ctx.errorHandlers.onRequestNotFound(ctx);
        } else if (path.startsWith("oidc/")) {
          path = path.slice(5);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else if (path.startsWith(".well-known/openid-configuration")) {
            path = path.slice(32);
            if (path.length === 0) {
              switch (request.method) {
                case "GET":
                  return __routeHandlers_246.oidc_get_configuration(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("keys")) {
            path = path.slice(4);
            if (path.length === 0) {
              switch (request.method) {
                case "GET":
                  return __routeHandlers_246.oidc_get_jwks(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("generateSigningKey")) {
            path = path.slice(18);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_246.oidc_generate_issuer_signing_key(
                    ctx,
                    oidc,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("setIssuerUrl")) {
            path = path.slice(12);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_246.oidc_set_issuer_url(ctx, oidc);
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("issuerInfo")) {
            path = path.slice(10);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_246.oidc_get_oidc_issuer_info(
                    ctx,
                    oidc,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          }
        } else if (path.startsWith("proposals/")) {
          path = path.slice(10);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else {
            let __proposal_id_idx = path.indexOf("/");
            __proposal_id_idx =
              __proposal_id_idx === -1 ? path.length : __proposal_id_idx;
            const proposalId = path.slice(0, __proposal_id_idx);
            path = path.slice(__proposal_id_idx);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else if (path.startsWith("/historical")) {
              path = path.slice(11);
              if (path.length === 0) {
                switch (request.method) {
                  case "GET":
                    return __routeHandlers_246.proposals_get_proposal_historical(
                      ctx,
                      proposals,
                      proposalId,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            }
          }
        } else if (path.startsWith("runtimeoptions/")) {
          path = path.slice(15);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else {
            let __option_idx = path.indexOf("/");
            __option_idx = __option_idx === -1 ? path.length : __option_idx;
            const option = path.slice(0, __option_idx);
            path = path.slice(__option_idx);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else if (path.startsWith("/status")) {
              path = path.slice(7);
              if (path.length === 0) {
                switch (request.method) {
                  case "POST":
                    return __routeHandlers_246.runtime_options_check_runtime_option(
                      ctx,
                      runtimeOptions,
                      option,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else {
                return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            }
          }
        } else if (path.startsWith("signing/")) {
          path = path.slice(8);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else if (path.startsWith("generateSigningKey")) {
            path = path.slice(18);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_246.signing_generate_signing_key(
                    ctx,
                    signing,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("info")) {
            path = path.slice(4);
            if (path.length === 0) {
              switch (request.method) {
                case "POST":
                  return __routeHandlers_246.signing_get_signing_info(
                    ctx,
                    signing,
                  );
                default:
                  return ctx.errorHandlers.onRequestNotFound(ctx);
              }
            } else {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          }
        } else if (path.startsWith("contracts")) {
          path = path.slice(9);
          if (path.length === 0) {
            switch (request.method) {
              case "GET":
                return __routeHandlers_246.contracts_list_contracts(
                  ctx,
                  contracts,
                );
              default:
                return ctx.errorHandlers.onRequestNotFound(ctx);
            }
          } else if (path.startsWith("/")) {
            path = path.slice(1);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else {
              let __contract_id_idx = path.indexOf("/");
              __contract_id_idx =
                __contract_id_idx === -1 ? path.length : __contract_id_idx;
              const contractId = path.slice(0, __contract_id_idx);
              path = path.slice(__contract_id_idx);
              if (path.length === 0) {
                switch (request.method) {
                  case "PUT":
                    return __routeHandlers_246.contracts_put_contract(
                      ctx,
                      contracts,
                      contractId,
                    );
                  case "POST":
                    return __routeHandlers_246.contracts_get_contract(
                      ctx,
                      contracts,
                      contractId,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else if (path.startsWith("/")) {
                path = path.slice(1);
                if (path.length === 0) {
                  return ctx.errorHandlers.onRequestNotFound(ctx);
                } else if (path.startsWith("c")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("a/")) {
                    path = path.slice(2);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("generate")) {
                      path = path.slice(8);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else if (path.startsWith("SigningKey")) {
                        path = path.slice(10);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.certificate_authority_generate_ca_signing_key(
                                ctx,
                                certificateAuthority,
                                contractId,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("EndorsedCert")) {
                        path = path.slice(12);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.certificate_authority_generate_endorsed_cert(
                                ctx,
                                certificateAuthority,
                                contractId,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      }
                    } else if (path.startsWith("status")) {
                      path = path.slice(6);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "POST":
                            return __routeHandlers_246.certificate_authority_get_ca_info(
                              ctx,
                              certificateAuthority,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  } else if (path.startsWith("leanroompolicy")) {
                    path = path.slice(14);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_246.clean_room_policy_get_clean_room_policy(
                            ctx,
                            cleanRoomPolicy,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("/delegates")) {
                      path = path.slice(10);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "GET":
                            return __routeHandlers_246.clean_room_policy_list_delegate_policies(
                              ctx,
                              cleanRoomPolicy,
                              contractId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("/")) {
                        path = path.slice(1);
                        if (path.length === 0) {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        } else {
                          let __delegate_type_idx = path.indexOf("/");
                          __delegate_type_idx =
                            __delegate_type_idx === -1
                              ? path.length
                              : __delegate_type_idx;
                          const delegateType = path.slice(
                            0,
                            __delegate_type_idx,
                          );
                          path = path.slice(__delegate_type_idx);
                          if (path.length === 0) {
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                          } else if (path.startsWith("/")) {
                            path = path.slice(1);
                            if (path.length === 0) {
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                            } else {
                              let __delegate_id_idx = path.indexOf("/");
                              __delegate_id_idx =
                                __delegate_id_idx === -1
                                  ? path.length
                                  : __delegate_id_idx;
                              const delegateId = path.slice(
                                0,
                                __delegate_id_idx,
                              );
                              path = path.slice(__delegate_id_idx);
                              if (path.length === 0) {
                                switch (request.method) {
                                  case "POST":
                                    return __routeHandlers_246.clean_room_policy_get_delegate_policy(
                                      ctx,
                                      cleanRoomPolicy,
                                      contractId,
                                      delegateType,
                                      delegateId,
                                    );
                                  case "PUT":
                                    return __routeHandlers_246.clean_room_policy_set_delegate_policy(
                                      ctx,
                                      cleanRoomPolicy,
                                      contractId,
                                      delegateType,
                                      delegateId,
                                    );
                                  default:
                                    return ctx.errorHandlers.onRequestNotFound(
                                      ctx,
                                    );
                                }
                              } else {
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                } else if (path.startsWith("runtimeoptions/")) {
                  path = path.slice(15);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else {
                    let __option_idx = path.indexOf("/");
                    __option_idx =
                      __option_idx === -1 ? path.length : __option_idx;
                    const option = path.slice(0, __option_idx);
                    path = path.slice(__option_idx);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("/")) {
                      path = path.slice(1);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else if (path.startsWith("status")) {
                        path = path.slice(6);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.contract_runtime_options_check_contract_runtime_option(
                                ctx,
                                contractRuntimeOptions,
                                contractId,
                                option,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("enable")) {
                        path = path.slice(6);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.contract_runtime_options_enable_contract_runtime_option(
                                ctx,
                                contractRuntimeOptions,
                                contractId,
                                option,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("disable")) {
                        path = path.slice(7);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.contract_runtime_options_disable_contract_runtime_option(
                                ctx,
                                contractRuntimeOptions,
                                contractId,
                                option,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      }
                    }
                  }
                } else if (path.startsWith("deployment")) {
                  path = path.slice(10);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("info")) {
                    path = path.slice(4);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_246.deployment_info_get_deployment_info(
                            ctx,
                            deploymentInfo,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("spec")) {
                    path = path.slice(4);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_246.deployment_spec_get_deployment_spec(
                            ctx,
                            deploymentSpec,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  }
                } else if (path.startsWith("events")) {
                  path = path.slice(6);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "GET":
                        return __routeHandlers_246.events_list_events(
                          ctx,
                          events,
                          contractId,
                        );
                      case "PUT":
                        return __routeHandlers_246.events_put_event(
                          ctx,
                          events,
                          contractId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("memberdocuments")) {
                  path = path.slice(15);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "GET":
                        return __routeHandlers_246.member_documents_list_member_documents(
                          ctx,
                          memberDocuments,
                          contractId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("/")) {
                    path = path.slice(1);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("accepted/")) {
                      path = path.slice(9);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else {
                        let __document_id_idx = path.indexOf("/");
                        __document_id_idx =
                          __document_id_idx === -1
                            ? path.length
                            : __document_id_idx;
                        const documentId = path.slice(0, __document_id_idx);
                        path = path.slice(__document_id_idx);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.member_documents_get_accepted_member_document(
                                ctx,
                                memberDocuments,
                                contractId,
                                documentId,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      }
                    } else {
                      let __document_id_idx = path.indexOf("/");
                      __document_id_idx =
                        __document_id_idx === -1
                          ? path.length
                          : __document_id_idx;
                      const documentId = path.slice(0, __document_id_idx);
                      path = path.slice(__document_id_idx);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "PUT":
                            return __routeHandlers_246.member_documents_put_member_document(
                              ctx,
                              memberDocuments,
                              contractId,
                              documentId,
                            );
                          case "POST":
                            return __routeHandlers_246.member_documents_get_member_document(
                              ctx,
                              memberDocuments,
                              contractId,
                              documentId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    }
                  }
                } else if (path.startsWith("s")) {
                  path = path.slice(1);
                  if (path.length === 0) {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  } else if (path.startsWith("ecrets")) {
                    path = path.slice(6);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "GET":
                          return __routeHandlers_246.secrets_list_secrets(
                            ctx,
                            secrets,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else if (path.startsWith("/")) {
                      path = path.slice(1);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else {
                        let __secret_name_idx = path.indexOf("/");
                        __secret_name_idx =
                          __secret_name_idx === -1
                            ? path.length
                            : __secret_name_idx;
                        const secretName = path.slice(0, __secret_name_idx);
                        path = path.slice(__secret_name_idx);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "PUT":
                              return __routeHandlers_246.secrets_put_secret(
                                ctx,
                                secrets,
                                contractId,
                                secretName,
                              );
                            case "POST":
                              return __routeHandlers_246.secrets_get_secret(
                                ctx,
                                secrets,
                                contractId,
                                secretName,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      }
                    }
                  } else if (path.startsWith("igning/sign")) {
                    path = path.slice(11);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_246.signing_sign_payload(
                            ctx,
                            signing,
                            contractId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  }
                } else if (path.startsWith("oauth/token")) {
                  path = path.slice(11);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.token_get_token(
                          ctx,
                          token,
                          contractId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("userdocuments")) {
                  path = path.slice(13);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "GET":
                        return __routeHandlers_246.user_documents_list_user_documents(
                          ctx,
                          userDocuments,
                          contractId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("/")) {
                    path = path.slice(1);
                    if (path.length === 0) {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    } else if (path.startsWith("accepted/")) {
                      path = path.slice(9);
                      if (path.length === 0) {
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                      } else {
                        let __document_id_idx = path.indexOf("/");
                        __document_id_idx =
                          __document_id_idx === -1
                            ? path.length
                            : __document_id_idx;
                        const documentId = path.slice(0, __document_id_idx);
                        path = path.slice(__document_id_idx);
                        if (path.length === 0) {
                          switch (request.method) {
                            case "POST":
                              return __routeHandlers_246.user_documents_get_accepted_user_document(
                                ctx,
                                userDocuments,
                                contractId,
                                documentId,
                              );
                            default:
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                          }
                        } else {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      }
                    } else {
                      let __document_id_idx = path.indexOf("/");
                      __document_id_idx =
                        __document_id_idx === -1
                          ? path.length
                          : __document_id_idx;
                      const documentId = path.slice(0, __document_id_idx);
                      path = path.slice(__document_id_idx);
                      if (path.length === 0) {
                        switch (request.method) {
                          case "PUT":
                            return __routeHandlers_246.user_documents_put_user_document(
                              ctx,
                              userDocuments,
                              contractId,
                              documentId,
                            );
                          case "POST":
                            return __routeHandlers_246.user_documents_get_user_document(
                              ctx,
                              userDocuments,
                              contractId,
                              documentId,
                            );
                          default:
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                        }
                      } else if (path.startsWith("/runtimeoptions/")) {
                        path = path.slice(16);
                        if (path.length === 0) {
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                        } else {
                          let __option_idx = path.indexOf("/");
                          __option_idx =
                            __option_idx === -1 ? path.length : __option_idx;
                          const option = path.slice(0, __option_idx);
                          path = path.slice(__option_idx);
                          if (path.length === 0) {
                            return ctx.errorHandlers.onRequestNotFound(ctx);
                          } else if (path.startsWith("/")) {
                            path = path.slice(1);
                            if (path.length === 0) {
                              return ctx.errorHandlers.onRequestNotFound(ctx);
                            } else if (path.startsWith("status")) {
                              path = path.slice(6);
                              if (path.length === 0) {
                                switch (request.method) {
                                  case "POST":
                                    return __routeHandlers_246.user_document_runtime_options_check_user_document_runtime_option(
                                      ctx,
                                      userDocumentRuntimeOptions,
                                      contractId,
                                      documentId,
                                      option,
                                    );
                                  default:
                                    return ctx.errorHandlers.onRequestNotFound(
                                      ctx,
                                    );
                                }
                              } else {
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                              }
                            } else if (path.startsWith("enable")) {
                              path = path.slice(6);
                              if (path.length === 0) {
                                switch (request.method) {
                                  case "POST":
                                    return __routeHandlers_246.user_document_runtime_options_enable_user_document_runtime_option(
                                      ctx,
                                      userDocumentRuntimeOptions,
                                      contractId,
                                      documentId,
                                      option,
                                    );
                                  default:
                                    return ctx.errorHandlers.onRequestNotFound(
                                      ctx,
                                    );
                                }
                              } else {
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                              }
                            } else if (path.startsWith("disable")) {
                              path = path.slice(7);
                              if (path.length === 0) {
                                switch (request.method) {
                                  case "POST":
                                    return __routeHandlers_246.user_document_runtime_options_disable_user_document_runtime_option(
                                      ctx,
                                      userDocumentRuntimeOptions,
                                      contractId,
                                      documentId,
                                      option,
                                    );
                                  default:
                                    return ctx.errorHandlers.onRequestNotFound(
                                      ctx,
                                    );
                                }
                              } else {
                                return ctx.errorHandlers.onRequestNotFound(ctx);
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else if (path.startsWith("users/")) {
          path = path.slice(6);
          if (path.length === 0) {
            return ctx.errorHandlers.onRequestNotFound(ctx);
          } else if (path.startsWith("i")) {
            path = path.slice(1);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else if (path.startsWith("dentities")) {
              path = path.slice(9);
              if (path.length === 0) {
                switch (request.method) {
                  case "GET":
                    return __routeHandlers_246.user_identities_list_user_identities(
                      ctx,
                      userIdentities,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else if (path.startsWith("/")) {
                path = path.slice(1);
                if (path.length === 0) {
                  return ctx.errorHandlers.onRequestNotFound(ctx);
                } else if (path.startsWith("self/status")) {
                  path = path.slice(11);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.user_identities_check_user_identity(
                          ctx,
                          userIdentities,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else {
                  let __identity_id_idx = path.indexOf("/");
                  __identity_id_idx =
                    __identity_id_idx === -1 ? path.length : __identity_id_idx;
                  const identityId = path.slice(0, __identity_id_idx);
                  path = path.slice(__identity_id_idx);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.user_identities_get_user_identity(
                          ctx,
                          userIdentities,
                          identityId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                }
              }
            } else if (path.startsWith("nvitations")) {
              path = path.slice(10);
              if (path.length === 0) {
                switch (request.method) {
                  case "GET":
                    return __routeHandlers_246.user_invitations_list_invitations(
                      ctx,
                      userInvitations,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else if (path.startsWith("/")) {
                path = path.slice(1);
                if (path.length === 0) {
                  return ctx.errorHandlers.onRequestNotFound(ctx);
                } else {
                  let __invitation_id_idx = path.indexOf("/");
                  __invitation_id_idx =
                    __invitation_id_idx === -1
                      ? path.length
                      : __invitation_id_idx;
                  const invitationId = path.slice(0, __invitation_id_idx);
                  path = path.slice(__invitation_id_idx);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.user_invitations_get_invitation(
                          ctx,
                          userInvitations,
                          invitationId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else if (path.startsWith("/accept")) {
                    path = path.slice(7);
                    if (path.length === 0) {
                      switch (request.method) {
                        case "POST":
                          return __routeHandlers_246.user_invitations_accept_invitation(
                            ctx,
                            userInvitations,
                            invitationId,
                          );
                        default:
                          return ctx.errorHandlers.onRequestNotFound(ctx);
                      }
                    } else {
                      return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  }
                }
              }
            }
          } else if (path.startsWith("proposals/")) {
            path = path.slice(10);
            if (path.length === 0) {
              return ctx.errorHandlers.onRequestNotFound(ctx);
            } else {
              let __proposal_id_idx = path.indexOf("/");
              __proposal_id_idx =
                __proposal_id_idx === -1 ? path.length : __proposal_id_idx;
              const proposalId = path.slice(0, __proposal_id_idx);
              path = path.slice(__proposal_id_idx);
              if (path.length === 0) {
                switch (request.method) {
                  case "POST":
                    return __routeHandlers_246.user_proposals_get_user_proposal(
                      ctx,
                      userProposals,
                      proposalId,
                    );
                  case "PUT":
                    return __routeHandlers_246.user_proposals_put_user_proposal(
                      ctx,
                      userProposals,
                      proposalId,
                    );
                  default:
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                }
              } else if (path.startsWith("/")) {
                path = path.slice(1);
                if (path.length === 0) {
                  return ctx.errorHandlers.onRequestNotFound(ctx);
                } else if (path.startsWith("status")) {
                  path = path.slice(6);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.user_proposals_check_user_proposal(
                          ctx,
                          userProposals,
                          proposalId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("withdraw")) {
                  path = path.slice(8);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.user_proposals_withdraw_user_proposal(
                          ctx,
                          userProposals,
                          proposalId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                } else if (path.startsWith("ballots/submit")) {
                  path = path.slice(14);
                  if (path.length === 0) {
                    switch (request.method) {
                      case "POST":
                        return __routeHandlers_246.user_proposals_submit_user_proposal_ballot(
                          ctx,
                          userProposals,
                          proposalId,
                        );
                      default:
                        return ctx.errorHandlers.onRequestNotFound(ctx);
                    }
                  } else {
                    return ctx.errorHandlers.onRequestNotFound(ctx);
                  }
                }
              }
            }
          }
        }
      }

      return ctx.errorHandlers.onRequestNotFound(ctx);
    },
  );

  const __errorHandlers_247 = {
    onRequestNotFound: __onRequestNotFound_242,
    onInvalidRequest: __onInvalidRequest_243,
    onInternalError: __onInternalError_244,
  };
  return {
    dispatch(request, response) {
      const ctx = { request, response, errorHandlers: __errorHandlers_247 };
      return dispatch(ctx, request, response).catch((e) =>
        __onInternalError_244(ctx, e),
      );
    },
  };
}
