"""
Auto-generated audit records file.
DO NOT EDIT THIS FILE MANUALLY - it is generated by generator.py
"""

import enum

from .audit_record import AuditRecord


class AuditRecordType(enum.Enum):
    """Enum for audit record types."""

    DATASET_LOAD_COMPLETED = "DATASET_LOAD_COMPLETED"
    DATASET_LOAD_FAILED = "DATASET_LOAD_FAILED"
    DATASET_WRITE_COMPLETED = "DATASET_WRITE_COMPLETED"
    DATASET_WRITE_FAILED = "DATASET_WRITE_FAILED"
    QUERY_COMPLETED = "QUERY_COMPLETED"
    QUERY_FAILED = "QUERY_FAILED"


class AuditRecordFactory:
    """Factory class for AuditRecord instances."""

    @staticmethod
    def DatasetLoadCompleted(
        source: str, dataset_name: str, job_id: str, row_count: str
    ) -> AuditRecord:
        """
        Create DATASET_LOAD_COMPLETED event.

        Message: Dataset: {dataset_name} load completed successfully | rows: {row_count} | job id: {job_id}
        """
        return AuditRecord(
            id=3001,
            name=AuditRecordType.DATASET_LOAD_COMPLETED.value,
            message="Dataset: {dataset_name} load completed successfully | rows: {row_count} | job id: {job_id}",
            source=source,
            parameters={
                "dataset_name": dataset_name,
                "job_id": job_id,
                "row_count": row_count,
            },
        )

    @staticmethod
    def DatasetLoadFailed(
        source: str, dataset_name: str, job_id: str, reason: str
    ) -> AuditRecord:
        """
        Create DATASET_LOAD_FAILED event.

        Message: Dataset: {dataset_name} load failed | job id: {job_id}
        """
        return AuditRecord(
            id=3002,
            name=AuditRecordType.DATASET_LOAD_FAILED.value,
            message="Dataset: {dataset_name} load failed | job id: {job_id}",
            source=source,
            parameters={
                "dataset_name": dataset_name,
                "job_id": job_id,
            },
        )

    @staticmethod
    def DatasetWriteCompleted(
        source: str, dataset_name: str, destination: str, job_id: str, row_count: str
    ) -> AuditRecord:
        """
        Create DATASET_WRITE_COMPLETED event.

        Message: Dataset write completed successfully to {destination} | dataset: {dataset_name} | rows: {row_count} | job id: {job_id}
        """
        return AuditRecord(
            id=3005,
            name=AuditRecordType.DATASET_WRITE_COMPLETED.value,
            message="Dataset write completed successfully to {destination} | dataset: {dataset_name} | rows: {row_count} | job id: {job_id}",
            source=source,
            parameters={
                "dataset_name": dataset_name,
                "destination": destination,
                "job_id": job_id,
                "row_count": row_count,
            },
        )

    @staticmethod
    def DatasetWriteFailed(
        source: str, dataset_name: str, destination: str, job_id: str, reason: str
    ) -> AuditRecord:
        """
        Create DATASET_WRITE_FAILED event.

        Message: Dataset write failed to {destination} | dataset: {dataset_name} | job id: {job_id} | reason: {reason}
        """
        return AuditRecord(
            id=3006,
            name=AuditRecordType.DATASET_WRITE_FAILED.value,
            message="Dataset write failed to {destination} | dataset: {dataset_name} | job id: {job_id} | reason: {reason}",
            source=source,
            parameters={
                "dataset_name": dataset_name,
                "destination": destination,
                "job_id": job_id,
                "reason": reason,
            },
        )

    @staticmethod
    def QueryCompleted(source: str, job_id: str) -> AuditRecord:
        """
        Create QUERY_COMPLETED event.

        Message: Query execution completed successfully | job id: {job_id}
        """
        return AuditRecord(
            id=3003,
            name=AuditRecordType.QUERY_COMPLETED.value,
            message="Query execution completed successfully | job id: {job_id}",
            source=source,
            parameters={"job_id": job_id},
        )

    @staticmethod
    def QueryFailed(source: str, job_id: str, reason: str) -> AuditRecord:
        """
        Create QUERY_FAILED event.

        Message: Query failed | job id: {job_id} | reason: {reason}
        """
        return AuditRecord(
            id=3004,
            name=AuditRecordType.QUERY_FAILED.value,
            message="Query failed | job id: {job_id} | reason: {reason}",
            source=source,
            parameters={"job_id": job_id, "reason": reason},
        )
