FROM mcr.microsoft.com/mirror/docker/library/python:3.11-slim

WORKDIR /app
RUN pip install --no-cache-dir flask cryptography
COPY mock_predictor.py .

ENTRYPOINT ["python3", "-u", "mock_predictor.py"]
