// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance
{

    ///<summary>
    /// Digital signature information
    ///</summary>
    public partial class Sign
    {
        ///<summary>
        /// Signature value
        ///</summary>
        public string Signature { get; set; }

        ///<summary>
        /// PEM encoded public key
        ///</summary>
        public string PublicKey { get; set; }


    }
}
