// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// Signing key response
    ///</summary>
    public partial class SigningKeyResponse
    {
        public string Kid { get; set; }

        public string PublicKey { get; set; }


    }
}
