// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;
using System.Text.Json.Nodes;

namespace Cleanroom.Governance.Client
{

    public partial class UserProposalResponse
    {
        public string ProposalId { get; set; }

        public string Name { get; set; }

        public UserProposalApprover[] Approvers { get; set; }

        [JsonPropertyName("args")]
        public JsonNode ArgsName { get; set; }


    }
}
