// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    ///<summary>
    /// User identity data
    ///</summary>
    public partial class UserIdentityData
    {
        public string TenantId { get; set; }

        public string Identifier { get; set; }


    }
}
