// Generated by @typespec/http-server-csharp
// <auto-generated />

using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client
{

    public partial class Vote
    {
        public string MemberId { get; set; }

        [JsonPropertyName("vote")]
        public bool VoteProp { get; set; }


    }
}
