apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
      protocol: TCP
      name: https
    {{- if .Values.ohttp.enabled }}
    - port: {{ .Values.ohttp.port }}
      targetPort: {{ .Values.ohttp.port }}
      protocol: TCP
      name: ohttp
    {{- end }}
  selector:
    {{- include "webserver.selectorLabels" . | nindent 4 }}
