name: Build cleanroom workload infrastructure containers
description: Build cleanroom workload infrastructure containers

inputs:
  tag:
    required: true
    description: The tag

runs:
  using: composite
  steps:
    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: cleanroom-spark-analytics-agent
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.cleanroom-spark-analytics-agent
        context: ${{ github.workspace }}

    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: cleanroom-spark-frontend
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.cleanroom-spark-frontend
        context: ${{ github.workspace }}

    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: cleanroom-spark-analytics-app
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.cleanroom-spark-analytics-app
        context: ${{ github.workspace }}

    - uses: ./.github/actions/build-helm-chart-and-artefacts
      with:
        name: cleanroom-spark-analytics-agent
        tag: ${{ inputs.tag }}
        path: ${{ github.workspace }}/src/workloads/analytics/cleanroom-spark-analytics-agent/helm/chart

    - uses: ./.github/actions/build-helm-chart-and-artefacts
      with:
        name: cleanroom-spark-frontend
        tag: ${{ inputs.tag }}
        path: ${{ github.workspace }}/src/workloads/analytics/cleanroom-spark-frontend/helm/chart

    - uses: ./.github/actions/build-helm-chart-and-artefacts
      with:
        name: frontend-service
        tag: ${{ inputs.tag }}
        path: ${{ github.workspace }}/src/workloads/frontend/helmchart

    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: kserve-inferencing-agent
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.kserve-inferencing-agent
        context: ${{ github.workspace }}

    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: kserve-inferencing-frontend
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.kserve-inferencing-frontend
        context: ${{ github.workspace }}

    - uses: ./.github/actions/build-container-and-artefacts
      with:
        name: ohttp-gateway
        tag: ${{ inputs.tag }}
        dockerfile: build/docker/Dockerfile.ohttp-gateway
        context: ${{ github.workspace }}

    - uses: ./.github/actions/build-helm-chart-and-artefacts
      with:
        name: kserve-inferencing-agent
        tag: ${{ inputs.tag }}
        path: ${{ github.workspace }}/src/workloads/inferencing/kserve-inferencing-agent/helm/chart

    - uses: ./.github/actions/build-helm-chart-and-artefacts
      with:
        name: kserve-inferencing-frontend
        tag: ${{ inputs.tag }}
        path: ${{ github.workspace }}/src/workloads/inferencing/kserve-inferencing-frontend/helm/chart
