apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
  namespace: {{ .Release.Namespace }}
data:
  settings: |
    service:
      name: {{ include "webserver.fullname" . | quote}}
      namespace: {{ .Release.Namespace | quote }}
      url: {{ printf "https://%s.%s.svc" (include "webserver.fullname" .) .Release.Namespace | quote }}
      scheduler:
        nodeSelector:
        {{- toYaml .Values.settings.service.scheduler.nodeSelector | nindent 10}}
        constraints:
        {{- toYaml .Values.settings.service.scheduler.constraints | nindent 10}}
      telemetry:
        telemetryCollectionEnabled: {{ .Values.telemetry.telemetryCollectionEnabled | quote }}
        prometheusEndpoint: {{ .Values.telemetry.prometheusEndpoint | quote }}
        lokiEndpoint: {{ .Values.telemetry.lokiEndpoint | quote }}
        tempoEndpoint: {{ .Values.telemetry.tempoEndpoint | quote }}
      optimizer:
        enabled: {{ .Values.optimizer.enabled | quote }}
        endpoint: {{ .Values.optimizer.endpoint | quote }}
        timeout: {{ .Values.optimizer.timeout | quote }}
    spark:
      computeProvider: {{ .Values.settings.spark.computeProvider | quote }}
    applications:
      analytics:
        namespace: {{ .Values.settings.applications.analytics.namespace | quote }}
        timeToLiveSeconds: {{ .Values.settings.applications.analytics.timeToLiveSeconds | quote }}
        applicationFile: {{ .Values.settings.applications.analytics.applicationFile | quote }}
        allowAll: {{ .Values.settings.applications.analytics.allowAll | quote }}
        debugMode: {{ .Values.settings.applications.analytics.debugMode | quote }}
        sql:
          driver:
            cores: {{ .Values.settings.applications.analytics.sql.driver.cores | quote }}
            memory: {{ .Values.settings.applications.analytics.sql.driver.memory | quote }}
            serviceAccount: {{ .Values.settings.applications.analytics.sql.driver.serviceAccount | quote}}
          executor:
            cores: {{ .Values.settings.applications.analytics.sql.executor.cores | quote }}
            memory: {{ .Values.settings.applications.analytics.sql.executor.memory | quote }}
            instances:
              min: {{ .Values.settings.applications.analytics.sql.executor.instances.min | quote }}
              max: {{ .Values.settings.applications.analytics.sql.executor.instances.max | quote }}
            deleteOnTermination: {{ .Values.settings.applications.analytics.sql.executor.deleteOnTermination | quote }}