// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text;
using System.Text.Json;
using AttestationClient;
using Controllers;
using FrontendSvc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FrontendSvc;

/// <summary>
/// Handles service health and identity endpoints.
/// </summary>
[ApiController]
[AllowAnonymous]
public class ServiceController : ControllerBase
{
    private readonly ILogger<ServiceController> logger;
    private readonly ClientManager clientManager;

    public ServiceController(
        ILogger<ServiceController> logger,
        ClientManager clientManager)
    {
        this.logger = logger;
        this.clientManager = clientManager;
    }

    /// <summary>
    /// Readiness probe endpoint.
    /// </summary>
    /// <returns>200 OK if the service is ready.</returns>
    [SkipApiVersionValidation]
    [HttpGet("/ready")]
    public IActionResult Ready()
    {
        this.logger.LogTrace("Readiness probe hit.");
        return this.Ok();
    }

    /// <summary>
    /// Returns the public key of the frontend TLS certificate generated by ccr-proxy.
    /// The cert is shared via a volume mount from the ccr-proxy sidecar container.
    /// </summary>
    /// <returns>Public key, subject, thumbprint, and validity of the service cert.</returns>
    [SkipApiVersionValidation]
    [HttpGet("/report")]
    public async Task<IActionResult> GetReport()
    {
        string certPath = this.clientManager.CcrServiceCertPath;
        string consortiumManagerEndpoint = this.clientManager.ConsortiumManagerEndpoint;
        string membershipManagerEndpoint = this.clientManager.MembershipManagerEndpoint;
        string analyticsWorkloadId = this.clientManager.AnalyticsWorkloadId;

        if (!System.IO.File.Exists(certPath))
        {
            this.logger.LogError(
                "CCR proxy generated service certificate not found at {CertPath}.",
                certPath);
            return this.NotFound(
                new { error = "CCR proxy generated service certificate not available." });
        }

        try
        {
            string certPem = System.IO.File.ReadAllText(certPath);

            // Collect settings/configuration details
            var settings = new Dictionary<string, string>
            {
                [SettingName.ConsortiumManagerEndpoint] = consortiumManagerEndpoint,
                [SettingName.MembershipManagerEndpoint] = membershipManagerEndpoint,
                [SettingName.AnalyticsWorkloadId] = analyticsWorkloadId,
            };

            var reportDataPayload = JsonSerializer.Serialize(
                new FrontendServiceCertReportDataContent
                {
                    Certificate = certPem,
                    Settings = settings,
                });
            var reportDataPayloadBytes = Encoding.UTF8.GetBytes(reportDataPayload);
            string platform;
            SnpCACIAttestationReport? report = null;
            if (Attestation.IsSnpCACI())
            {
                platform = "snp";
                report = (await Attestation.GetCACIReportAsync(reportDataPayloadBytes)).SnpCaci;
            }
            else
            {
                platform = "virtual";
            }

            return this.Ok(new FrontendReport
            {
                Platform = platform,
                Report = report,
                ReportDataPayload = Convert.ToBase64String(reportDataPayloadBytes),
            });
        }
        catch (Exception ex)
        {
            this.logger.LogError(ex, "Failed to read service certificate.");
            return this.StatusCode(
                500,
                new { error = "Failed to read service certificate." });
        }
    }

    [SkipApiVersionValidation]
    [HttpGet("/checkConnectionsInit")]
    public async Task CheckOtherServiceConnectionInit()
    {
        this.logger.LogInformation(
            $"Checking connectivity to other services for initialization.");
        await this.clientManager.GetMembershipManagerClientAsync();
        await this.clientManager.GetConsortiumManagerClientAsync();
    }
}
