// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Cleanroom.Governance.Client.Proxy;

namespace Cleanroom.Governance.Client.Proxy.Controllers
{
    [ApiController]
    public partial class MemberDocumentsController : ControllerBase
    {

        public MemberDocumentsController(IMemberDocuments operations)
        {
            MemberDocumentsImpl = operations;
        }
        internal virtual IMemberDocuments MemberDocumentsImpl { get; }

        ///<summary>
        /// Lists member documents. Token mode only.
        ///</summary>
        [HttpGet]
        [Route("/memberdocuments")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(MemberDocumentsList))]
        public virtual async Task<IActionResult> ListMemberDocuments()
        {
            var result = await MemberDocumentsImpl.ListMemberDocumentsAsync();
            return Ok(result);
        }

        ///<summary>
        /// Gets member document. Token mode only.
        ///</summary>
        [HttpGet]
        [Route("/memberdocuments/{documentId}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(GetMemberDocumentResponse))]
        public virtual async Task<IActionResult> GetMemberDocument(string documentId)
        {
            var result = await MemberDocumentsImpl.GetMemberDocumentAsync(documentId);
            return Ok(result);
        }

        ///<summary>
        /// Updates member document. Token mode only.
        ///</summary>
        [HttpPut]
        [Route("/memberdocuments/{documentId}")]
        [ProducesResponseType((int)HttpStatusCode.NoContent, Type = typeof(void))]
        public virtual async Task<IActionResult> UpdateMemberDocument(string documentId, DocumentData body)
        {
            await MemberDocumentsImpl.UpdateMemberDocumentAsync(documentId, body);
            return NoContent();
        }

        ///<summary>
        /// Proposes member document change. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/memberdocuments/{documentId}/propose")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(ProposalResponse))]
        public virtual async Task<IActionResult> ProposeMemberDocumentChange(string documentId, DocumentProposal body)
        {
            var result = await MemberDocumentsImpl.ProposeMemberDocumentChangeAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Votes to accept member document. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/memberdocuments/{documentId}/vote_accept")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(VoteResponse))]
        public virtual async Task<IActionResult> VoteAcceptMemberDocument(string documentId, ProposalVote body)
        {
            var result = await MemberDocumentsImpl.VoteAcceptMemberDocumentAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Votes to reject member document. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/memberdocuments/{documentId}/vote_reject")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(VoteResponse))]
        public virtual async Task<IActionResult> VoteRejectMemberDocument(string documentId, ProposalVote body)
        {
            var result = await MemberDocumentsImpl.VoteRejectMemberDocumentAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Casts custom ballot on member document. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/memberdocuments/{documentId}/vote")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(VoteResponse))]
        public virtual async Task<IActionResult> VoteOnMemberDocument(string documentId, CustomBallotVote body)
        {
            var result = await MemberDocumentsImpl.VoteOnMemberDocumentAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Retrieves member document with attestation. Attestation mode only. Requires
        /// public key and attestation report. Response is encrypted with provided
        /// public key.
        ///</summary>
        [HttpPost]
        [Route("/memberdocuments/{documentId}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(EncryptedResponse))]
        public virtual async Task<IActionResult> GetMemberDocumentWithAttestation(string documentId, DocumentRetrievalRequest body)
        {
            var result = await MemberDocumentsImpl.GetMemberDocumentWithAttestationAsync(documentId, body);
            return Ok(result);
        }

    }
}
