// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Cleanroom.Governance.Client.Proxy;

namespace Cleanroom.Governance.Client.Proxy.Controllers
{
    [ApiController]
    public partial class UserDocumentsController : ControllerBase
    {

        public UserDocumentsController(IUserDocuments operations)
        {
            UserDocumentsImpl = operations;
        }
        internal virtual IUserDocuments UserDocumentsImpl { get; }

        ///<summary>
        /// Lists user documents. Token mode only.
        ///</summary>
        [HttpGet]
        [Route("/userdocuments")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(UserDocumentsListResponse))]
        public virtual async Task<IActionResult> ListUserDocuments([FromQuery(Name = "labelSelector")] string? labelSelector)
        {
            var result = await UserDocumentsImpl.ListUserDocumentsAsync(labelSelector);
            return Ok(result);
        }

        ///<summary>
        /// Gets user document. Token mode only.
        ///</summary>
        [HttpGet]
        [Route("/userdocuments/{documentId}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(UserDocumentResponse))]
        public virtual async Task<IActionResult> GetUserDocument(string documentId)
        {
            var result = await UserDocumentsImpl.GetUserDocumentAsync(documentId);
            return Ok(result);
        }

        ///<summary>
        /// Updates user document. Token mode only.
        ///</summary>
        [HttpPut]
        [Route("/userdocuments/{documentId}")]
        [ProducesResponseType((int)HttpStatusCode.NoContent, Type = typeof(void))]
        public virtual async Task<IActionResult> UpdateUserDocument(string documentId, PutUserDocumentRequest body)
        {
            await UserDocumentsImpl.UpdateUserDocumentAsync(documentId, body);
            return NoContent();
        }

        ///<summary>
        /// Proposes user document change. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/propose")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(ProposalResponse))]
        public virtual async Task<IActionResult> ProposeUserDocumentChange(string documentId, UserDocumentProposal body)
        {
            var result = await UserDocumentsImpl.ProposeUserDocumentChangeAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Votes to accept user document. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/vote_accept")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(VoteResponse))]
        public virtual async Task<IActionResult> VoteAcceptUserDocument(string documentId, ProposalVote body)
        {
            var result = await UserDocumentsImpl.VoteAcceptUserDocumentAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Votes to reject user document. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/vote_reject")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(VoteResponse))]
        public virtual async Task<IActionResult> VoteRejectUserDocument(string documentId, ProposalVote body)
        {
            var result = await UserDocumentsImpl.VoteRejectUserDocumentAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Casts custom ballot on user document. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/vote")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(VoteResponse))]
        public virtual async Task<IActionResult> VoteOnUserDocument(string documentId, CustomBallotVote body)
        {
            var result = await UserDocumentsImpl.VoteOnUserDocumentAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Enables user document runtime option. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/runtimeoptions/{runtimeOption}/enable")]
        [ProducesResponseType((int)HttpStatusCode.NoContent, Type = typeof(void))]
        public virtual async Task<IActionResult> EnableUserDocumentRuntimeOption(string documentId, string runtimeOption)
        {
            await UserDocumentsImpl.EnableUserDocumentRuntimeOptionAsync(documentId, runtimeOption);
            return NoContent();
        }

        ///<summary>
        /// Disables user document runtime option. Token mode only.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/runtimeoptions/{runtimeOption}/disable")]
        [ProducesResponseType((int)HttpStatusCode.NoContent, Type = typeof(void))]
        public virtual async Task<IActionResult> DisableUserDocumentRuntimeOption(string documentId, string runtimeOption)
        {
            await UserDocumentsImpl.DisableUserDocumentRuntimeOptionAsync(documentId, runtimeOption);
            return NoContent();
        }

        ///<summary>
        /// Checks user document runtime option status. Works in both modes.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/checkstatus/{runtimeOption}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(RuntimeOptionStatusResponse))]
        public virtual async Task<IActionResult> CheckUserDocumentRuntimeOptionStatus(string documentId, string runtimeOption)
        {
            var result = await UserDocumentsImpl.CheckUserDocumentRuntimeOptionStatusAsync(documentId, runtimeOption);
            return Ok(result);
        }

        ///<summary>
        /// Retrieves user document with attestation. Attestation mode only. Requires
        /// public key and attestation report. Response is encrypted with provided
        /// public key.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(EncryptedResponse))]
        public virtual async Task<IActionResult> GetUserDocumentWithAttestation(string documentId, DocumentRetrievalRequest body)
        {
            var result = await UserDocumentsImpl.GetUserDocumentWithAttestationAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Checks user document execution consent with attestation. Attestation mode
        /// only. Request must include SNP attestation report.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/consentcheck/execution")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(ConsentCheckResponse))]
        public virtual async Task<IActionResult> CheckExecutionConsentAttestation(string documentId, AttestationRequest body)
        {
            var result = await UserDocumentsImpl.CheckExecutionConsentAttestationAsync(documentId, body);
            return Ok(result);
        }

        ///<summary>
        /// Checks user document telemetry consent with attestation. Attestation mode
        /// only. Request must include SNP attestation report.
        ///</summary>
        [HttpPost]
        [Route("/userdocuments/{documentId}/consentcheck/telemetry")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(ConsentCheckResponse))]
        public virtual async Task<IActionResult> CheckTelemetryConsentAttestation(string documentId, AttestationRequest body)
        {
            var result = await UserDocumentsImpl.CheckTelemetryConsentAttestationAsync(documentId, body);
            return Ok(result);
        }

    }
}
