// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Cleanroom.Governance.Client.Proxy;

namespace Cleanroom.Governance.Client.Proxy.Controllers
{
    [ApiController]
    public partial class UsersController : ControllerBase
    {

        public UsersController(IUsers operations)
        {
            UsersImpl = operations;
        }
        internal virtual IUsers UsersImpl { get; }

        ///<summary>
        /// Lists users. Token mode only.
        ///</summary>
        [HttpGet]
        [Route("/users")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(UsersListResponse))]
        public virtual async Task<IActionResult> ListUsers()
        {
            var result = await UsersImpl.ListUsersAsync();
            return Ok(result);
        }

        ///<summary>
        /// Gets user details. Token mode only.
        ///</summary>
        [HttpGet]
        [Route("/users/{userId}")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(UserResponse))]
        public virtual async Task<IActionResult> GetUser(string userId)
        {
            var result = await UsersImpl.GetUserAsync(userId);
            return Ok(result);
        }

        ///<summary>
        /// Checks if user is active using JWT token from Authorization header. Works
        /// in both modes.
        ///</summary>
        [HttpPost]
        [Route("/users/isactive")]
        [ProducesResponseType((int)HttpStatusCode.OK, Type = typeof(UserActiveResponse))]
        public virtual async Task<IActionResult> IsUserActive([FromHeader(Name = "authorization")] string authorization)
        {
            var result = await UsersImpl.IsUserActiveAsync(authorization);
            return Ok(result);
        }

    }
}
