// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client.Proxy
{

    public interface ICleanRoomPolicy
    {
        ///<summary>
        /// Gets clean room policy. Token mode only.
        ///</summary>
        Task<CleanRoomPolicyResponse> GetCleanRoomPolicyAsync(string contractId);
        ///<summary>
        /// Proposes a clean room policy change. Token mode only.
        ///</summary>
        Task<ProposalResponse> ProposeCleanRoomPolicyChangeAsync(string contractId, CleanRoomPolicyProposal body);
        ///<summary>
        /// Gets delegate policy. Works in both modes.
        ///</summary>
        Task<DelegatePolicyResponse> GetDelegatePolicyAsync(string contractId, string delegateType, string delegateId);
        ///<summary>
        /// Lists delegate policies. Token mode only.
        ///</summary>
        Task<DelegatePoliciesListResponse> ListDelegatePoliciesAsync(string contractId);

    }
}
