// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client.Proxy
{

    public interface IEventsAttestation
    {
        ///<summary>
        /// Stores an event with attestation. Attestation mode only. Request must be
        /// signed and include SNP attestation report.
        ///</summary>
        Task StoreEventAsync(AttestedEventRequest body, string? id, string? scope);

    }
}
