// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client.Proxy
{

    public interface IEvents
    {
        ///<summary>
        /// Gets events. Token mode only.
        ///</summary>
        Task<EventsResponse> GetEventsAsync(string contractId, string? id, string? scope, long? fromSeqno, long? toSeqno, int? maxSeqnoPerPage);

    }
}
