// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client.Proxy
{

    public interface IMemberDocuments
    {
        ///<summary>
        /// Lists member documents. Token mode only.
        ///</summary>
        Task<MemberDocumentsList> ListMemberDocumentsAsync();
        ///<summary>
        /// Gets member document. Token mode only.
        ///</summary>
        Task<GetMemberDocumentResponse> GetMemberDocumentAsync(string documentId);
        ///<summary>
        /// Updates member document. Token mode only.
        ///</summary>
        Task UpdateMemberDocumentAsync(string documentId, DocumentData body);
        ///<summary>
        /// Proposes member document change. Token mode only.
        ///</summary>
        Task<ProposalResponse> ProposeMemberDocumentChangeAsync(string documentId, DocumentProposal body);
        ///<summary>
        /// Votes to accept member document. Token mode only.
        ///</summary>
        Task<VoteResponse> VoteAcceptMemberDocumentAsync(string documentId, ProposalVote body);
        ///<summary>
        /// Votes to reject member document. Token mode only.
        ///</summary>
        Task<VoteResponse> VoteRejectMemberDocumentAsync(string documentId, ProposalVote body);
        ///<summary>
        /// Casts custom ballot on member document. Token mode only.
        ///</summary>
        Task<VoteResponse> VoteOnMemberDocumentAsync(string documentId, CustomBallotVote body);
        ///<summary>
        /// Retrieves member document with attestation. Attestation mode only. Requires
        /// public key and attestation report. Response is encrypted with provided
        /// public key.
        ///</summary>
        Task<EncryptedResponse> GetMemberDocumentWithAttestationAsync(string documentId, DocumentRetrievalRequest body);

    }
}
