// Generated by @typespec/http-server-csharp
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TypeSpec.Helpers.JsonConverters;
using TypeSpec.Helpers;

namespace Cleanroom.Governance.Client.Proxy
{

    public interface IUserProposals
    {
        ///<summary>
        /// Creates user proposal. Token mode only.
        ///</summary>
        Task<ProposalResponse> CreateUserProposalAsync(UserProposalRequest body);
        ///<summary>
        /// Gets user proposal. Token mode only.
        ///</summary>
        Task<UserProposalResponse> GetUserProposalAsync(string proposalId);
        ///<summary>
        /// Gets user proposal status. Token mode only.
        ///</summary>
        Task<ProposalStatusResponse> GetUserProposalStatusAsync(string proposalId);
        ///<summary>
        /// Withdraws user proposal. Token mode only.
        ///</summary>
        Task<WithdrawResponse> WithdrawUserProposalAsync(string proposalId);
        ///<summary>
        /// Votes to accept user proposal. Token mode only.
        ///</summary>
        Task<VoteResponse> VoteAcceptUserProposalAsync(string proposalId);
        ///<summary>
        /// Votes to reject user proposal. Token mode only.
        ///</summary>
        Task<VoteResponse> VoteRejectUserProposalAsync(string proposalId);

    }
}
