// <auto-generated/>

#nullable disable

using System;
using System.ClientModel;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Generate endorsed cert request. </summary>
    public partial class GenerateEndorsedCertRequest : IJsonModel<GenerateEndorsedCertRequest>
    {
        /// <summary> Initializes a new instance of <see cref="GenerateEndorsedCertRequest"/> for deserialization. </summary>
        internal GenerateEndorsedCertRequest()
        {
        }

        /// <param name="data"> The data to parse. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual GenerateEndorsedCertRequest PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<GenerateEndorsedCertRequest>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions))
                    {
                        return DeserializeGenerateEndorsedCertRequest(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(GenerateEndorsedCertRequest)} does not support reading '{options.Format}' format.");
            }
        }

        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<GenerateEndorsedCertRequest>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, AzureCleanroomGovernanceClientContext.Default);
                default:
                    throw new FormatException($"The model {nameof(GenerateEndorsedCertRequest)} does not support writing '{options.Format}' format.");
            }
        }

        /// <param name="options"> The client options for reading and writing models. </param>
        BinaryData IPersistableModel<GenerateEndorsedCertRequest>.Write(ModelReaderWriterOptions options) => PersistableModelWriteCore(options);

        /// <param name="data"> The data to parse. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        GenerateEndorsedCertRequest IPersistableModel<GenerateEndorsedCertRequest>.Create(BinaryData data, ModelReaderWriterOptions options) => PersistableModelCreateCore(data, options);

        /// <param name="options"> The client options for reading and writing models. </param>
        string IPersistableModel<GenerateEndorsedCertRequest>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        /// <param name="generateEndorsedCertRequest"> The <see cref="GenerateEndorsedCertRequest"/> to serialize into <see cref="BinaryContent"/>. </param>
        public static implicit operator BinaryContent(GenerateEndorsedCertRequest generateEndorsedCertRequest)
        {
            if (generateEndorsedCertRequest == null)
            {
                return null;
            }
            return BinaryContent.Create(generateEndorsedCertRequest, ModelSerializationExtensions.WireOptions);
        }

        /// <param name="writer"> The JSON writer. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        void IJsonModel<GenerateEndorsedCertRequest>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        /// <param name="writer"> The JSON writer. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<GenerateEndorsedCertRequest>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(GenerateEndorsedCertRequest)} does not support writing '{format}' format.");
            }
            writer.WritePropertyName("attestation"u8);
            writer.WriteObjectValue(Attestation, options);
            writer.WritePropertyName("encrypt"u8);
            writer.WriteObjectValue(Encrypt, options);
            writer.WritePropertyName("sign"u8);
            writer.WriteObjectValue(Sign, options);
            writer.WritePropertyName("data"u8);
            writer.WriteStringValue(Data);
            if (options.Format != "W" && _additionalBinaryDataProperties != null)
            {
                foreach (var item in _additionalBinaryDataProperties)
                {
                    writer.WritePropertyName(item.Key);
#if NET6_0_OR_GREATER
                    writer.WriteRawValue(item.Value);
#else
                    using (JsonDocument document = JsonDocument.Parse(item.Value))
                    {
                        JsonSerializer.Serialize(writer, document.RootElement);
                    }
#endif
                }
            }
        }

        /// <param name="reader"> The JSON reader. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        GenerateEndorsedCertRequest IJsonModel<GenerateEndorsedCertRequest>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => JsonModelCreateCore(ref reader, options);

        /// <param name="reader"> The JSON reader. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual GenerateEndorsedCertRequest JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<GenerateEndorsedCertRequest>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(GenerateEndorsedCertRequest)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return DeserializeGenerateEndorsedCertRequest(document.RootElement, options);
        }

        /// <param name="element"> The JSON element to deserialize. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        internal static GenerateEndorsedCertRequest DeserializeGenerateEndorsedCertRequest(JsonElement element, ModelReaderWriterOptions options)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            SnpEvidence attestation = default;
            Encrypt encrypt = default;
            Sign sign = default;
            string data = default;
            IDictionary<string, BinaryData> additionalBinaryDataProperties = new ChangeTrackingDictionary<string, BinaryData>();
            foreach (var prop in element.EnumerateObject())
            {
                if (prop.NameEquals("attestation"u8))
                {
                    attestation = SnpEvidence.DeserializeSnpEvidence(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("encrypt"u8))
                {
                    encrypt = Encrypt.DeserializeEncrypt(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("sign"u8))
                {
                    sign = Sign.DeserializeSign(prop.Value, options);
                    continue;
                }
                if (prop.NameEquals("data"u8))
                {
                    data = prop.Value.GetString();
                    continue;
                }
                if (options.Format != "W")
                {
                    additionalBinaryDataProperties.Add(prop.Name, BinaryData.FromString(prop.Value.GetRawText()));
                }
            }
            return new GenerateEndorsedCertRequest(attestation, encrypt, sign, data, additionalBinaryDataProperties);
        }
    }
}
