// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Get accepted member document response. </summary>
    public partial class GetAcceptedMemberDocumentResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="GetAcceptedMemberDocumentResponse"/>. </summary>
        /// <param name="value"> Encrypted GetDocumentResponse content. </param>
        internal GetAcceptedMemberDocumentResponse(string value)
        {
            Value = value;
        }

        /// <summary> Initializes a new instance of <see cref="GetAcceptedMemberDocumentResponse"/>. </summary>
        /// <param name="value"> Encrypted GetDocumentResponse content. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal GetAcceptedMemberDocumentResponse(string value, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Value = value;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Encrypted GetDocumentResponse content. </summary>
        public string Value { get; }
    }
}
