// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Get proposal response. </summary>
    public partial class GetProposalResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="GetProposalResponse"/>. </summary>
        /// <param name="value"> Array of proposals. </param>
        internal GetProposalResponse(IEnumerable<Proposal> value)
        {
            Value = value.ToList();
        }

        /// <summary> Initializes a new instance of <see cref="GetProposalResponse"/>. </summary>
        /// <param name="nextLink"> Next link for pagination. </param>
        /// <param name="value"> Array of proposals. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal GetProposalResponse(string nextLink, IList<Proposal> value, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            NextLink = nextLink;
            Value = value;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Next link for pagination. </summary>
        public string NextLink { get; }

        /// <summary> Array of proposals. </summary>
        public IList<Proposal> Value { get; }
    }
}
