// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Get runtime option response. </summary>
    public partial class GetRuntimeOptionResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="GetRuntimeOptionResponse"/>. </summary>
        /// <param name="status"> Runtime option status. </param>
        internal GetRuntimeOptionResponse(string status)
        {
            Status = status;
            ProposalIds = new ChangeTrackingList<string>();
        }

        /// <summary> Initializes a new instance of <see cref="GetRuntimeOptionResponse"/>. </summary>
        /// <param name="status"> Runtime option status. </param>
        /// <param name="reason"> Error reason. </param>
        /// <param name="proposalIds"> Proposal IDs. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal GetRuntimeOptionResponse(string status, ErrorReason reason, IList<string> proposalIds, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Status = status;
            Reason = reason;
            ProposalIds = proposalIds;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Runtime option status. </summary>
        public string Status { get; }

        /// <summary> Error reason. </summary>
        public ErrorReason Reason { get; }

        /// <summary> Proposal IDs. </summary>
        public IList<string> ProposalIds { get; }
    }
}
