// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Get user proposal response. </summary>
    public partial class GetUserProposalResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="GetUserProposalResponse"/>. </summary>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <param name="name"> Proposal name. </param>
        /// <param name="approvers"> Approvers. </param>
        /// <param name="args"> Proposal arguments. </param>
        internal GetUserProposalResponse(string proposalId, string name, IEnumerable<UserProposalApprover> approvers, BinaryData args)
        {
            ProposalId = proposalId;
            Name = name;
            Approvers = approvers.ToList();
            Args = args;
        }

        /// <summary> Initializes a new instance of <see cref="GetUserProposalResponse"/>. </summary>
        /// <param name="proposalId"> Proposal ID. </param>
        /// <param name="name"> Proposal name. </param>
        /// <param name="approvers"> Approvers. </param>
        /// <param name="args"> Proposal arguments. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal GetUserProposalResponse(string proposalId, string name, IList<UserProposalApprover> approvers, BinaryData args, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            ProposalId = proposalId;
            Name = name;
            Approvers = approvers;
            Args = args;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Proposal ID. </summary>
        public string ProposalId { get; }

        /// <summary> Proposal name. </summary>
        public string Name { get; }

        /// <summary> Approvers. </summary>
        public IList<UserProposalApprover> Approvers { get; }

        /// <summary>
        /// Proposal arguments
        /// <para> To assign an object to this property use <see cref="BinaryData.FromObjectAsJson{T}(T, JsonSerializerOptions?)"/>. </para>
        /// <para> To assign an already formatted json string to this property use <see cref="BinaryData.FromString(string)"/>. </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term> BinaryData.FromObjectAsJson("foo"). </term>
        /// <description> Creates a payload of "foo". </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromString("\"foo\""). </term>
        /// <description> Creates a payload of "foo". </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromObjectAsJson(new { key = "value" }). </term>
        /// <description> Creates a payload of { "key": "value" }. </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromString("{\"key\": \"value\"}"). </term>
        /// <description> Creates a payload of { "key": "value" }. </description>
        /// </item>
        /// </list>
        /// </para>
        /// </summary>
        public BinaryData Args { get; }
    }
}
