// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Get user identity response. </summary>
    public partial class GetUserIdentityResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="GetUserIdentityResponse"/>. </summary>
        /// <param name="id"> User ID. </param>
        /// <param name="accountType"> Account type. </param>
        /// <param name="invitationId"> Invitation ID. </param>
        /// <param name="data"> User data. </param>
        internal GetUserIdentityResponse(string id, string accountType, string invitationId, BinaryData data)
        {
            Id = id;
            AccountType = accountType;
            InvitationId = invitationId;
            Data = data;
        }

        /// <summary> Initializes a new instance of <see cref="GetUserIdentityResponse"/>. </summary>
        /// <param name="id"> User ID. </param>
        /// <param name="accountType"> Account type. </param>
        /// <param name="invitationId"> Invitation ID. </param>
        /// <param name="data"> User data. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal GetUserIdentityResponse(string id, string accountType, string invitationId, BinaryData data, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Id = id;
            AccountType = accountType;
            InvitationId = invitationId;
            Data = data;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> User ID. </summary>
        public string Id { get; }

        /// <summary> Account type. </summary>
        public string AccountType { get; }

        /// <summary> Invitation ID. </summary>
        public string InvitationId { get; }

        /// <summary>
        /// User data
        /// <para> To assign an object to this property use <see cref="BinaryData.FromObjectAsJson{T}(T, JsonSerializerOptions?)"/>. </para>
        /// <para> To assign an already formatted json string to this property use <see cref="BinaryData.FromString(string)"/>. </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term> BinaryData.FromObjectAsJson("foo"). </term>
        /// <description> Creates a payload of "foo". </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromString("\"foo\""). </term>
        /// <description> Creates a payload of "foo". </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromObjectAsJson(new { key = "value" }). </term>
        /// <description> Creates a payload of { "key": "value" }. </description>
        /// </item>
        /// <item>
        /// <term> BinaryData.FromString("{\"key\": \"value\"}"). </term>
        /// <description> Creates a payload of { "key": "value" }. </description>
        /// </item>
        /// </list>
        /// </para>
        /// </summary>
        public BinaryData Data { get; }
    }
}
