// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> List contract response. </summary>
    public partial class ListContractResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="ListContractResponse"/>. </summary>
        /// <param name="id"> Contract ID. </param>
        internal ListContractResponse(string id)
        {
            Id = id;
        }

        /// <summary> Initializes a new instance of <see cref="ListContractResponse"/>. </summary>
        /// <param name="id"> Contract ID. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal ListContractResponse(string id, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Id = id;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Contract ID. </summary>
        public string Id { get; }
    }
}
