// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> List secret response. </summary>
    public partial class ListSecretResponse
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="ListSecretResponse"/>. </summary>
        /// <param name="secretId"> Secret ID. </param>
        internal ListSecretResponse(string secretId)
        {
            SecretId = secretId;
        }

        /// <summary> Initializes a new instance of <see cref="ListSecretResponse"/>. </summary>
        /// <param name="secretId"> Secret ID. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal ListSecretResponse(string secretId, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            SecretId = secretId;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Secret ID. </summary>
        public string SecretId { get; }
    }
}
