// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Put secret by clean room request. </summary>
    public partial class PutSecretByCleanRoomRequest
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="PutSecretByCleanRoomRequest"/>. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <param name="sign"> Signature. </param>
        /// <param name="data"> Encrypted data. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="attestation"/>, <paramref name="encrypt"/>, <paramref name="sign"/> or <paramref name="data"/> is null. </exception>
        public PutSecretByCleanRoomRequest(SnpEvidence attestation, Encrypt encrypt, Sign sign, string data)
        {
            Argument.AssertNotNull(attestation, nameof(attestation));
            Argument.AssertNotNull(encrypt, nameof(encrypt));
            Argument.AssertNotNull(sign, nameof(sign));
            Argument.AssertNotNull(data, nameof(data));

            Attestation = attestation;
            Encrypt = encrypt;
            Sign = sign;
            Data = data;
        }

        /// <summary> Initializes a new instance of <see cref="PutSecretByCleanRoomRequest"/>. </summary>
        /// <param name="attestation"> Attestation evidence. </param>
        /// <param name="encrypt"> Encryption info. </param>
        /// <param name="sign"> Signature. </param>
        /// <param name="data"> Encrypted data. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal PutSecretByCleanRoomRequest(SnpEvidence attestation, Encrypt encrypt, Sign sign, string data, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Attestation = attestation;
            Encrypt = encrypt;
            Sign = sign;
            Data = data;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Attestation evidence. </summary>
        public SnpEvidence Attestation { get; }

        /// <summary> Encryption info. </summary>
        public Encrypt Encrypt { get; }

        /// <summary> Signature. </summary>
        public Sign Sign { get; }

        /// <summary> Encrypted data. </summary>
        public string Data { get; }
    }
}
