// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> Signing info. </summary>
    public partial class SigningInfo
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="SigningInfo"/>. </summary>
        /// <param name="enabled"> Signing enabled. </param>
        internal SigningInfo(bool enabled)
        {
            Enabled = enabled;
        }

        /// <summary> Initializes a new instance of <see cref="SigningInfo"/>. </summary>
        /// <param name="enabled"> Signing enabled. </param>
        /// <param name="publicKeyPem"> PEM encoded public key. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal SigningInfo(bool enabled, string publicKeyPem, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Enabled = enabled;
            PublicKeyPem = publicKeyPem;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Signing enabled. </summary>
        public bool Enabled { get; }

        /// <summary> PEM encoded public key. </summary>
        public string PublicKeyPem { get; }
    }
}
