// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> User information. </summary>
    public partial class UserInfo
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="UserInfo"/>. </summary>
        /// <param name="userId"> User ID. </param>
        /// <param name="data"> User data. </param>
        internal UserInfo(string userId, UserData data)
        {
            UserId = userId;
            Data = data;
        }

        /// <summary> Initializes a new instance of <see cref="UserInfo"/>. </summary>
        /// <param name="userId"> User ID. </param>
        /// <param name="data"> User data. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal UserInfo(string userId, UserData data, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            UserId = userId;
            Data = data;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> User ID. </summary>
        public string UserId { get; }

        /// <summary> User data. </summary>
        public UserData Data { get; }
    }
}
