// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Cleanroom.Governance.Client
{
    /// <summary> User proposal approver. </summary>
    public partial class UserProposalApprover
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="UserProposalApprover"/>. </summary>
        /// <param name="approverId"> Approver ID. </param>
        /// <param name="approverIdType"> Approver ID type. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="approverId"/> or <paramref name="approverIdType"/> is null. </exception>
        public UserProposalApprover(string approverId, string approverIdType)
        {
            Argument.AssertNotNull(approverId, nameof(approverId));
            Argument.AssertNotNull(approverIdType, nameof(approverIdType));

            ApproverId = approverId;
            ApproverIdType = approverIdType;
        }

        /// <summary> Initializes a new instance of <see cref="UserProposalApprover"/>. </summary>
        /// <param name="approverId"> Approver ID. </param>
        /// <param name="approverIdType"> Approver ID type. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal UserProposalApprover(string approverId, string approverIdType, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            ApproverId = approverId;
            ApproverIdType = approverIdType;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Approver ID. </summary>
        public string ApproverId { get; set; }

        /// <summary> Approver ID type. </summary>
        public string ApproverIdType { get; set; }
    }
}
