# Use the official .NET Core SDK as the base image
FROM mcr.microsoft.com/mirror/docker/library/python:3.10-slim AS base

RUN pip install ruff

COPY ./python-linter.sh /python-linter.sh
RUN chmod +x /python-linter.sh
WORKDIR /
ENTRYPOINT ["/python-linter.sh"]