name: Cleanup stale resources created by PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"  # 00:00 IST daily (18:30 UTC prev day)

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cleanup-stale-resources:
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public", "1ES.JobId=cleanup-stale-pr-resources-${{ github.run_id }}-${{ github.run_attempt }}"]
    environment: pr
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ./.github/actions/setup-docker-on-data-disk

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Execute cleanup
      env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      run: pwsh ./.github/scripts/cleanup.ps1 -environment "pr"