name: "PR Validation: Cluster Provider"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read  # This is required for actions/checkout
  checks: write   # This is required to generate the test report


# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  pick-location:
    runs-on: ubuntu-latest
    outputs:
      location: ${{ steps.pick.outputs.location }}
    steps:
      - name: Pick a random Azure location
        id: pick
        shell: bash
        run: |
          # These are the locations where DC2as_v5 SKU is available that we use in Flex Node tests.
          # "westeurope" is intentionally left out of the list since we have been seeing issues related to AKS Free tier quotas in that region.
          # westus is removed as it is being used by another PR validation flow.
          locations=("northeurope" "germanywestcentral" "centralindia" "eastasia" "southeastasia" )
          index=$((RANDOM % ${#locations[@]}))
          echo "location=${locations[$index]}" >> "$GITHUB_OUTPUT"
          echo "Selected location: ${locations[$index]}"
          
  aks-cleanroom-cluster:
    needs: [pick-location]
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public", "1ES.JobId=aks-cleanroom-cluster-${{ github.run_id }}-${{ github.run_attempt }}"]
    environment: pr
    env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        RUN_ID: ${{ github.run_id }}
        JOB_ID: ${{ github.job }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-docker-on-data-disk

      - name: Login to Azure and refresh token
        uses: ./.github/actions/login-to-azure
        env:
          CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy CACI/VN2 backed cluster
        run: >
          pwsh ./samples/workloads/azcli/deploy-cluster.ps1
          -infraType aks
          -enableObservability
          -enableAnalytics
          -securityPolicyCreationOption cached-debug
          -registry acr
          -repo ${{ vars.ACR_URL }}
          -tag ${{ github.run_id }}
          -location ${{ needs.pick-location.outputs.location }}

      - name: Test Spark application run
        run: pwsh ./samples/workloads/azcli/test-cluster.ps1 -testAnalytics

      - name: Dump cleanroom-cluster-provider logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: docker compose -p cleanroom-cluster-provider logs

      - name: Dump cleanroom-cluster logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: pwsh ./samples/workloads/azcli/dump-cleanroom-cluster-logs.ps1

      - name: Upload generated artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: aks-cleanroom-cluster
          path: ./samples/workloads/azcli/sandbox_common
          overwrite: true
        if: always()

      - name: Delete resource groups
        if: success()
        shell: pwsh
        run: ./samples/ccf/azcli/remove-resources.ps1 -tag "github_actions=cleanroom-cluster-${{ github.job }}-${{ github.run_id }}"

  virtual-cleanroom-cluster:
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public", "1ES.JobId=virtual-cleanroom-cluster-${{ github.run_id }}-${{ github.run_attempt }}"]
    environment: pr
    env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        RUN_ID: ${{ github.run_id }}
        JOB_ID: ${{ github.job }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-docker-on-data-disk

      - name: Login to Azure and refresh token
        uses: ./.github/actions/login-to-azure
        env:
          CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy virtual cluster
        run: >
          pwsh ./samples/workloads/azcli/deploy-cluster.ps1
          -infraType virtual
          -enableObservability
          -enableAnalytics
          -enableKServeInferencing
          -registry acr
          -repo ${{ vars.ACR_URL }}
          -tag ${{ github.run_id }}

      - name: Test workload run
        run: pwsh ./samples/workloads/azcli/test-cluster.ps1 -testAnalytics -testKServeInferencing

      - name: Dump cleanroom-cluster-provider logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: docker compose -p cleanroom-cluster-provider logs

      - name: Dump cleanroom-cluster logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: pwsh ./samples/workloads/azcli/dump-cleanroom-cluster-logs.ps1

  aks-cleanroom-cluster-flexnode:
    needs: [pick-location]
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public", "1ES.JobId=aks-cleanroom-cluster-flexnode-${{ github.run_id }}-${{ github.run_attempt }}"]
    environment: pr
    env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        RUN_ID: ${{ github.run_id }}
        JOB_ID: ${{ github.job }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-docker-on-data-disk

      - name: Login to Azure and refresh token
        uses: ./.github/actions/login-to-azure
        env:
          CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy cluster with flex node
        run: >
          pwsh ./samples/workloads/azcli/deploy-cluster.ps1
          -infraType aks
          -enableObservability
          -enableFlexNode
          -flexNodeInsecure
          -flexNodeProvisionUsingSSH
          -enableKServeInferencing
          -registry acr
          -repo ${{ vars.ACR_URL }}
          -tag ${{ github.run_id }}
          -location ${{ needs.pick-location.outputs.location }}

      - name: Test flex node workloads
        run: pwsh ./samples/workloads/azcli/test-cluster.ps1 -testKServeInferencing

      - name: Dump cleanroom-cluster-provider logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: docker compose -p cleanroom-cluster-provider logs

      - name: Dump cleanroom-cluster logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: pwsh ./samples/workloads/azcli/dump-cleanroom-cluster-logs.ps1
        
      - name: Upload generated artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: aks-cleanroom-cluster-flexnode
          path: ./samples/workloads/azcli/sandbox_common
          overwrite: true
        if: always()

      - name: Delete resource groups
        if: success()
        shell: pwsh
        run: ./samples/ccf/azcli/remove-resources.ps1 -tag "github_actions=cleanroom-cluster-${{ github.job }}-${{ github.run_id }}"

  virtual-cleanroom-cluster-flexnode:
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public", "1ES.JobId=virtual-cleanroom-cluster-flexnode-${{ github.run_id }}-${{ github.run_attempt }}"]
    environment: pr
    env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        RUN_ID: ${{ github.run_id }}
        JOB_ID: ${{ github.job }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-docker-on-data-disk

      - name: Login to Azure and refresh token
        uses: ./.github/actions/login-to-azure
        env:
          CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy virtual cluster with flex node
        run: >
          pwsh ./samples/workloads/azcli/deploy-cluster.ps1
          -infraType virtual
          -registry acr
          -enableObservability
          -enableFlexNode
          -flexNodeInsecure
          -enableKServeInferencing
          -repo ${{ vars.ACR_URL }}
          -tag ${{ github.run_id }}

      - name: Test Flex Node workloads
        run: pwsh ./samples/workloads/azcli/test-cluster.ps1 -testKServeInferencing

      - name: Dump cleanroom-cluster-provider logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: docker compose -p cleanroom-cluster-provider logs

      - name: Dump cleanroom-cluster logs
        shell: pwsh
        if: ${{ !cancelled() }}
        run: pwsh ./samples/workloads/azcli/dump-cleanroom-cluster-logs.ps1
