name: "PR Validation: Flex Node Tests"

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  flex-node-test:
    runs-on: ["self-hosted", "1ES.Pool=azure-cleanroom-public", "1ES.JobId=flex-node-${{ github.run_id }}-${{ github.run_attempt }}"]
    environment: pr
    env:
      CLUSTER_NAME: api-server-proxy-ci
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-docker-on-data-disk

      - name: Install kind
        run: |
          if ! command -v kind &>/dev/null; then
            echo "Installing kind..."
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
          fi
          kind version

      - name: Install kubectl
        run: |
          if ! command -v kubectl &>/dev/null; then
            echo "Installing kubectl..."
            curl -Lo ./kubectl "https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          fi
          kubectl version --client

      - name: Run api-server-proxy unit tests
        run: |
          go test -v ./src/k8s-node/api-server-proxy/internal/apiserverproxy/...

      - name: Run kubelet-proxy unit tests
        run: |
          go test -v ./src/k8s-node/kubelet-proxy/internal/kubeletproxy/...

      - name: Run integration tests (Kind)
        run: >
          go test
          -tags "kind,integration,kubelet_proxy,api_server_proxy"
          -v -timeout 30m
          ./src/k8s-node/test/integration/

      - name: Login to Azure and refresh token
        uses: ./.github/actions/login-to-azure
        env:
          CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # TODO (HPrabh): The AKS integration tests require SSHing into the flex node VM which is not possible with the current GitHub Actions runner setup.
      # We need to deploy a ssh pod and then use that to execute commands on the node. Enable this when it is implemented.
      # - name: Run integration tests (AKS)
      #   run: >
      #     go test
      #     -tags "aks,integration,kubelet_proxy,api_server_proxy"
      #     -v -timeout 30m
      #     ./src/k8s-node/test/integration/
